/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.core.type.*;
import com.socotra.coremodel.*;
import com.socotra.coremodel.views.Internal;
import com.socotra.deployment.*;
import com.socotra.platform.tools.ULID;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.*;
import java.util.stream.Collectors;

public record FraudProtectionQuickQuote(
    @JsonView({Internal.class}) Element element
    ) implements FraudProtection, Validatable, Elemental, CustomerObject {

  public static final String TYPE = "FraudProtectionQuickQuote";

  public String type() { return TYPE; }

  public FraudProtectionQuickQuote maskData(DataMaskingLevel level) {
    return this;
  }

  public FraudProtectionQuickQuote anonymizeData() {
    return this;
  }

  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    Collection<ValidationItem> validationItems = new ArrayList<>();
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder()
        .elementType(type()).locator(element.locator());
    if (validationItemBuilder.hasErrors()) {
      validationItems.add(validationItemBuilder.build());
    }
    return validationItems;
  }

  public FraudProtectionQuickQuote applyDefaults(DeploymentConfig config) {
    FraudProtectionQuickQuoteBuilder builder = toBuilder();
    return builder.build();
  }

  public FraudProtectionQuickQuote applyAvailabilityRemovals(Instant referenceDate) {
    FraudProtectionQuickQuoteBuilder builder = toBuilder();
    return builder.build();
  }

  @JsonIgnore
  public ULID locator() {
    return element.locator();
  }

  public Element toElement(DeploymentFactory factory) {
    Map<String, Object> ct = Map.of();
    Collection<Element> subElements = List.of();
    Map<String, Object> data = Map.of();
    return element.toBuilder()
        .type(type())
        .elements(Collections.unmodifiableCollection(subElements))
        .coverageTerms(ct)
        .data(data)
        .category(ElementCategory.coverage)
        .build();
  }

  public static FraudProtectionQuickQuote fromElement(DeploymentFactory factory, Element element) {
    if (element == null) {
      return null;
    }
    return new FraudProtectionQuickQuote(
        element);
  }

  public static FraudProtectionQuickQuoteBuilder builder(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ULID staticLocator, Instant originalEffectiveTime) {
    Element origin = Element.builder()
        .tenantLocator(tenantLocator)
        .type("FraudProtectionQuickQuote")
        .locator(ULID.generate())
        .staticLocator(staticLocator)
        .rootLocator(rootLocator)
        .parentLocator(parentLocator)
        .originalEffectiveTime(originalEffectiveTime)
        .build();
    return new FraudProtectionQuickQuoteBuilder().element(origin);
  }

  public FraudProtectionQuickQuoteBuilder toBuilder() {
    return new FraudProtectionQuickQuoteBuilder()
        .element(this.element);
  }

  public static class FraudProtectionQuickQuoteBuilder {
    private Element element;
    public FraudProtectionQuickQuoteBuilder element(Element element) { this.element = element; return this; }

    private FraudProtectionQuickQuoteBuilder() {}

    public FraudProtectionQuickQuote build() {
      return new FraudProtectionQuickQuote(
          this.element
      );
    }
  }

}
