/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.core.type.*;
import com.socotra.coremodel.*;
import com.socotra.coremodel.views.Internal;
import com.socotra.deployment.*;
import com.socotra.platform.tools.ULID;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.*;
import java.util.stream.Collectors;

public record IdentityTheftProtectionPolicy(
    @JsonView({Internal.class}) Element element
    ) implements IdentityTheftProtection, Validatable, Elemental, CustomerObject {

  public static final String TYPE = "IdentityTheftProtectionPolicy";

  public String type() { return TYPE; }

  public IdentityTheftProtectionPolicy maskData(DataMaskingLevel level) {
    return this;
  }

  public IdentityTheftProtectionPolicy anonymizeData() {
    return this;
  }

  public Instant originalEffectiveTime() {
    return element.originalEffectiveTime().orElse(null);
  }
  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    Collection<ValidationItem> validationItems = new ArrayList<>();
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder()
        .elementType(type()).locator(element.locator());
    if (validationItemBuilder.hasErrors()) {
      validationItems.add(validationItemBuilder.build());
    }
    return validationItems;
  }

  public IdentityTheftProtectionPolicy applyDefaults(DeploymentConfig config) {
    IdentityTheftProtectionPolicyBuilder builder = toBuilder();
    return builder.build();
  }

  public IdentityTheftProtectionPolicy applyAvailabilityRemovals(Instant referenceDate) {
    IdentityTheftProtectionPolicyBuilder builder = toBuilder();
    return builder.build();
  }

  @JsonIgnore
  public ULID locator() {
    return element.locator();
  }

  public Element toElement(DeploymentFactory factory) {
    Map<String, Object> ct = Map.of();
    Collection<Element> subElements = List.of();
    Map<String, Object> data = Map.of();
    return element.toBuilder()
        .type(type())
        .elements(Collections.unmodifiableCollection(subElements))
        .coverageTerms(ct)
        .data(data)
        .category(ElementCategory.coverage)
        .build();
  }

  public static IdentityTheftProtectionPolicy fromElement(DeploymentFactory factory, Element element) {
    if (element == null) {
      return null;
    }
    return new IdentityTheftProtectionPolicy(
        element);
  }

  public static IdentityTheftProtectionPolicy copyFrom(UUID tenantLocator, ULID rootLocator, ULID parentLocator, IdentityTheftProtectionQuote other) {
    if (other == null) {
      return null;
    }
    IdentityTheftProtectionPolicyBuilder builder = builder(tenantLocator, rootLocator, parentLocator, other.element().locator(), other.element().originalEffectiveTime().orElse(null));
    return builder
        .build();
  }

  public static IdentityTheftProtectionPolicy copyFrom(UUID tenantLocator, ULID rootLocator, ULID parentLocator, IdentityTheftProtectionPolicy other) {
    if (other == null) {
      return null;
    }
    IdentityTheftProtectionPolicyBuilder builder = builder(tenantLocator, rootLocator, parentLocator, other.element().staticLocator(), other.element().originalEffectiveTime().orElse(null));
    return builder
        .build();
  }

  public static IdentityTheftProtectionPolicyBuilder builder(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ULID staticLocator, Instant originalEffectiveTime) {
    Element origin = Element.builder()
        .tenantLocator(tenantLocator)
        .type("IdentityTheftProtectionPolicy")
        .locator(ULID.generate())
        .staticLocator(staticLocator)
        .rootLocator(rootLocator)
        .parentLocator(parentLocator)
        .originalEffectiveTime(originalEffectiveTime)
        .build();
    return new IdentityTheftProtectionPolicyBuilder().element(origin);
  }

  public IdentityTheftProtectionPolicyBuilder toBuilder() {
    return new IdentityTheftProtectionPolicyBuilder()
        .element(this.element);
  }

  public static class IdentityTheftProtectionPolicyBuilder {
    private Element element;
    public IdentityTheftProtectionPolicyBuilder element(Element element) { this.element = element; return this; }

    private IdentityTheftProtectionPolicyBuilder() {}

    public IdentityTheftProtectionPolicy build() {
      return new IdentityTheftProtectionPolicy(
          this.element
      );
    }
  }

}
