/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.socotra.coremodel.*;

import java.time.*;
import java.util.*;
import java.math.*;
import java.util.function.Consumer;

import com.socotra.platform.tools.ULID;

public interface PremiumCreditCardProtection extends Chargeable {
  FraudProtection fraudProtection();
  IdentityTheftProtection identityTheftProtection();
  CardReplacement cardReplacement();
  UnauthorizedUse unauthorizedUse();
  PurchaseProtection purchaseProtection();
  TravelEmergencyAssistance travelEmergencyAssistance();
  FraudLimit fraudLimit();
  IdentityTheftLimit identityTheftLimit();
  PurchaseProtectionLimit purchaseProtectionLimit();
  TravelAssistanceLimit travelAssistanceLimit();
  CardReplacementBenefit cardReplacementBenefit();
  PremiumDeductible premiumDeductible();
  PremiumCreditCardProtectionData data();

  @Override
  default void consumeChargeableElements(Consumer<Chargeable> consumer) {
    if(fraudProtection() != null) { consumer.accept(fraudProtection()); }
    if(identityTheftProtection() != null) { consumer.accept(identityTheftProtection()); }
    if(cardReplacement() != null) { consumer.accept(cardReplacement()); }
    if(unauthorizedUse() != null) { consumer.accept(unauthorizedUse()); }
    if(purchaseProtection() != null) { consumer.accept(purchaseProtection()); }
    if(travelEmergencyAssistance() != null) { consumer.accept(travelEmergencyAssistance()); }
  }

  public interface PremiumCreditCardProtectionData {
    BigDecimal averageMonthlySpend();
    BigDecimal bankRelationshipYears();
    LocalDate cardIssuedDate();
    String cardType();
    BigDecimal creditLimit();
    String frequentTraveler();
    String hasPreviousClaims();
    BigDecimal numberOfCards();
  }

  @Override
  default Collection<Charge> charges() {
    return Arrays.asList(Charge.values());
  }

  enum Charge implements com.socotra.coremodel.ChargeType {
    premium(ChargeType.premium),
    commission(ChargeType.commission),
    tax(ChargeType.tax);

    private final ChargeType chargeType;

    Charge(ChargeType chargeType) {
      this.chargeType = chargeType;
    }

    @Override
    public ChargeCategory category() {
      return chargeType.category();
    }
  }
}
