/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.core.type.*;
import com.socotra.coremodel.*;
import com.socotra.coremodel.views.Internal;
import com.socotra.deployment.*;
import com.socotra.platform.tools.ULID;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.*;
import java.util.stream.Collectors;

public record UnauthorizedUseQuickQuote(
    @JsonView({Internal.class}) Element element
    ) implements UnauthorizedUse, Validatable, Elemental, CustomerObject {

  public static final String TYPE = "UnauthorizedUseQuickQuote";

  public String type() { return TYPE; }

  public UnauthorizedUseQuickQuote maskData(DataMaskingLevel level) {
    return this;
  }

  public UnauthorizedUseQuickQuote anonymizeData() {
    return this;
  }

  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    Collection<ValidationItem> validationItems = new ArrayList<>();
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder()
        .elementType(type()).locator(element.locator());
    if (validationItemBuilder.hasErrors()) {
      validationItems.add(validationItemBuilder.build());
    }
    return validationItems;
  }

  public UnauthorizedUseQuickQuote applyDefaults(DeploymentConfig config) {
    UnauthorizedUseQuickQuoteBuilder builder = toBuilder();
    return builder.build();
  }

  public UnauthorizedUseQuickQuote applyAvailabilityRemovals(Instant referenceDate) {
    UnauthorizedUseQuickQuoteBuilder builder = toBuilder();
    return builder.build();
  }

  @JsonIgnore
  public ULID locator() {
    return element.locator();
  }

  public Element toElement(DeploymentFactory factory) {
    Map<String, Object> ct = Map.of();
    Collection<Element> subElements = List.of();
    Map<String, Object> data = Map.of();
    return element.toBuilder()
        .type(type())
        .elements(Collections.unmodifiableCollection(subElements))
        .coverageTerms(ct)
        .data(data)
        .category(ElementCategory.coverage)
        .build();
  }

  public static UnauthorizedUseQuickQuote fromElement(DeploymentFactory factory, Element element) {
    if (element == null) {
      return null;
    }
    return new UnauthorizedUseQuickQuote(
        element);
  }

  public static UnauthorizedUseQuickQuoteBuilder builder(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ULID staticLocator, Instant originalEffectiveTime) {
    Element origin = Element.builder()
        .tenantLocator(tenantLocator)
        .type("UnauthorizedUseQuickQuote")
        .locator(ULID.generate())
        .staticLocator(staticLocator)
        .rootLocator(rootLocator)
        .parentLocator(parentLocator)
        .originalEffectiveTime(originalEffectiveTime)
        .build();
    return new UnauthorizedUseQuickQuoteBuilder().element(origin);
  }

  public UnauthorizedUseQuickQuoteBuilder toBuilder() {
    return new UnauthorizedUseQuickQuoteBuilder()
        .element(this.element);
  }

  public static class UnauthorizedUseQuickQuoteBuilder {
    private Element element;
    public UnauthorizedUseQuickQuoteBuilder element(Element element) { this.element = element; return this; }

    private UnauthorizedUseQuickQuoteBuilder() {}

    public UnauthorizedUseQuickQuote build() {
      return new UnauthorizedUseQuickQuote(
          this.element
      );
    }
  }

}
