/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Account(
    com.socotra.platform.tools.ULID locator,
    java.lang.String type,
    com.socotra.coremodel.AccountState accountState,
    Map<java.lang.String,java.lang.Object> data,
    java.time.Instant createdAt,
    java.util.UUID createdBy,
    Optional<java.lang.String> delinquencyPlanName,
    Optional<java.lang.String> shortfallTolerancePlanName,
    Optional<Preferences> preferences,
    Optional<java.lang.String> autoRenewalPlanName,
    Optional<java.lang.String> excessCreditPlanName,
    com.socotra.coremodel.BillingLevel billingLevel,
    Optional<java.lang.String> invoiceDocument,
    Optional<byte[]> securityId,
    Optional<java.lang.String> region,
    Optional<java.lang.String> accountNumber,
    Collection<ContactRoles> contacts,
    Optional<java.lang.String> timezone,
    Optional<java.time.Instant> anonymizedAt,
    Optional<java.lang.String> invoicingPlanName,
    Optional<java.lang.String> paymentExecutionRetryPlanName,
    Optional<com.socotra.platform.tools.ULID> configVersionLocator
)  implements com.socotra.coremodel.interfaces.Account
{
  public Account {
    accountState = accountState == null ? com.socotra.coremodel.AccountState.draft : accountState;

    delinquencyPlanName = delinquencyPlanName == null ? Optional.empty() : delinquencyPlanName;
    shortfallTolerancePlanName = shortfallTolerancePlanName == null ? Optional.empty() : shortfallTolerancePlanName;
    preferences = preferences == null ? Optional.empty() : preferences;
    autoRenewalPlanName = autoRenewalPlanName == null ? Optional.empty() : autoRenewalPlanName;
    excessCreditPlanName = excessCreditPlanName == null ? Optional.empty() : excessCreditPlanName;
    billingLevel = billingLevel == null ? com.socotra.coremodel.BillingLevel.policy : billingLevel;

    invoiceDocument = invoiceDocument == null ? Optional.empty() : invoiceDocument;
    securityId = securityId == null ? Optional.empty() : securityId;
    region = region == null ? Optional.empty() : region;
    accountNumber = accountNumber == null ? Optional.empty() : accountNumber;
    timezone = timezone == null ? Optional.empty() : timezone;
    anonymizedAt = anonymizedAt == null ? Optional.empty() : anonymizedAt;
    invoicingPlanName = invoicingPlanName == null ? Optional.empty() : invoicingPlanName;
    paymentExecutionRetryPlanName = paymentExecutionRetryPlanName == null ? Optional.empty() : paymentExecutionRetryPlanName;
    configVersionLocator = configVersionLocator == null ? Optional.empty() : configVersionLocator;
    data = data == null ? Map.of() : data.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));
    contacts = contacts == null ? List.of() : List.copyOf(contacts);
    if(data == null) {
      data = Map.of();
    }
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(type, "type is required but it is null");
    Objects.requireNonNull(accountState, "accountState is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(createdBy, "createdBy is required but it is null");
    Objects.requireNonNull(delinquencyPlanName, "delinquencyPlanName is required but it is null");
    Objects.requireNonNull(shortfallTolerancePlanName, "shortfallTolerancePlanName is required but it is null");
    Objects.requireNonNull(preferences, "preferences is required but it is null");
    Objects.requireNonNull(autoRenewalPlanName, "autoRenewalPlanName is required but it is null");
    Objects.requireNonNull(excessCreditPlanName, "excessCreditPlanName is required but it is null");
    Objects.requireNonNull(billingLevel, "billingLevel is required but it is null");
    Objects.requireNonNull(invoiceDocument, "invoiceDocument is required but it is null");
    Objects.requireNonNull(securityId, "securityId is required but it is null");
    Objects.requireNonNull(region, "region is required but it is null");
    Objects.requireNonNull(accountNumber, "accountNumber is required but it is null");
    Objects.requireNonNull(timezone, "timezone is required but it is null");
    Objects.requireNonNull(anonymizedAt, "anonymizedAt is required but it is null");
    Objects.requireNonNull(invoicingPlanName, "invoicingPlanName is required but it is null");
    Objects.requireNonNull(paymentExecutionRetryPlanName, "paymentExecutionRetryPlanName is required but it is null");
    Objects.requireNonNull(configVersionLocator, "configVersionLocator is required but it is null");

 }

  public com.socotra.coremodel.protobuf.Account toProto() {
    com.socotra.coremodel.protobuf.Account.Builder builder = com.socotra.coremodel.protobuf.Account.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (type != null) {
      builder.setType(this.type);
    }
    if (accountState != null) {
      builder.setAccountState(this.accountState.name());
    }
    builder.putAllData(data.isEmpty() ? Map.of() :data.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> com.socotra.protobuf.Object.newBuilder().setData(MarshallerFactory.getFor(e.getValue().getClass()).write(e.getValue())).setType(e.getValue().getClass().getName()).build())));
    if (createdAt != null) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.getEpochSecond()).setNanos(createdAt.getNano()).build());
    }
    if (createdBy != null) {
      builder.setCreatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(createdBy.getMostSignificantBits()).setLsb(createdBy.getLeastSignificantBits()).build());
    }
    if (delinquencyPlanName.isPresent()) {
      builder.setDelinquencyPlanName(this.delinquencyPlanName.get());
    }
    if (shortfallTolerancePlanName.isPresent()) {
      builder.setShortfallTolerancePlanName(this.shortfallTolerancePlanName.get());
    }
    if (preferences.isPresent()) {
      builder.setPreferences(preferences.get().toProto());
    }
    if (autoRenewalPlanName.isPresent()) {
      builder.setAutoRenewalPlanName(this.autoRenewalPlanName.get());
    }
    if (excessCreditPlanName.isPresent()) {
      builder.setExcessCreditPlanName(this.excessCreditPlanName.get());
    }
    if (billingLevel != null) {
      builder.setBillingLevel(this.billingLevel.name());
    }
    if (invoiceDocument.isPresent()) {
      builder.setInvoiceDocument(this.invoiceDocument.get());
    }
    if (securityId.isPresent()) {
      builder.setSecurityId(com.google.protobuf.ByteString.copyFrom(securityId.get()));
    }
    if (region.isPresent()) {
      builder.setRegion(this.region.get());
    }
    if (accountNumber.isPresent()) {
      builder.setAccountNumber(this.accountNumber.get());
    }
    builder.addAllContacts(this.contacts.stream().map(f -> f.toProto()).toList());
    if (timezone.isPresent()) {
      builder.setTimezone(this.timezone.get());
    }
    if (anonymizedAt.isPresent()) {
      builder.setAnonymizedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(anonymizedAt.get().getEpochSecond()).setNanos(anonymizedAt.get().getNano()).build());
    }
    if (invoicingPlanName.isPresent()) {
      builder.setInvoicingPlanName(this.invoicingPlanName.get());
    }
    if (paymentExecutionRetryPlanName.isPresent()) {
      builder.setPaymentExecutionRetryPlanName(this.paymentExecutionRetryPlanName.get());
    }
    if (configVersionLocator.isPresent()) {
      builder.setConfigVersionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(configVersionLocator.get().getMostSignificantBits()).setLsb(configVersionLocator.get().getLeastSignificantBits()).build());
    }
    return builder.build();
  }

  public Account toTransport() {
    return toBuilder()
        .contacts(List.of())
        .build();
  }

  public static Account fromProto(com.socotra.coremodel.protobuf.Account proto) {
    return new Account(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getType(),
         proto.getAccountState().isEmpty() ? null : com.socotra.coremodel.AccountState.valueOf(proto.getAccountState()),
         proto.getDataMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> MarshallerFactory.getFor(java.lang.Object.class).read(e.getValue().getData(), e.getValue().getType()))),
         java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos()),
         new java.util.UUID(proto.getCreatedBy().getMsb(), proto.getCreatedBy().getLsb()),
         proto.hasDelinquencyPlanName() ? Optional.of(proto.getDelinquencyPlanName()) : Optional.empty(),
         proto.hasShortfallTolerancePlanName() ? Optional.of(proto.getShortfallTolerancePlanName()) : Optional.empty(),
         proto.hasPreferences() ? Optional.of(Preferences.fromProto(proto.getPreferences())) : Optional.empty(),
         proto.hasAutoRenewalPlanName() ? Optional.of(proto.getAutoRenewalPlanName()) : Optional.empty(),
         proto.hasExcessCreditPlanName() ? Optional.of(proto.getExcessCreditPlanName()) : Optional.empty(),
         proto.getBillingLevel().isEmpty() ? null : com.socotra.coremodel.BillingLevel.valueOf(proto.getBillingLevel()),
         proto.hasInvoiceDocument() ? Optional.of(proto.getInvoiceDocument()) : Optional.empty(),
         proto.hasSecurityId() ? Optional.of(proto.getSecurityId().toByteArray()) : Optional.empty(),
         proto.hasRegion() ? Optional.of(proto.getRegion()) : Optional.empty(),
         proto.hasAccountNumber() ? Optional.of(proto.getAccountNumber()) : Optional.empty(),
         proto.getContactsList().stream().map(f -> ContactRoles.fromProto(f)).toList(),
         proto.hasTimezone() ? Optional.of(proto.getTimezone()) : Optional.empty(),
         proto.hasAnonymizedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAnonymizedAt().getSeconds(), proto.getAnonymizedAt().getNanos())) : Optional.empty(),
         proto.hasInvoicingPlanName() ? Optional.of(proto.getInvoicingPlanName()) : Optional.empty(),
         proto.hasPaymentExecutionRetryPlanName() ? Optional.of(proto.getPaymentExecutionRetryPlanName()) : Optional.empty(),
         proto.hasConfigVersionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getConfigVersionLocator().getMsb(), proto.getConfigVersionLocator().getLsb())) : Optional.empty()
    );
  }

  public static AccountBuilder builder() {
    return new AccountBuilder();
  }

  public static Account copyFrom(com.socotra.coremodel.interfaces.Account other) {
    return new Account(
        other.locator(),
        other.type(),
        other.accountState(),
        other.data(),
        other.createdAt(),
        other.createdBy(),
        other.delinquencyPlanName(),
        other.shortfallTolerancePlanName(),
        other.preferences(),
        other.autoRenewalPlanName(),
        other.excessCreditPlanName(),
        other.billingLevel(),
        other.invoiceDocument(),
        other.securityId(),
        other.region(),
        other.accountNumber(),
        other.contacts(),
        other.timezone(),
        other.anonymizedAt(),
        other.invoicingPlanName(),
        other.paymentExecutionRetryPlanName(),
        other.configVersionLocator()
    );
  }

  public AccountBuilder toBuilder() {
    return new AccountBuilder()
       .locator(this.locator)
       .type(this.type)
       .accountState(this.accountState)
       .data(this.data)
       .createdAt(this.createdAt)
       .createdBy(this.createdBy)
       .delinquencyPlanName(this.delinquencyPlanName)
       .shortfallTolerancePlanName(this.shortfallTolerancePlanName)
       .preferences(this.preferences)
       .autoRenewalPlanName(this.autoRenewalPlanName)
       .excessCreditPlanName(this.excessCreditPlanName)
       .billingLevel(this.billingLevel)
       .invoiceDocument(this.invoiceDocument)
       .securityId(this.securityId)
       .region(this.region)
       .accountNumber(this.accountNumber)
       .contacts(this.contacts)
       .timezone(this.timezone)
       .anonymizedAt(this.anonymizedAt)
       .invoicingPlanName(this.invoicingPlanName)
       .paymentExecutionRetryPlanName(this.paymentExecutionRetryPlanName)
       .configVersionLocator(this.configVersionLocator);
  }


  @Override
  public Account mergeWith(DeploymentFactory factory, CustomerObject customerObject) {
     if (!(customerObject instanceof AccountDefinition)) {
       throw new IllegalArgumentException();
     }
     AccountDefinition<?> accountDefinition = (AccountDefinition) customerObject;
     return this.toBuilder()
         .data(CustomerDataHolder.transform(factory, accountDefinition.data()))
         .delinquencyPlanName(accountDefinition.delinquencyPlanName())
         .excessCreditPlanName(accountDefinition.excessCreditPlanName())
         .shortfallTolerancePlanName(accountDefinition.shortfallTolerancePlanName())
         .preferences(accountDefinition.preferences())
         .billingLevel(accountDefinition.billingLevel())
         .invoiceDocument(accountDefinition.invoiceDocument())
         .build();
  }

  public static class AccountBuilder {
    private com.socotra.platform.tools.ULID locator;
    public AccountBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private java.lang.String type;
    public AccountBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private com.socotra.coremodel.AccountState accountState;
    public AccountBuilder accountState(com.socotra.coremodel.AccountState accountState) {
      this.accountState = accountState;
      return this;
    }
    private Map<java.lang.String,java.lang.Object> data;
    public AccountBuilder data(Map<java.lang.String,java.lang.Object> data) {
      this.data = data;
      return this;
    }
    private java.time.Instant createdAt;
    public AccountBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    private java.util.UUID createdBy;
    public AccountBuilder createdBy(java.util.UUID createdBy) {
      this.createdBy = createdBy;
      return this;
    }
    private Optional<java.lang.String> delinquencyPlanName;
    public AccountBuilder delinquencyPlanName(Optional<java.lang.String> delinquencyPlanName) {
      this.delinquencyPlanName = delinquencyPlanName;
      return this;
    }
    public AccountBuilder delinquencyPlanName(java.lang.String delinquencyPlanName) {
      this.delinquencyPlanName = Optional.ofNullable(delinquencyPlanName);
      return this;
    }
    private Optional<java.lang.String> shortfallTolerancePlanName;
    public AccountBuilder shortfallTolerancePlanName(Optional<java.lang.String> shortfallTolerancePlanName) {
      this.shortfallTolerancePlanName = shortfallTolerancePlanName;
      return this;
    }
    public AccountBuilder shortfallTolerancePlanName(java.lang.String shortfallTolerancePlanName) {
      this.shortfallTolerancePlanName = Optional.ofNullable(shortfallTolerancePlanName);
      return this;
    }
    private Optional<Preferences> preferences;
    public AccountBuilder preferences(Optional<Preferences> preferences) {
      this.preferences = preferences;
      return this;
    }
    public AccountBuilder preferences(Preferences preferences) {
      this.preferences = Optional.ofNullable(preferences);
      return this;
    }
    private Optional<java.lang.String> autoRenewalPlanName;
    public AccountBuilder autoRenewalPlanName(Optional<java.lang.String> autoRenewalPlanName) {
      this.autoRenewalPlanName = autoRenewalPlanName;
      return this;
    }
    public AccountBuilder autoRenewalPlanName(java.lang.String autoRenewalPlanName) {
      this.autoRenewalPlanName = Optional.ofNullable(autoRenewalPlanName);
      return this;
    }
    private Optional<java.lang.String> excessCreditPlanName;
    public AccountBuilder excessCreditPlanName(Optional<java.lang.String> excessCreditPlanName) {
      this.excessCreditPlanName = excessCreditPlanName;
      return this;
    }
    public AccountBuilder excessCreditPlanName(java.lang.String excessCreditPlanName) {
      this.excessCreditPlanName = Optional.ofNullable(excessCreditPlanName);
      return this;
    }
    private com.socotra.coremodel.BillingLevel billingLevel;
    public AccountBuilder billingLevel(com.socotra.coremodel.BillingLevel billingLevel) {
      this.billingLevel = billingLevel;
      return this;
    }
    private Optional<java.lang.String> invoiceDocument;
    public AccountBuilder invoiceDocument(Optional<java.lang.String> invoiceDocument) {
      this.invoiceDocument = invoiceDocument;
      return this;
    }
    public AccountBuilder invoiceDocument(java.lang.String invoiceDocument) {
      this.invoiceDocument = Optional.ofNullable(invoiceDocument);
      return this;
    }
    private Optional<byte[]> securityId;
    public AccountBuilder securityId(Optional<byte[]> securityId) {
      this.securityId = securityId;
      return this;
    }
    public AccountBuilder securityId(byte[] securityId) {
      this.securityId = Optional.ofNullable(securityId);
      return this;
    }
    private Optional<java.lang.String> region;
    public AccountBuilder region(Optional<java.lang.String> region) {
      this.region = region;
      return this;
    }
    public AccountBuilder region(java.lang.String region) {
      this.region = Optional.ofNullable(region);
      return this;
    }
    private Optional<java.lang.String> accountNumber;
    public AccountBuilder accountNumber(Optional<java.lang.String> accountNumber) {
      this.accountNumber = accountNumber;
      return this;
    }
    public AccountBuilder accountNumber(java.lang.String accountNumber) {
      this.accountNumber = Optional.ofNullable(accountNumber);
      return this;
    }
    private Collection<ContactRoles> contacts;
    public AccountBuilder contacts(Collection<ContactRoles> contacts) {
      this.contacts = contacts;
      return this;
    }
    private Optional<java.lang.String> timezone;
    public AccountBuilder timezone(Optional<java.lang.String> timezone) {
      this.timezone = timezone;
      return this;
    }
    public AccountBuilder timezone(java.lang.String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }
    private Optional<java.time.Instant> anonymizedAt;
    public AccountBuilder anonymizedAt(Optional<java.time.Instant> anonymizedAt) {
      this.anonymizedAt = anonymizedAt;
      return this;
    }
    public AccountBuilder anonymizedAt(java.time.Instant anonymizedAt) {
      this.anonymizedAt = Optional.ofNullable(anonymizedAt);
      return this;
    }
    private Optional<java.lang.String> invoicingPlanName;
    public AccountBuilder invoicingPlanName(Optional<java.lang.String> invoicingPlanName) {
      this.invoicingPlanName = invoicingPlanName;
      return this;
    }
    public AccountBuilder invoicingPlanName(java.lang.String invoicingPlanName) {
      this.invoicingPlanName = Optional.ofNullable(invoicingPlanName);
      return this;
    }
    private Optional<java.lang.String> paymentExecutionRetryPlanName;
    public AccountBuilder paymentExecutionRetryPlanName(Optional<java.lang.String> paymentExecutionRetryPlanName) {
      this.paymentExecutionRetryPlanName = paymentExecutionRetryPlanName;
      return this;
    }
    public AccountBuilder paymentExecutionRetryPlanName(java.lang.String paymentExecutionRetryPlanName) {
      this.paymentExecutionRetryPlanName = Optional.ofNullable(paymentExecutionRetryPlanName);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> configVersionLocator;
    public AccountBuilder configVersionLocator(Optional<com.socotra.platform.tools.ULID> configVersionLocator) {
      this.configVersionLocator = configVersionLocator;
      return this;
    }
    public AccountBuilder configVersionLocator(com.socotra.platform.tools.ULID configVersionLocator) {
      this.configVersionLocator = Optional.ofNullable(configVersionLocator);
      return this;
    }
    public AccountBuilder() {
      data = new HashMap<>();
      contacts = new ArrayList<>();
    }
    public Account build() {
      return new Account(
          locator,
          type,
          accountState,
          data,
          createdAt,
          createdBy,
          delinquencyPlanName,
          shortfallTolerancePlanName,
          preferences,
          autoRenewalPlanName,
          excessCreditPlanName,
          billingLevel,
          invoiceDocument,
          securityId,
          region,
          accountNumber,
          contacts,
          timezone,
          anonymizedAt,
          invoicingPlanName,
          paymentExecutionRetryPlanName,
          configVersionLocator
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public AccountBuilder addContact(ContactRoles field) {
      this.contacts = copyIfImmutable(this.contacts, c -> c.add(field));
      return this;
    }
    public AccountBuilder addContacts(Collection<ContactRoles> fields) {
      this.contacts = copyIfImmutable(this.contacts, c -> c.addAll(fields));
      return this;
    }
    public boolean hasContacts() {
      return !this.contacts.isEmpty();
    }


  }
}
