/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record AddChangeInstruction(
    Collection<Element> elements
)  implements com.socotra.coremodel.TransactionChangeInstruction
{
  public AddChangeInstruction {
    elements = elements == null ? List.of() : List.copyOf(elements);


 }

  public com.socotra.coremodel.protobuf.AddChangeInstruction toProto() {
    com.socotra.coremodel.protobuf.AddChangeInstruction.Builder builder = com.socotra.coremodel.protobuf.AddChangeInstruction.newBuilder();
    builder.addAllElements(this.elements.stream().map(f -> f.toProto()).toList());
    return builder.build();
  }

  public AddChangeInstruction toTransport() {
    return toBuilder()
        .elements(List.of())
        .build();
  }

  public static AddChangeInstruction fromProto(com.socotra.coremodel.protobuf.AddChangeInstruction proto) {
    return new AddChangeInstruction(
         proto.getElementsList().stream().map(f -> Element.fromProto(f)).toList()
    );
  }

  public static AddChangeInstructionBuilder builder() {
    return new AddChangeInstructionBuilder();
  }


  public AddChangeInstructionBuilder toBuilder() {
    return new AddChangeInstructionBuilder()
       .elements(this.elements);
  }




  public static class AddChangeInstructionBuilder {
    private Collection<Element> elements;
    public AddChangeInstructionBuilder elements(Collection<Element> elements) {
      this.elements = elements;
      return this;
    }
    public AddChangeInstructionBuilder() {
      elements = new ArrayList<>();
    }
    public AddChangeInstruction build() {
      return new AddChangeInstruction(
          elements
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public AddChangeInstructionBuilder addElement(Element field) {
      this.elements = copyIfImmutable(this.elements, c -> c.add(field));
      return this;
    }
    public AddChangeInstructionBuilder addElements(Collection<Element> fields) {
      this.elements = copyIfImmutable(this.elements, c -> c.addAll(fields));
      return this;
    }
    public boolean hasElements() {
      return !this.elements.isEmpty();
    }


  }
}
