/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record AutopayPluginRequest(
    Invoice invoice,
    java.lang.Boolean invoicingHoldActive
) 
{
  public AutopayPluginRequest {

    Objects.requireNonNull(invoice, "invoice is required but it is null");
    Objects.requireNonNull(invoicingHoldActive, "invoicingHoldActive is required but it is null");

 }

  public com.socotra.coremodel.protobuf.AutopayPluginRequest toProto() {
    com.socotra.coremodel.protobuf.AutopayPluginRequest.Builder builder = com.socotra.coremodel.protobuf.AutopayPluginRequest.newBuilder();
    if (invoice != null) {
      builder.setInvoice(invoice.toProto());
    }
    if (invoicingHoldActive != null) {
      builder.setInvoicingHoldActive(this.invoicingHoldActive);
    }
    return builder.build();
  }

  public AutopayPluginRequest toTransport() {
    return toBuilder()
        .build();
  }

  public static AutopayPluginRequest fromProto(com.socotra.coremodel.protobuf.AutopayPluginRequest proto) {
    return new AutopayPluginRequest(
         Invoice.fromProto(proto.getInvoice()),
         proto.getInvoicingHoldActive()
    );
  }

  public static AutopayPluginRequestBuilder builder() {
    return new AutopayPluginRequestBuilder();
  }


  public AutopayPluginRequestBuilder toBuilder() {
    return new AutopayPluginRequestBuilder()
       .invoice(this.invoice)
       .invoicingHoldActive(this.invoicingHoldActive);
  }




  public static class AutopayPluginRequestBuilder {
    private Invoice invoice;
    public AutopayPluginRequestBuilder invoice(Invoice invoice) {
      this.invoice = invoice;
      return this;
    }
    private java.lang.Boolean invoicingHoldActive;
    public AutopayPluginRequestBuilder invoicingHoldActive(java.lang.Boolean invoicingHoldActive) {
      this.invoicingHoldActive = invoicingHoldActive;
      return this;
    }
    public AutopayPluginRequestBuilder() {
    }
    public AutopayPluginRequest build() {
      return new AutopayPluginRequest(
          invoice,
          invoicingHoldActive
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
