/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record AutopayPluginResponse(
    Optional<PaymentCreateRequest> paymentRequest,
    Optional<java.time.Instant> nextRequestTime
) 
{
  public AutopayPluginResponse {
    paymentRequest = paymentRequest == null ? Optional.empty() : paymentRequest;
    nextRequestTime = nextRequestTime == null ? Optional.empty() : nextRequestTime;

    Objects.requireNonNull(paymentRequest, "paymentRequest is required but it is null");
    Objects.requireNonNull(nextRequestTime, "nextRequestTime is required but it is null");

 }

  public com.socotra.coremodel.protobuf.AutopayPluginResponse toProto() {
    com.socotra.coremodel.protobuf.AutopayPluginResponse.Builder builder = com.socotra.coremodel.protobuf.AutopayPluginResponse.newBuilder();
    if (paymentRequest.isPresent()) {
      builder.setPaymentRequest(paymentRequest.get().toProto());
    }
    if (nextRequestTime.isPresent()) {
      builder.setNextRequestTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(nextRequestTime.get().getEpochSecond()).setNanos(nextRequestTime.get().getNano()).build());
    }
    return builder.build();
  }

  public AutopayPluginResponse toTransport() {
    return toBuilder()
        .build();
  }

  public static AutopayPluginResponse fromProto(com.socotra.coremodel.protobuf.AutopayPluginResponse proto) {
    return new AutopayPluginResponse(
         proto.hasPaymentRequest() ? Optional.of(PaymentCreateRequest.fromProto(proto.getPaymentRequest())) : Optional.empty(),
         proto.hasNextRequestTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getNextRequestTime().getSeconds(), proto.getNextRequestTime().getNanos())) : Optional.empty()
    );
  }

  public static AutopayPluginResponseBuilder builder() {
    return new AutopayPluginResponseBuilder();
  }


  public AutopayPluginResponseBuilder toBuilder() {
    return new AutopayPluginResponseBuilder()
       .paymentRequest(this.paymentRequest)
       .nextRequestTime(this.nextRequestTime);
  }




  public static class AutopayPluginResponseBuilder {
    private Optional<PaymentCreateRequest> paymentRequest;
    public AutopayPluginResponseBuilder paymentRequest(Optional<PaymentCreateRequest> paymentRequest) {
      this.paymentRequest = paymentRequest;
      return this;
    }
    public AutopayPluginResponseBuilder paymentRequest(PaymentCreateRequest paymentRequest) {
      this.paymentRequest = Optional.ofNullable(paymentRequest);
      return this;
    }
    private Optional<java.time.Instant> nextRequestTime;
    public AutopayPluginResponseBuilder nextRequestTime(Optional<java.time.Instant> nextRequestTime) {
      this.nextRequestTime = nextRequestTime;
      return this;
    }
    public AutopayPluginResponseBuilder nextRequestTime(java.time.Instant nextRequestTime) {
      this.nextRequestTime = Optional.ofNullable(nextRequestTime);
      return this;
    }
    public AutopayPluginResponseBuilder() {
    }
    public AutopayPluginResponse build() {
      return new AutopayPluginResponse(
          paymentRequest,
          nextRequestTime
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
