/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record AuxDataSet(
    com.socotra.coremodel.UiType uiType,
    java.lang.String key,
    java.lang.String value
) 
{
  public AuxDataSet {
    uiType = uiType == null ? com.socotra.coremodel.UiType.normal : uiType;


    Objects.requireNonNull(uiType, "uiType is required but it is null");
    Objects.requireNonNull(key, "key is required but it is null");
    Objects.requireNonNull(value, "value is required but it is null");

 }

  public com.socotra.coremodel.protobuf.AuxDataSet toProto() {
    com.socotra.coremodel.protobuf.AuxDataSet.Builder builder = com.socotra.coremodel.protobuf.AuxDataSet.newBuilder();
    if (uiType != null) {
      builder.setUiType(this.uiType.name());
    }
    if (key != null) {
      builder.setKey(this.key);
    }
    if (value != null) {
      builder.setValue(this.value);
    }
    return builder.build();
  }

  public AuxDataSet toTransport() {
    return toBuilder()
        .build();
  }

  public static AuxDataSet fromProto(com.socotra.coremodel.protobuf.AuxDataSet proto) {
    return new AuxDataSet(
         proto.getUiType().isEmpty() ? null : com.socotra.coremodel.UiType.valueOf(proto.getUiType()),
         proto.getKey(),
         proto.getValue()
    );
  }

  public static AuxDataSetBuilder builder() {
    return new AuxDataSetBuilder();
  }


  public AuxDataSetBuilder toBuilder() {
    return new AuxDataSetBuilder()
       .uiType(this.uiType)
       .key(this.key)
       .value(this.value);
  }




  public static class AuxDataSetBuilder {
    private com.socotra.coremodel.UiType uiType;
    public AuxDataSetBuilder uiType(com.socotra.coremodel.UiType uiType) {
      this.uiType = uiType;
      return this;
    }
    private java.lang.String key;
    public AuxDataSetBuilder key(java.lang.String key) {
      this.key = key;
      return this;
    }
    private java.lang.String value;
    public AuxDataSetBuilder value(java.lang.String value) {
      this.value = value;
      return this;
    }
    public AuxDataSetBuilder() {
    }
    public AuxDataSet build() {
      return new AuxDataSet(
          uiType,
          key,
          value
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
