/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record AuxDataKey(
    java.lang.String key,
    com.socotra.coremodel.UiType uiType,
    Optional<java.lang.String> auxDataSettingsName
) 
{
  public AuxDataKey {
    uiType = uiType == null ? com.socotra.coremodel.UiType.normal : uiType;

    auxDataSettingsName = auxDataSettingsName == null ? Optional.empty() : auxDataSettingsName;

    Objects.requireNonNull(key, "key is required but it is null");
    Objects.requireNonNull(uiType, "uiType is required but it is null");
    Objects.requireNonNull(auxDataSettingsName, "auxDataSettingsName is required but it is null");

 }

  public com.socotra.coremodel.protobuf.AuxDataKey toProto() {
    com.socotra.coremodel.protobuf.AuxDataKey.Builder builder = com.socotra.coremodel.protobuf.AuxDataKey.newBuilder();
    if (key != null) {
      builder.setKey(this.key);
    }
    if (uiType != null) {
      builder.setUiType(this.uiType.name());
    }
    if (auxDataSettingsName.isPresent()) {
      builder.setAuxDataSettingsName(this.auxDataSettingsName.get());
    }
    return builder.build();
  }

  public AuxDataKey toTransport() {
    return toBuilder()
        .build();
  }

  public static AuxDataKey fromProto(com.socotra.coremodel.protobuf.AuxDataKey proto) {
    return new AuxDataKey(
         proto.getKey(),
         proto.getUiType().isEmpty() ? null : com.socotra.coremodel.UiType.valueOf(proto.getUiType()),
         proto.hasAuxDataSettingsName() ? Optional.of(proto.getAuxDataSettingsName()) : Optional.empty()
    );
  }

  public static AuxDataKeyBuilder builder() {
    return new AuxDataKeyBuilder();
  }


  public AuxDataKeyBuilder toBuilder() {
    return new AuxDataKeyBuilder()
       .key(this.key)
       .uiType(this.uiType)
       .auxDataSettingsName(this.auxDataSettingsName);
  }




  public static class AuxDataKeyBuilder {
    private java.lang.String key;
    public AuxDataKeyBuilder key(java.lang.String key) {
      this.key = key;
      return this;
    }
    private com.socotra.coremodel.UiType uiType;
    public AuxDataKeyBuilder uiType(com.socotra.coremodel.UiType uiType) {
      this.uiType = uiType;
      return this;
    }
    private Optional<java.lang.String> auxDataSettingsName;
    public AuxDataKeyBuilder auxDataSettingsName(Optional<java.lang.String> auxDataSettingsName) {
      this.auxDataSettingsName = auxDataSettingsName;
      return this;
    }
    public AuxDataKeyBuilder auxDataSettingsName(java.lang.String auxDataSettingsName) {
      this.auxDataSettingsName = Optional.ofNullable(auxDataSettingsName);
      return this;
    }
    public AuxDataKeyBuilder() {
    }
    public AuxDataKey build() {
      return new AuxDataKey(
          key,
          uiType,
          auxDataSettingsName
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
