/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record AuxDataKeysSet(
    java.lang.String locator,
    Collection<AuxDataKey> auxDataKeys,
    java.lang.Integer offset,
    java.lang.Integer count
) 
{
  public AuxDataKeysSet {
    auxDataKeys = auxDataKeys == null ? List.of() : List.copyOf(auxDataKeys);

    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(offset, "offset is required but it is null");
    Objects.requireNonNull(count, "count is required but it is null");

 }

  public com.socotra.coremodel.protobuf.AuxDataKeysSet toProto() {
    com.socotra.coremodel.protobuf.AuxDataKeysSet.Builder builder = com.socotra.coremodel.protobuf.AuxDataKeysSet.newBuilder();
    if (locator != null) {
      builder.setLocator(this.locator);
    }
    builder.addAllAuxDataKeys(this.auxDataKeys.stream().map(f -> f.toProto()).toList());
    if (offset != null) {
      builder.setOffset(this.offset);
    }
    if (count != null) {
      builder.setCount(this.count);
    }
    return builder.build();
  }

  public AuxDataKeysSet toTransport() {
    return toBuilder()
        .auxDataKeys(List.of())
        .build();
  }

  public static AuxDataKeysSet fromProto(com.socotra.coremodel.protobuf.AuxDataKeysSet proto) {
    return new AuxDataKeysSet(
         proto.getLocator(),
         proto.getAuxDataKeysList().stream().map(f -> AuxDataKey.fromProto(f)).toList(),
         proto.getOffset(),
         proto.getCount()
    );
  }

  public static AuxDataKeysSetBuilder builder() {
    return new AuxDataKeysSetBuilder();
  }


  public AuxDataKeysSetBuilder toBuilder() {
    return new AuxDataKeysSetBuilder()
       .locator(this.locator)
       .auxDataKeys(this.auxDataKeys)
       .offset(this.offset)
       .count(this.count);
  }




  public static class AuxDataKeysSetBuilder {
    private java.lang.String locator;
    public AuxDataKeysSetBuilder locator(java.lang.String locator) {
      this.locator = locator;
      return this;
    }
    private Collection<AuxDataKey> auxDataKeys;
    public AuxDataKeysSetBuilder auxDataKeys(Collection<AuxDataKey> auxDataKeys) {
      this.auxDataKeys = auxDataKeys;
      return this;
    }
    private java.lang.Integer offset;
    public AuxDataKeysSetBuilder offset(java.lang.Integer offset) {
      this.offset = offset;
      return this;
    }
    private java.lang.Integer count;
    public AuxDataKeysSetBuilder count(java.lang.Integer count) {
      this.count = count;
      return this;
    }
    public AuxDataKeysSetBuilder() {
      auxDataKeys = new ArrayList<>();
    }
    public AuxDataKeysSet build() {
      return new AuxDataKeysSet(
          locator,
          auxDataKeys,
          offset,
          count
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public AuxDataKeysSetBuilder addAuxDataKey(AuxDataKey field) {
      this.auxDataKeys = copyIfImmutable(this.auxDataKeys, c -> c.add(field));
      return this;
    }
    public AuxDataKeysSetBuilder addAuxDataKeys(Collection<AuxDataKey> fields) {
      this.auxDataKeys = copyIfImmutable(this.auxDataKeys, c -> c.addAll(fields));
      return this;
    }
    public boolean hasAuxDataKeys() {
      return !this.auxDataKeys.isEmpty();
    }


  }
}
