/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record BillingPreferences(
    Optional<java.lang.String> billingPlanName,
    Optional<com.socotra.coremodel.BillingLevel> billingLevel
) 
{
  public BillingPreferences {
    billingPlanName = billingPlanName == null ? Optional.empty() : billingPlanName;
    billingLevel = billingLevel == null ? Optional.empty() : billingLevel;


    Objects.requireNonNull(billingPlanName, "billingPlanName is required but it is null");
    Objects.requireNonNull(billingLevel, "billingLevel is required but it is null");

 }

  public com.socotra.coremodel.protobuf.BillingPreferences toProto() {
    com.socotra.coremodel.protobuf.BillingPreferences.Builder builder = com.socotra.coremodel.protobuf.BillingPreferences.newBuilder();
    if (billingPlanName.isPresent()) {
      builder.setBillingPlanName(this.billingPlanName.get());
    }
    if (billingLevel.isPresent()) {
      builder.setBillingLevel(this.billingLevel.get().name());
    }
    return builder.build();
  }

  public BillingPreferences toTransport() {
    return toBuilder()
        .build();
  }

  public static BillingPreferences fromProto(com.socotra.coremodel.protobuf.BillingPreferences proto) {
    return new BillingPreferences(
         proto.hasBillingPlanName() ? Optional.of(proto.getBillingPlanName()) : Optional.empty(),
         proto.hasBillingLevel() ? Optional.of(proto.getBillingLevel().isEmpty() ? null : com.socotra.coremodel.BillingLevel.valueOf(proto.getBillingLevel())) : Optional.empty()
    );
  }

  public static BillingPreferencesBuilder builder() {
    return new BillingPreferencesBuilder();
  }


  public BillingPreferencesBuilder toBuilder() {
    return new BillingPreferencesBuilder()
       .billingPlanName(this.billingPlanName)
       .billingLevel(this.billingLevel);
  }




  public static class BillingPreferencesBuilder {
    private Optional<java.lang.String> billingPlanName;
    public BillingPreferencesBuilder billingPlanName(Optional<java.lang.String> billingPlanName) {
      this.billingPlanName = billingPlanName;
      return this;
    }
    public BillingPreferencesBuilder billingPlanName(java.lang.String billingPlanName) {
      this.billingPlanName = Optional.ofNullable(billingPlanName);
      return this;
    }
    private Optional<com.socotra.coremodel.BillingLevel> billingLevel;
    public BillingPreferencesBuilder billingLevel(Optional<com.socotra.coremodel.BillingLevel> billingLevel) {
      this.billingLevel = billingLevel;
      return this;
    }
    public BillingPreferencesBuilder billingLevel(com.socotra.coremodel.BillingLevel billingLevel) {
      this.billingLevel = Optional.ofNullable(billingLevel);
      return this;
    }
    public BillingPreferencesBuilder() {
    }
    public BillingPreferences build() {
      return new BillingPreferences(
          billingPlanName,
          billingLevel
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
