/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record CancellationPluginResponse(
    RatingSet retentionCharges
) 
{
  public CancellationPluginResponse {

    Objects.requireNonNull(retentionCharges, "retentionCharges is required but it is null");

 }

  public com.socotra.coremodel.protobuf.CancellationPluginResponse toProto() {
    com.socotra.coremodel.protobuf.CancellationPluginResponse.Builder builder = com.socotra.coremodel.protobuf.CancellationPluginResponse.newBuilder();
    if (retentionCharges != null) {
      builder.setRetentionCharges(retentionCharges.toProto());
    }
    return builder.build();
  }

  public CancellationPluginResponse toTransport() {
    return toBuilder()
        .build();
  }

  public static CancellationPluginResponse fromProto(com.socotra.coremodel.protobuf.CancellationPluginResponse proto) {
    return new CancellationPluginResponse(
         RatingSet.fromProto(proto.getRetentionCharges())
    );
  }

  public static CancellationPluginResponseBuilder builder() {
    return new CancellationPluginResponseBuilder();
  }


  public CancellationPluginResponseBuilder toBuilder() {
    return new CancellationPluginResponseBuilder()
       .retentionCharges(this.retentionCharges);
  }




  public static class CancellationPluginResponseBuilder {
    private RatingSet retentionCharges;
    public CancellationPluginResponseBuilder retentionCharges(RatingSet retentionCharges) {
      this.retentionCharges = retentionCharges;
      return this;
    }
    public CancellationPluginResponseBuilder() {
    }
    public CancellationPluginResponse build() {
      return new CancellationPluginResponse(
          retentionCharges
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
