/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Charge(
    com.socotra.platform.tools.ULID locator,
    com.socotra.platform.tools.ULID elementLocator,
    java.lang.String chargeType,
    com.socotra.coremodel.ChargeCategory chargeCategory,
    java.math.BigDecimal amount,
    java.math.BigDecimal rate,
    java.math.BigDecimal referenceRate,
    Optional<java.lang.String> tag,
    Optional<java.math.BigDecimal> rateDifference,
    com.socotra.platform.tools.ULID elementStaticLocator,
    Optional<com.socotra.platform.tools.ULID> reversalOfLocator,
    com.socotra.coremodel.ChargeHandling handling,
    com.socotra.coremodel.ChargeInvoicing invoicing
) 
{
  public Charge {
    
    tag = tag == null ? Optional.empty() : tag;
    rateDifference = rateDifference == null ? Optional.empty() : rateDifference;
    reversalOfLocator = reversalOfLocator == null ? Optional.empty() : reversalOfLocator;
    handling = handling == null ? com.socotra.coremodel.ChargeHandling.normal : handling;

    invoicing = invoicing == null ? com.socotra.coremodel.ChargeInvoicing.scheduled : invoicing;

    UnaryOperator<java.math.BigDecimal> normalizer = v -> {
      java.math.BigDecimal bd = v.setScale(15, RoundingMode.HALF_EVEN).stripTrailingZeros();
      if (bd.scale() < 0) {
        bd = bd.setScale(0, RoundingMode.UNNECESSARY);
      }
      return bd;
    };

    rate = rate == null ? null : normalizer.apply(rate);
    referenceRate = referenceRate == null ? null : normalizer.apply(referenceRate);
    rateDifference = rateDifference.map(normalizer);
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(elementLocator, "elementLocator is required but it is null");
    Objects.requireNonNull(chargeType, "chargeType is required but it is null");
    Objects.requireNonNull(chargeCategory, "chargeCategory is required but it is null");
    Objects.requireNonNull(amount, "amount is required but it is null");
    Objects.requireNonNull(rate, "rate is required but it is null");
    Objects.requireNonNull(referenceRate, "referenceRate is required but it is null");
    Objects.requireNonNull(tag, "tag is required but it is null");
    Objects.requireNonNull(rateDifference, "rateDifference is required but it is null");
    Objects.requireNonNull(reversalOfLocator, "reversalOfLocator is required but it is null");
    Objects.requireNonNull(handling, "handling is required but it is null");
    Objects.requireNonNull(invoicing, "invoicing is required but it is null");

 }

  public com.socotra.coremodel.protobuf.Charge toProto() {
    com.socotra.coremodel.protobuf.Charge.Builder builder = com.socotra.coremodel.protobuf.Charge.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (elementLocator != null) {
      builder.setElementLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(elementLocator.getMostSignificantBits()).setLsb(elementLocator.getLeastSignificantBits()).build());
    }
    if (chargeType != null) {
      builder.setChargeType(this.chargeType);
    }
    if (chargeCategory != null) {
      builder.setChargeCategory(this.chargeCategory.name());
    }
    if (amount != null) {
      builder.setAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(amount.scale()).setPrecision(amount.precision()).setValue(com.google.protobuf.ByteString.copyFrom(amount.unscaledValue().toByteArray())).build());
    }
    if (rate != null) {
      builder.setRate(com.socotra.protobuf.BigDecimal.newBuilder().setScale(rate.scale()).setPrecision(rate.precision()).setValue(com.google.protobuf.ByteString.copyFrom(rate.unscaledValue().toByteArray())).build());
    }
    if (referenceRate != null) {
      builder.setReferenceRate(com.socotra.protobuf.BigDecimal.newBuilder().setScale(referenceRate.scale()).setPrecision(referenceRate.precision()).setValue(com.google.protobuf.ByteString.copyFrom(referenceRate.unscaledValue().toByteArray())).build());
    }
    if (tag.isPresent()) {
      builder.setTag(this.tag.get());
    }
    if (rateDifference.isPresent()) {
      builder.setRateDifference(com.socotra.protobuf.BigDecimal.newBuilder().setScale(rateDifference.get().scale()).setPrecision(rateDifference.get().precision()).setValue(com.google.protobuf.ByteString.copyFrom(rateDifference.get().unscaledValue().toByteArray())).build());
    }
    if (elementStaticLocator != null) {
      builder.setElementStaticLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(elementStaticLocator.getMostSignificantBits()).setLsb(elementStaticLocator.getLeastSignificantBits()).build());
    }
    if (reversalOfLocator.isPresent()) {
      builder.setReversalOfLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(reversalOfLocator.get().getMostSignificantBits()).setLsb(reversalOfLocator.get().getLeastSignificantBits()).build());
    }
    if (handling != null) {
      builder.setHandling(this.handling.name());
    }
    if (invoicing != null) {
      builder.setInvoicing(this.invoicing.name());
    }
    return builder.build();
  }

  public Charge toTransport() {
    return toBuilder()
        .build();
  }

  public static Charge fromProto(com.socotra.coremodel.protobuf.Charge proto) {
    return new Charge(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getElementLocator().getMsb(), proto.getElementLocator().getLsb()),
         proto.getChargeType(),
         proto.getChargeCategory().isEmpty() ? null : com.socotra.coremodel.ChargeCategory.valueOf(proto.getChargeCategory()),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getAmount().getValue().toByteArray()), proto.getAmount().getScale(), new java.math.MathContext(proto.getAmount().getPrecision())),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getRate().getValue().toByteArray()), proto.getRate().getScale(), new java.math.MathContext(proto.getRate().getPrecision())),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getReferenceRate().getValue().toByteArray()), proto.getReferenceRate().getScale(), new java.math.MathContext(proto.getReferenceRate().getPrecision())),
         proto.hasTag() ? Optional.of(proto.getTag()) : Optional.empty(),
         proto.hasRateDifference() ? Optional.of(new java.math.BigDecimal(new java.math.BigInteger(proto.getRateDifference().getValue().toByteArray()), proto.getRateDifference().getScale(), new java.math.MathContext(proto.getRateDifference().getPrecision()))) : Optional.empty(),
         new com.socotra.platform.tools.ULID(proto.getElementStaticLocator().getMsb(), proto.getElementStaticLocator().getLsb()),
         proto.hasReversalOfLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getReversalOfLocator().getMsb(), proto.getReversalOfLocator().getLsb())) : Optional.empty(),
         proto.getHandling().isEmpty() ? null : com.socotra.coremodel.ChargeHandling.valueOf(proto.getHandling()),
         proto.getInvoicing().isEmpty() ? null : com.socotra.coremodel.ChargeInvoicing.valueOf(proto.getInvoicing())
    );
  }

  public static ChargeBuilder builder() {
    return new ChargeBuilder();
  }


  public ChargeBuilder toBuilder() {
    return new ChargeBuilder()
       .locator(this.locator)
       .elementLocator(this.elementLocator)
       .chargeType(this.chargeType)
       .chargeCategory(this.chargeCategory)
       .amount(this.amount)
       .rate(this.rate)
       .referenceRate(this.referenceRate)
       .tag(this.tag)
       .rateDifference(this.rateDifference)
       .elementStaticLocator(this.elementStaticLocator)
       .reversalOfLocator(this.reversalOfLocator)
       .handling(this.handling)
       .invoicing(this.invoicing);
  }


  public com.socotra.platform.tools.ULID elementStaticLocator() {
    return elementStaticLocator == null ? elementLocator : elementStaticLocator;
  }

  public static class ChargeBuilder {
    private com.socotra.platform.tools.ULID locator;
    public ChargeBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.platform.tools.ULID elementLocator;
    public ChargeBuilder elementLocator(com.socotra.platform.tools.ULID elementLocator) {
      this.elementLocator = elementLocator;
      return this;
    }
    private java.lang.String chargeType;
    public ChargeBuilder chargeType(java.lang.String chargeType) {
      this.chargeType = chargeType;
      return this;
    }
    private com.socotra.coremodel.ChargeCategory chargeCategory;
    public ChargeBuilder chargeCategory(com.socotra.coremodel.ChargeCategory chargeCategory) {
      this.chargeCategory = chargeCategory;
      return this;
    }
    private java.math.BigDecimal amount;
    public ChargeBuilder amount(java.math.BigDecimal amount) {
      this.amount = amount;
      return this;
    }
    private java.math.BigDecimal rate;
    public ChargeBuilder rate(java.math.BigDecimal rate) {
      this.rate = rate;
      return this;
    }
    private java.math.BigDecimal referenceRate;
    public ChargeBuilder referenceRate(java.math.BigDecimal referenceRate) {
      this.referenceRate = referenceRate;
      return this;
    }
    private Optional<java.lang.String> tag;
    public ChargeBuilder tag(Optional<java.lang.String> tag) {
      this.tag = tag;
      return this;
    }
    public ChargeBuilder tag(java.lang.String tag) {
      this.tag = Optional.ofNullable(tag);
      return this;
    }
    private Optional<java.math.BigDecimal> rateDifference;
    public ChargeBuilder rateDifference(Optional<java.math.BigDecimal> rateDifference) {
      this.rateDifference = rateDifference;
      return this;
    }
    public ChargeBuilder rateDifference(java.math.BigDecimal rateDifference) {
      this.rateDifference = Optional.ofNullable(rateDifference);
      return this;
    }
    private com.socotra.platform.tools.ULID elementStaticLocator;
    public ChargeBuilder elementStaticLocator(com.socotra.platform.tools.ULID elementStaticLocator) {
      this.elementStaticLocator = elementStaticLocator;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> reversalOfLocator;
    public ChargeBuilder reversalOfLocator(Optional<com.socotra.platform.tools.ULID> reversalOfLocator) {
      this.reversalOfLocator = reversalOfLocator;
      return this;
    }
    public ChargeBuilder reversalOfLocator(com.socotra.platform.tools.ULID reversalOfLocator) {
      this.reversalOfLocator = Optional.ofNullable(reversalOfLocator);
      return this;
    }
    private com.socotra.coremodel.ChargeHandling handling;
    public ChargeBuilder handling(com.socotra.coremodel.ChargeHandling handling) {
      this.handling = handling;
      return this;
    }
    private com.socotra.coremodel.ChargeInvoicing invoicing;
    public ChargeBuilder invoicing(com.socotra.coremodel.ChargeInvoicing invoicing) {
      this.invoicing = invoicing;
      return this;
    }
    public ChargeBuilder() {
    }
    public Charge build() {
      return new Charge(
          locator,
          elementLocator,
          chargeType,
          chargeCategory,
          amount,
          rate,
          referenceRate,
          tag,
          rateDifference,
          elementStaticLocator,
          reversalOfLocator,
          handling,
          invoicing
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
