/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Delinquency(
    com.socotra.platform.tools.ULID locator,
    com.socotra.platform.tools.ULID accountLocator,
    com.socotra.coremodel.DelinquencyState delinquencyState,
    java.time.Instant createdAt,
    java.time.Instant updatedAt,
    DelinquencySettings settings,
    java.lang.String timezone,
    Collection<DelinquencyReference> references,
    Optional<java.time.Instant> graceStartedAt,
    Optional<java.time.Instant> graceEndAt,
    Optional<java.time.Instant> lapseTransactionEffectiveDate,
    Collection<ConfiguredDelinquencyEvent> configuredDelinquencyEvents
) 
{
  public Delinquency {
    
    graceStartedAt = graceStartedAt == null ? Optional.empty() : graceStartedAt;
    graceEndAt = graceEndAt == null ? Optional.empty() : graceEndAt;
    lapseTransactionEffectiveDate = lapseTransactionEffectiveDate == null ? Optional.empty() : lapseTransactionEffectiveDate;
    references = references == null ? List.of() : List.copyOf(references);
    configuredDelinquencyEvents = configuredDelinquencyEvents == null ? List.of() : List.copyOf(configuredDelinquencyEvents);

    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(accountLocator, "accountLocator is required but it is null");
    Objects.requireNonNull(delinquencyState, "delinquencyState is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(updatedAt, "updatedAt is required but it is null");
    Objects.requireNonNull(settings, "settings is required but it is null");
    Objects.requireNonNull(timezone, "timezone is required but it is null");
    Objects.requireNonNull(graceStartedAt, "graceStartedAt is required but it is null");
    Objects.requireNonNull(graceEndAt, "graceEndAt is required but it is null");
    Objects.requireNonNull(lapseTransactionEffectiveDate, "lapseTransactionEffectiveDate is required but it is null");

 }

  public com.socotra.coremodel.protobuf.Delinquency toProto() {
    com.socotra.coremodel.protobuf.Delinquency.Builder builder = com.socotra.coremodel.protobuf.Delinquency.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (accountLocator != null) {
      builder.setAccountLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(accountLocator.getMostSignificantBits()).setLsb(accountLocator.getLeastSignificantBits()).build());
    }
    if (delinquencyState != null) {
      builder.setDelinquencyState(this.delinquencyState.name());
    }
    if (createdAt != null) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.getEpochSecond()).setNanos(createdAt.getNano()).build());
    }
    if (updatedAt != null) {
      builder.setUpdatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(updatedAt.getEpochSecond()).setNanos(updatedAt.getNano()).build());
    }
    if (settings != null) {
      builder.setSettings(settings.toProto());
    }
    if (timezone != null) {
      builder.setTimezone(this.timezone);
    }
    builder.addAllReferences(this.references.stream().map(f -> f.toProto()).toList());
    if (graceStartedAt.isPresent()) {
      builder.setGraceStartedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(graceStartedAt.get().getEpochSecond()).setNanos(graceStartedAt.get().getNano()).build());
    }
    if (graceEndAt.isPresent()) {
      builder.setGraceEndAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(graceEndAt.get().getEpochSecond()).setNanos(graceEndAt.get().getNano()).build());
    }
    if (lapseTransactionEffectiveDate.isPresent()) {
      builder.setLapseTransactionEffectiveDate(com.google.protobuf.Timestamp.newBuilder().setSeconds(lapseTransactionEffectiveDate.get().getEpochSecond()).setNanos(lapseTransactionEffectiveDate.get().getNano()).build());
    }
    builder.addAllConfiguredDelinquencyEvents(this.configuredDelinquencyEvents.stream().map(f -> f.toProto()).toList());
    return builder.build();
  }

  public Delinquency toTransport() {
    return toBuilder()
        .references(List.of())
        .configuredDelinquencyEvents(List.of())
        .build();
  }

  public static Delinquency fromProto(com.socotra.coremodel.protobuf.Delinquency proto) {
    return new Delinquency(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getAccountLocator().getMsb(), proto.getAccountLocator().getLsb()),
         proto.getDelinquencyState().isEmpty() ? null : com.socotra.coremodel.DelinquencyState.valueOf(proto.getDelinquencyState()),
         java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos()),
         java.time.Instant.ofEpochSecond(proto.getUpdatedAt().getSeconds(), proto.getUpdatedAt().getNanos()),
         DelinquencySettings.fromProto(proto.getSettings()),
         proto.getTimezone(),
         proto.getReferencesList().stream().map(f -> DelinquencyReference.fromProto(f)).toList(),
         proto.hasGraceStartedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getGraceStartedAt().getSeconds(), proto.getGraceStartedAt().getNanos())) : Optional.empty(),
         proto.hasGraceEndAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getGraceEndAt().getSeconds(), proto.getGraceEndAt().getNanos())) : Optional.empty(),
         proto.hasLapseTransactionEffectiveDate() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getLapseTransactionEffectiveDate().getSeconds(), proto.getLapseTransactionEffectiveDate().getNanos())) : Optional.empty(),
         proto.getConfiguredDelinquencyEventsList().stream().map(f -> ConfiguredDelinquencyEvent.fromProto(f)).toList()
    );
  }

  public static DelinquencyBuilder builder() {
    return new DelinquencyBuilder();
  }


  public DelinquencyBuilder toBuilder() {
    return new DelinquencyBuilder()
       .locator(this.locator)
       .accountLocator(this.accountLocator)
       .delinquencyState(this.delinquencyState)
       .createdAt(this.createdAt)
       .updatedAt(this.updatedAt)
       .settings(this.settings)
       .timezone(this.timezone)
       .references(this.references)
       .graceStartedAt(this.graceStartedAt)
       .graceEndAt(this.graceEndAt)
       .lapseTransactionEffectiveDate(this.lapseTransactionEffectiveDate)
       .configuredDelinquencyEvents(this.configuredDelinquencyEvents);
  }




  public static class DelinquencyBuilder {
    private com.socotra.platform.tools.ULID locator;
    public DelinquencyBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.platform.tools.ULID accountLocator;
    public DelinquencyBuilder accountLocator(com.socotra.platform.tools.ULID accountLocator) {
      this.accountLocator = accountLocator;
      return this;
    }
    private com.socotra.coremodel.DelinquencyState delinquencyState;
    public DelinquencyBuilder delinquencyState(com.socotra.coremodel.DelinquencyState delinquencyState) {
      this.delinquencyState = delinquencyState;
      return this;
    }
    private java.time.Instant createdAt;
    public DelinquencyBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    private java.time.Instant updatedAt;
    public DelinquencyBuilder updatedAt(java.time.Instant updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }
    private DelinquencySettings settings;
    public DelinquencyBuilder settings(DelinquencySettings settings) {
      this.settings = settings;
      return this;
    }
    private java.lang.String timezone;
    public DelinquencyBuilder timezone(java.lang.String timezone) {
      this.timezone = timezone;
      return this;
    }
    private Collection<DelinquencyReference> references;
    public DelinquencyBuilder references(Collection<DelinquencyReference> references) {
      this.references = references;
      return this;
    }
    private Optional<java.time.Instant> graceStartedAt;
    public DelinquencyBuilder graceStartedAt(Optional<java.time.Instant> graceStartedAt) {
      this.graceStartedAt = graceStartedAt;
      return this;
    }
    public DelinquencyBuilder graceStartedAt(java.time.Instant graceStartedAt) {
      this.graceStartedAt = Optional.ofNullable(graceStartedAt);
      return this;
    }
    private Optional<java.time.Instant> graceEndAt;
    public DelinquencyBuilder graceEndAt(Optional<java.time.Instant> graceEndAt) {
      this.graceEndAt = graceEndAt;
      return this;
    }
    public DelinquencyBuilder graceEndAt(java.time.Instant graceEndAt) {
      this.graceEndAt = Optional.ofNullable(graceEndAt);
      return this;
    }
    private Optional<java.time.Instant> lapseTransactionEffectiveDate;
    public DelinquencyBuilder lapseTransactionEffectiveDate(Optional<java.time.Instant> lapseTransactionEffectiveDate) {
      this.lapseTransactionEffectiveDate = lapseTransactionEffectiveDate;
      return this;
    }
    public DelinquencyBuilder lapseTransactionEffectiveDate(java.time.Instant lapseTransactionEffectiveDate) {
      this.lapseTransactionEffectiveDate = Optional.ofNullable(lapseTransactionEffectiveDate);
      return this;
    }
    private Collection<ConfiguredDelinquencyEvent> configuredDelinquencyEvents;
    public DelinquencyBuilder configuredDelinquencyEvents(Collection<ConfiguredDelinquencyEvent> configuredDelinquencyEvents) {
      this.configuredDelinquencyEvents = configuredDelinquencyEvents;
      return this;
    }
    public DelinquencyBuilder() {
      references = new ArrayList<>();
      configuredDelinquencyEvents = new ArrayList<>();
    }
    public Delinquency build() {
      return new Delinquency(
          locator,
          accountLocator,
          delinquencyState,
          createdAt,
          updatedAt,
          settings,
          timezone,
          references,
          graceStartedAt,
          graceEndAt,
          lapseTransactionEffectiveDate,
          configuredDelinquencyEvents
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public DelinquencyBuilder addReference(DelinquencyReference field) {
      this.references = copyIfImmutable(this.references, c -> c.add(field));
      return this;
    }
    public DelinquencyBuilder addReferences(Collection<DelinquencyReference> fields) {
      this.references = copyIfImmutable(this.references, c -> c.addAll(fields));
      return this;
    }
    public boolean hasReferences() {
      return !this.references.isEmpty();
    }
    public DelinquencyBuilder addConfiguredDelinquencyEvent(ConfiguredDelinquencyEvent field) {
      this.configuredDelinquencyEvents = copyIfImmutable(this.configuredDelinquencyEvents, c -> c.add(field));
      return this;
    }
    public DelinquencyBuilder addConfiguredDelinquencyEvents(Collection<ConfiguredDelinquencyEvent> fields) {
      this.configuredDelinquencyEvents = copyIfImmutable(this.configuredDelinquencyEvents, c -> c.addAll(fields));
      return this;
    }
    public boolean hasConfiguredDelinquencyEvents() {
      return !this.configuredDelinquencyEvents.isEmpty();
    }


  }
}
