/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record DocumentDataSnapshot(
    Optional<java.lang.Object> metadata,
    java.lang.Object renderingData
) 
{
  public DocumentDataSnapshot {
    metadata = metadata == null ? Optional.empty() : metadata;
  renderingData = renderingData == null ? Map.of() : renderingData;
    Objects.requireNonNull(metadata, "metadata is required but it is null");
    Objects.requireNonNull(renderingData, "renderingData is required but it is null");

 }

  public com.socotra.coremodel.protobuf.DocumentDataSnapshot toProto() {
    com.socotra.coremodel.protobuf.DocumentDataSnapshot.Builder builder = com.socotra.coremodel.protobuf.DocumentDataSnapshot.newBuilder();
    if (metadata.isPresent()) {
      builder.setMetadata(com.socotra.protobuf.Object.newBuilder().setType(metadata.get().getClass().getName()).setData(MarshallerFactory.getFor(metadata.get().getClass()).write(metadata.get())).build());
    }
    if (renderingData != null) {
      builder.setRenderingData(com.socotra.protobuf.Object.newBuilder().setType(renderingData.getClass().getName()).setData(MarshallerFactory.getFor(renderingData.getClass()).write(renderingData)).build());
    }
    return builder.build();
  }

  public DocumentDataSnapshot toTransport() {
    return toBuilder()
        .build();
  }

  public static DocumentDataSnapshot fromProto(com.socotra.coremodel.protobuf.DocumentDataSnapshot proto) {
    return new DocumentDataSnapshot(
         proto.hasMetadata() ? Optional.of(MarshallerFactory.getFor(java.lang.Object.class).read(proto.getMetadata().getData())) : Optional.empty(),
         MarshallerFactory.getFor(java.lang.Object.class).read(proto.getRenderingData().getData())
    );
  }

  public static DocumentDataSnapshotBuilder builder() {
    return new DocumentDataSnapshotBuilder();
  }


  public DocumentDataSnapshotBuilder toBuilder() {
    return new DocumentDataSnapshotBuilder()
       .metadata(this.metadata)
       .renderingData(this.renderingData);
  }

  public <T> T metadataAs(Class<T> clazz) {
    return MarshallerFactory.getFor(metadata.getClass(), clazz).read(metadata, clazz);
  }
  public <T> T renderingDataAs(Class<T> clazz) {
    return MarshallerFactory.getFor(renderingData.getClass(), clazz).read(renderingData, clazz);
  }



  public static class DocumentDataSnapshotBuilder {
    private Optional<java.lang.Object> metadata;
    public DocumentDataSnapshotBuilder metadata(Optional<java.lang.Object> metadata) {
      this.metadata = metadata;
      return this;
    }
    public DocumentDataSnapshotBuilder metadata(java.lang.Object metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }
    private java.lang.Object renderingData;
    public DocumentDataSnapshotBuilder renderingData(java.lang.Object renderingData) {
      this.renderingData = renderingData;
      return this;
    }
    public DocumentDataSnapshotBuilder() {
    }
    public DocumentDataSnapshot build() {
      return new DocumentDataSnapshot(
          metadata,
          renderingData
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
