/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Element(
    java.util.UUID tenantLocator,
    java.lang.String type,
    com.socotra.platform.tools.ULID locator,
    com.socotra.platform.tools.ULID rootLocator,
    com.socotra.platform.tools.ULID parentLocator,
    Collection<Element> elements,
    Map<java.lang.String,java.lang.Object> coverageTerms,
    Map<java.lang.String,java.lang.Object> data,
    com.socotra.platform.tools.ULID staticLocator,
    Optional<java.time.Instant> originalEffectiveTime,
    Optional<com.socotra.coremodel.ElementCategory> category
)  implements com.socotra.coremodel.interfaces.Element<Element>
{
  public Element {
    originalEffectiveTime = originalEffectiveTime == null ? Optional.empty() : originalEffectiveTime;
    category = category == null ? Optional.empty() : category;

    elements = elements == null ? List.of() : List.copyOf(elements);
    coverageTerms = coverageTerms == null ? Map.of() : coverageTerms.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));
    data = data == null ? Map.of() : data.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));
    coverageTerms = coverageTerms.entrySet().stream()
        .collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, entry -> {
            java.lang.Object value = entry.getValue();
            return switch (value) {
                case Enum e -> e.name();
                case GenericCoverageTerms<?> gct -> gct.value();
                default -> value;
            };
        }));

 }

  public com.socotra.coremodel.protobuf.Element toProto() {
    com.socotra.coremodel.protobuf.Element.Builder builder = com.socotra.coremodel.protobuf.Element.newBuilder();
    if (tenantLocator != null) {
      builder.setTenantLocator(com.socotra.protobuf.UUID.newBuilder().setMsb(tenantLocator.getMostSignificantBits()).setLsb(tenantLocator.getLeastSignificantBits()).build());
    }
    if (type != null) {
      builder.setType(this.type);
    }
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (rootLocator != null) {
      builder.setRootLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(rootLocator.getMostSignificantBits()).setLsb(rootLocator.getLeastSignificantBits()).build());
    }
    if (parentLocator != null) {
      builder.setParentLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(parentLocator.getMostSignificantBits()).setLsb(parentLocator.getLeastSignificantBits()).build());
    }
    builder.addAllElements(this.elements.stream().map(f -> f.toProto()).toList());
    builder.putAllCoverageTerms(coverageTerms.isEmpty() ? Map.of() :coverageTerms.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> com.socotra.protobuf.Object.newBuilder().setData(MarshallerFactory.getFor(e.getValue().getClass()).write(e.getValue())).setType(e.getValue().getClass().getName()).build())));
    builder.putAllData(data.isEmpty() ? Map.of() :data.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> com.socotra.protobuf.Object.newBuilder().setData(MarshallerFactory.getFor(e.getValue().getClass()).write(e.getValue())).setType(e.getValue().getClass().getName()).build())));
    if (staticLocator != null) {
      builder.setStaticLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(staticLocator.getMostSignificantBits()).setLsb(staticLocator.getLeastSignificantBits()).build());
    }
    if (originalEffectiveTime.isPresent()) {
      builder.setOriginalEffectiveTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(originalEffectiveTime.get().getEpochSecond()).setNanos(originalEffectiveTime.get().getNano()).build());
    }
    if (category.isPresent()) {
      builder.setCategory(this.category.get().name());
    }
    return builder.build();
  }

  public Element toTransport() {
    return toBuilder()
        .elements(List.of())
        .build();
  }

  public static Element fromProto(com.socotra.coremodel.protobuf.Element proto) {
    return new Element(
         new java.util.UUID(proto.getTenantLocator().getMsb(), proto.getTenantLocator().getLsb()),
         proto.getType(),
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getRootLocator().getMsb(), proto.getRootLocator().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getParentLocator().getMsb(), proto.getParentLocator().getLsb()),
         proto.getElementsList().stream().map(f -> Element.fromProto(f)).toList(),
         proto.getCoverageTermsMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> MarshallerFactory.getFor(java.lang.Object.class).read(e.getValue().getData(), e.getValue().getType()))),
         proto.getDataMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> MarshallerFactory.getFor(java.lang.Object.class).read(e.getValue().getData(), e.getValue().getType()))),
         new com.socotra.platform.tools.ULID(proto.getStaticLocator().getMsb(), proto.getStaticLocator().getLsb()),
         proto.hasOriginalEffectiveTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getOriginalEffectiveTime().getSeconds(), proto.getOriginalEffectiveTime().getNanos())) : Optional.empty(),
         proto.hasCategory() ? Optional.of(proto.getCategory().isEmpty() ? null : com.socotra.coremodel.ElementCategory.valueOf(proto.getCategory())) : Optional.empty()
    );
  }

  public static ElementBuilder builder() {
    return new ElementBuilder();
  }

  public static Element copyFrom(com.socotra.coremodel.interfaces.Element<Element> other) {
    return new Element(
        other.tenantLocator(),
        other.type(),
        other.locator(),
        other.rootLocator(),
        other.parentLocator(),
        other.elements(),
        other.coverageTerms(),
        other.data(),
        other.staticLocator(),
        other.originalEffectiveTime(),
        other.category()
    );
  }

  public ElementBuilder toBuilder() {
    return new ElementBuilder()
       .tenantLocator(this.tenantLocator)
       .type(this.type)
       .locator(this.locator)
       .rootLocator(this.rootLocator)
       .parentLocator(this.parentLocator)
       .elements(this.elements)
       .coverageTerms(this.coverageTerms)
       .data(this.data)
       .staticLocator(this.staticLocator)
       .originalEffectiveTime(this.originalEffectiveTime)
       .category(this.category);
  }


  public com.socotra.platform.tools.ULID staticLocator() {
    return staticLocator == null ? locator : staticLocator;
  }

  public static class ElementBuilder {
    private java.util.UUID tenantLocator;
    public ElementBuilder tenantLocator(java.util.UUID tenantLocator) {
      this.tenantLocator = tenantLocator;
      return this;
    }
    private java.lang.String type;
    public ElementBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private com.socotra.platform.tools.ULID locator;
    public ElementBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.platform.tools.ULID rootLocator;
    public ElementBuilder rootLocator(com.socotra.platform.tools.ULID rootLocator) {
      this.rootLocator = rootLocator;
      return this;
    }
    private com.socotra.platform.tools.ULID parentLocator;
    public ElementBuilder parentLocator(com.socotra.platform.tools.ULID parentLocator) {
      this.parentLocator = parentLocator;
      return this;
    }
    private Collection<Element> elements;
    public ElementBuilder elements(Collection<Element> elements) {
      this.elements = elements;
      return this;
    }
    private Map<java.lang.String,java.lang.Object> coverageTerms;
    public ElementBuilder coverageTerms(Map<java.lang.String,java.lang.Object> coverageTerms) {
      this.coverageTerms = coverageTerms;
      return this;
    }
    private Map<java.lang.String,java.lang.Object> data;
    public ElementBuilder data(Map<java.lang.String,java.lang.Object> data) {
      this.data = data;
      return this;
    }
    private com.socotra.platform.tools.ULID staticLocator;
    public ElementBuilder staticLocator(com.socotra.platform.tools.ULID staticLocator) {
      this.staticLocator = staticLocator;
      return this;
    }
    private Optional<java.time.Instant> originalEffectiveTime;
    public ElementBuilder originalEffectiveTime(Optional<java.time.Instant> originalEffectiveTime) {
      this.originalEffectiveTime = originalEffectiveTime;
      return this;
    }
    public ElementBuilder originalEffectiveTime(java.time.Instant originalEffectiveTime) {
      this.originalEffectiveTime = Optional.ofNullable(originalEffectiveTime);
      return this;
    }
    private Optional<com.socotra.coremodel.ElementCategory> category;
    public ElementBuilder category(Optional<com.socotra.coremodel.ElementCategory> category) {
      this.category = category;
      return this;
    }
    public ElementBuilder category(com.socotra.coremodel.ElementCategory category) {
      this.category = Optional.ofNullable(category);
      return this;
    }
    public ElementBuilder() {
      elements = new ArrayList<>();
      coverageTerms = new HashMap<>();
      data = new HashMap<>();
    }
    public Element build() {
      return new Element(
          tenantLocator,
          type,
          locator,
          rootLocator,
          parentLocator,
          elements,
          coverageTerms,
          data,
          staticLocator,
          originalEffectiveTime,
          category
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public ElementBuilder addElement(Element field) {
      this.elements = copyIfImmutable(this.elements, c -> c.add(field));
      return this;
    }
    public ElementBuilder addElements(Collection<Element> fields) {
      this.elements = copyIfImmutable(this.elements, c -> c.addAll(fields));
      return this;
    }
    public boolean hasElements() {
      return !this.elements.isEmpty();
    }


  }
}
