/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record EventType(
    java.lang.String id
)  implements com.socotra.coremodel.interfaces.EventType
{
  public EventType {

    Objects.requireNonNull(id, "id is required but it is null");

 }

  public com.socotra.coremodel.protobuf.EventType toProto() {
    com.socotra.coremodel.protobuf.EventType.Builder builder = com.socotra.coremodel.protobuf.EventType.newBuilder();
    if (id != null) {
      builder.setId(this.id);
    }
    return builder.build();
  }

  public EventType toTransport() {
    return toBuilder()
        .build();
  }

  public static EventType fromProto(com.socotra.coremodel.protobuf.EventType proto) {
    return new EventType(
         proto.getId()
    );
  }

  public static EventTypeBuilder builder() {
    return new EventTypeBuilder();
  }

  public static EventType copyFrom(com.socotra.coremodel.interfaces.EventType other) {
    return new EventType(
        other.id()
    );
  }

  public EventTypeBuilder toBuilder() {
    return new EventTypeBuilder()
       .id(this.id);
  }




  public static class EventTypeBuilder {
    private java.lang.String id;
    public EventTypeBuilder id(java.lang.String id) {
      this.id = id;
      return this;
    }
    public EventTypeBuilder() {
    }
    public EventType build() {
      return new EventType(
          id
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
