/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record FieldSearchConfiguration(
    java.lang.String name,
    java.lang.String type,
    Optional<java.lang.Boolean> searchable,
    Optional<java.lang.Boolean> restricted
) 
{
  public FieldSearchConfiguration {
    searchable = searchable == null ? Optional.empty() : searchable;
    restricted = restricted == null ? Optional.empty() : restricted;

    Objects.requireNonNull(name, "name is required but it is null");
    Objects.requireNonNull(type, "type is required but it is null");
    Objects.requireNonNull(searchable, "searchable is required but it is null");
    Objects.requireNonNull(restricted, "restricted is required but it is null");

 }

  public com.socotra.coremodel.protobuf.FieldSearchConfiguration toProto() {
    com.socotra.coremodel.protobuf.FieldSearchConfiguration.Builder builder = com.socotra.coremodel.protobuf.FieldSearchConfiguration.newBuilder();
    if (name != null) {
      builder.setName(this.name);
    }
    if (type != null) {
      builder.setType(this.type);
    }
    if (searchable.isPresent()) {
      builder.setSearchable(this.searchable.get());
    }
    if (restricted.isPresent()) {
      builder.setRestricted(this.restricted.get());
    }
    return builder.build();
  }

  public FieldSearchConfiguration toTransport() {
    return toBuilder()
        .build();
  }

  public static FieldSearchConfiguration fromProto(com.socotra.coremodel.protobuf.FieldSearchConfiguration proto) {
    return new FieldSearchConfiguration(
         proto.getName(),
         proto.getType(),
         proto.hasSearchable() ? Optional.of(proto.getSearchable()) : Optional.empty(),
         proto.hasRestricted() ? Optional.of(proto.getRestricted()) : Optional.empty()
    );
  }

  public static FieldSearchConfigurationBuilder builder() {
    return new FieldSearchConfigurationBuilder();
  }


  public FieldSearchConfigurationBuilder toBuilder() {
    return new FieldSearchConfigurationBuilder()
       .name(this.name)
       .type(this.type)
       .searchable(this.searchable)
       .restricted(this.restricted);
  }




  public static class FieldSearchConfigurationBuilder {
    private java.lang.String name;
    public FieldSearchConfigurationBuilder name(java.lang.String name) {
      this.name = name;
      return this;
    }
    private java.lang.String type;
    public FieldSearchConfigurationBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private Optional<java.lang.Boolean> searchable;
    public FieldSearchConfigurationBuilder searchable(Optional<java.lang.Boolean> searchable) {
      this.searchable = searchable;
      return this;
    }
    public FieldSearchConfigurationBuilder searchable(java.lang.Boolean searchable) {
      this.searchable = Optional.ofNullable(searchable);
      return this;
    }
    private Optional<java.lang.Boolean> restricted;
    public FieldSearchConfigurationBuilder restricted(Optional<java.lang.Boolean> restricted) {
      this.restricted = restricted;
      return this;
    }
    public FieldSearchConfigurationBuilder restricted(java.lang.Boolean restricted) {
      this.restricted = Optional.ofNullable(restricted);
      return this;
    }
    public FieldSearchConfigurationBuilder() {
    }
    public FieldSearchConfiguration build() {
      return new FieldSearchConfiguration(
          name,
          type,
          searchable,
          restricted
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
