/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record FlatChargeSummary(
    Optional<com.socotra.platform.tools.ULID> transactionLocator,
    Optional<java.lang.String> transactionType,
    Optional<java.lang.String> transactionCategory,
    Optional<java.time.Instant> transactionEffectiveTime,
    java.math.BigDecimal amount
) 
{
  public FlatChargeSummary {
    transactionLocator = transactionLocator == null ? Optional.empty() : transactionLocator;
    transactionType = transactionType == null ? Optional.empty() : transactionType;
    transactionCategory = transactionCategory == null ? Optional.empty() : transactionCategory;
    transactionEffectiveTime = transactionEffectiveTime == null ? Optional.empty() : transactionEffectiveTime;

    Objects.requireNonNull(transactionLocator, "transactionLocator is required but it is null");
    Objects.requireNonNull(transactionType, "transactionType is required but it is null");
    Objects.requireNonNull(transactionCategory, "transactionCategory is required but it is null");
    Objects.requireNonNull(transactionEffectiveTime, "transactionEffectiveTime is required but it is null");
    Objects.requireNonNull(amount, "amount is required but it is null");

 }

  public com.socotra.coremodel.protobuf.FlatChargeSummary toProto() {
    com.socotra.coremodel.protobuf.FlatChargeSummary.Builder builder = com.socotra.coremodel.protobuf.FlatChargeSummary.newBuilder();
    if (transactionLocator.isPresent()) {
      builder.setTransactionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(transactionLocator.get().getMostSignificantBits()).setLsb(transactionLocator.get().getLeastSignificantBits()).build());
    }
    if (transactionType.isPresent()) {
      builder.setTransactionType(this.transactionType.get());
    }
    if (transactionCategory.isPresent()) {
      builder.setTransactionCategory(this.transactionCategory.get());
    }
    if (transactionEffectiveTime.isPresent()) {
      builder.setTransactionEffectiveTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(transactionEffectiveTime.get().getEpochSecond()).setNanos(transactionEffectiveTime.get().getNano()).build());
    }
    if (amount != null) {
      builder.setAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(amount.scale()).setPrecision(amount.precision()).setValue(com.google.protobuf.ByteString.copyFrom(amount.unscaledValue().toByteArray())).build());
    }
    return builder.build();
  }

  public FlatChargeSummary toTransport() {
    return toBuilder()
        .build();
  }

  public static FlatChargeSummary fromProto(com.socotra.coremodel.protobuf.FlatChargeSummary proto) {
    return new FlatChargeSummary(
         proto.hasTransactionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getTransactionLocator().getMsb(), proto.getTransactionLocator().getLsb())) : Optional.empty(),
         proto.hasTransactionType() ? Optional.of(proto.getTransactionType()) : Optional.empty(),
         proto.hasTransactionCategory() ? Optional.of(proto.getTransactionCategory()) : Optional.empty(),
         proto.hasTransactionEffectiveTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getTransactionEffectiveTime().getSeconds(), proto.getTransactionEffectiveTime().getNanos())) : Optional.empty(),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getAmount().getValue().toByteArray()), proto.getAmount().getScale(), new java.math.MathContext(proto.getAmount().getPrecision()))
    );
  }

  public static FlatChargeSummaryBuilder builder() {
    return new FlatChargeSummaryBuilder();
  }


  public FlatChargeSummaryBuilder toBuilder() {
    return new FlatChargeSummaryBuilder()
       .transactionLocator(this.transactionLocator)
       .transactionType(this.transactionType)
       .transactionCategory(this.transactionCategory)
       .transactionEffectiveTime(this.transactionEffectiveTime)
       .amount(this.amount);
  }




  public static class FlatChargeSummaryBuilder {
    private Optional<com.socotra.platform.tools.ULID> transactionLocator;
    public FlatChargeSummaryBuilder transactionLocator(Optional<com.socotra.platform.tools.ULID> transactionLocator) {
      this.transactionLocator = transactionLocator;
      return this;
    }
    public FlatChargeSummaryBuilder transactionLocator(com.socotra.platform.tools.ULID transactionLocator) {
      this.transactionLocator = Optional.ofNullable(transactionLocator);
      return this;
    }
    private Optional<java.lang.String> transactionType;
    public FlatChargeSummaryBuilder transactionType(Optional<java.lang.String> transactionType) {
      this.transactionType = transactionType;
      return this;
    }
    public FlatChargeSummaryBuilder transactionType(java.lang.String transactionType) {
      this.transactionType = Optional.ofNullable(transactionType);
      return this;
    }
    private Optional<java.lang.String> transactionCategory;
    public FlatChargeSummaryBuilder transactionCategory(Optional<java.lang.String> transactionCategory) {
      this.transactionCategory = transactionCategory;
      return this;
    }
    public FlatChargeSummaryBuilder transactionCategory(java.lang.String transactionCategory) {
      this.transactionCategory = Optional.ofNullable(transactionCategory);
      return this;
    }
    private Optional<java.time.Instant> transactionEffectiveTime;
    public FlatChargeSummaryBuilder transactionEffectiveTime(Optional<java.time.Instant> transactionEffectiveTime) {
      this.transactionEffectiveTime = transactionEffectiveTime;
      return this;
    }
    public FlatChargeSummaryBuilder transactionEffectiveTime(java.time.Instant transactionEffectiveTime) {
      this.transactionEffectiveTime = Optional.ofNullable(transactionEffectiveTime);
      return this;
    }
    private java.math.BigDecimal amount;
    public FlatChargeSummaryBuilder amount(java.math.BigDecimal amount) {
      this.amount = amount;
      return this;
    }
    public FlatChargeSummaryBuilder() {
    }
    public FlatChargeSummary build() {
      return new FlatChargeSummary(
          transactionLocator,
          transactionType,
          transactionCategory,
          transactionEffectiveTime,
          amount
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
