/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record InstallmentsPluginRequest(
    InstallmentsPluginContext context,
    Collection<Installment> installments,
    InstallmentLattice installmentLattice
) 
{
  public InstallmentsPluginRequest {
    installments = installments == null ? List.of() : List.copyOf(installments);

    Objects.requireNonNull(context, "context is required but it is null");
    Objects.requireNonNull(installmentLattice, "installmentLattice is required but it is null");

 }

  public com.socotra.coremodel.protobuf.InstallmentsPluginRequest toProto() {
    com.socotra.coremodel.protobuf.InstallmentsPluginRequest.Builder builder = com.socotra.coremodel.protobuf.InstallmentsPluginRequest.newBuilder();
    if (context != null) {
      builder.setContext(context.toProto());
    }
    builder.addAllInstallments(this.installments.stream().map(f -> f.toProto()).toList());
    if (installmentLattice != null) {
      builder.setInstallmentLattice(installmentLattice.toProto());
    }
    return builder.build();
  }

  public InstallmentsPluginRequest toTransport() {
    return toBuilder()
        .installments(List.of())
        .build();
  }

  public static InstallmentsPluginRequest fromProto(com.socotra.coremodel.protobuf.InstallmentsPluginRequest proto) {
    return new InstallmentsPluginRequest(
         InstallmentsPluginContext.fromProto(proto.getContext()),
         proto.getInstallmentsList().stream().map(f -> Installment.fromProto(f)).toList(),
         InstallmentLattice.fromProto(proto.getInstallmentLattice())
    );
  }

  public static InstallmentsPluginRequestBuilder builder() {
    return new InstallmentsPluginRequestBuilder();
  }


  public InstallmentsPluginRequestBuilder toBuilder() {
    return new InstallmentsPluginRequestBuilder()
       .context(this.context)
       .installments(this.installments)
       .installmentLattice(this.installmentLattice);
  }




  public static class InstallmentsPluginRequestBuilder {
    private InstallmentsPluginContext context;
    public InstallmentsPluginRequestBuilder context(InstallmentsPluginContext context) {
      this.context = context;
      return this;
    }
    private Collection<Installment> installments;
    public InstallmentsPluginRequestBuilder installments(Collection<Installment> installments) {
      this.installments = installments;
      return this;
    }
    private InstallmentLattice installmentLattice;
    public InstallmentsPluginRequestBuilder installmentLattice(InstallmentLattice installmentLattice) {
      this.installmentLattice = installmentLattice;
      return this;
    }
    public InstallmentsPluginRequestBuilder() {
      installments = new ArrayList<>();
    }
    public InstallmentsPluginRequest build() {
      return new InstallmentsPluginRequest(
          context,
          installments,
          installmentLattice
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public InstallmentsPluginRequestBuilder addInstallment(Installment field) {
      this.installments = copyIfImmutable(this.installments, c -> c.add(field));
      return this;
    }
    public InstallmentsPluginRequestBuilder addInstallments(Collection<Installment> fields) {
      this.installments = copyIfImmutable(this.installments, c -> c.addAll(fields));
      return this;
    }
    public boolean hasInstallments() {
      return !this.installments.isEmpty();
    }


  }
}
