/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record InstallmentLattice(
    com.socotra.platform.tools.ULID locator,
    Optional<com.socotra.platform.tools.ULID> settingsLocator,
    java.time.Instant createdAt,
    java.util.UUID createdBy,
    com.socotra.platform.tools.ULID accountLocator,
    java.time.Instant termStartTime,
    java.time.Instant termEndTime,
    Optional<com.socotra.platform.tools.ULID> termLocator,
    Optional<com.socotra.platform.tools.ULID> quoteLocator,
    Optional<com.socotra.platform.tools.ULID> policyLocator,
    java.lang.String currency,
    java.lang.String timezone,
    Optional<com.socotra.platform.tools.ULID> basedOnLocator,
    java.time.Instant effectiveTime,
    Optional<com.socotra.platform.tools.ULID> creatorTransactionLocator,
    com.socotra.coremodel.LatticeCategory latticeCategory,
    Collection<com.socotra.platform.tools.ULID> reversedLatticeLocators,
    Collection<com.socotra.platform.tools.ULID> reReversedLatticeLocators,
    Collection<InstallmentLatticeFrame> frames
)  implements com.socotra.coremodel.interfaces.InstallmentLattice
{
  public InstallmentLattice {
    settingsLocator = settingsLocator == null ? Optional.empty() : settingsLocator;
    termLocator = termLocator == null ? Optional.empty() : termLocator;
    quoteLocator = quoteLocator == null ? Optional.empty() : quoteLocator;
    policyLocator = policyLocator == null ? Optional.empty() : policyLocator;
    basedOnLocator = basedOnLocator == null ? Optional.empty() : basedOnLocator;
    creatorTransactionLocator = creatorTransactionLocator == null ? Optional.empty() : creatorTransactionLocator;
    latticeCategory = latticeCategory == null ? com.socotra.coremodel.LatticeCategory.normal : latticeCategory;

    reversedLatticeLocators = reversedLatticeLocators == null ? List.of() : List.copyOf(reversedLatticeLocators);
    reReversedLatticeLocators = reReversedLatticeLocators == null ? List.of() : List.copyOf(reReversedLatticeLocators);
    frames = frames == null ? List.of() : List.copyOf(frames);

    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(settingsLocator, "settingsLocator is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(createdBy, "createdBy is required but it is null");
    Objects.requireNonNull(accountLocator, "accountLocator is required but it is null");
    Objects.requireNonNull(termStartTime, "termStartTime is required but it is null");
    Objects.requireNonNull(termEndTime, "termEndTime is required but it is null");
    Objects.requireNonNull(termLocator, "termLocator is required but it is null");
    Objects.requireNonNull(quoteLocator, "quoteLocator is required but it is null");
    Objects.requireNonNull(policyLocator, "policyLocator is required but it is null");
    Objects.requireNonNull(currency, "currency is required but it is null");
    Objects.requireNonNull(timezone, "timezone is required but it is null");
    Objects.requireNonNull(basedOnLocator, "basedOnLocator is required but it is null");
    Objects.requireNonNull(effectiveTime, "effectiveTime is required but it is null");
    Objects.requireNonNull(creatorTransactionLocator, "creatorTransactionLocator is required but it is null");
    Objects.requireNonNull(latticeCategory, "latticeCategory is required but it is null");

 }

  public com.socotra.coremodel.protobuf.InstallmentLattice toProto() {
    com.socotra.coremodel.protobuf.InstallmentLattice.Builder builder = com.socotra.coremodel.protobuf.InstallmentLattice.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (settingsLocator.isPresent()) {
      builder.setSettingsLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(settingsLocator.get().getMostSignificantBits()).setLsb(settingsLocator.get().getLeastSignificantBits()).build());
    }
    if (createdAt != null) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.getEpochSecond()).setNanos(createdAt.getNano()).build());
    }
    if (createdBy != null) {
      builder.setCreatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(createdBy.getMostSignificantBits()).setLsb(createdBy.getLeastSignificantBits()).build());
    }
    if (accountLocator != null) {
      builder.setAccountLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(accountLocator.getMostSignificantBits()).setLsb(accountLocator.getLeastSignificantBits()).build());
    }
    if (termStartTime != null) {
      builder.setTermStartTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(termStartTime.getEpochSecond()).setNanos(termStartTime.getNano()).build());
    }
    if (termEndTime != null) {
      builder.setTermEndTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(termEndTime.getEpochSecond()).setNanos(termEndTime.getNano()).build());
    }
    if (termLocator.isPresent()) {
      builder.setTermLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(termLocator.get().getMostSignificantBits()).setLsb(termLocator.get().getLeastSignificantBits()).build());
    }
    if (quoteLocator.isPresent()) {
      builder.setQuoteLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(quoteLocator.get().getMostSignificantBits()).setLsb(quoteLocator.get().getLeastSignificantBits()).build());
    }
    if (policyLocator.isPresent()) {
      builder.setPolicyLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(policyLocator.get().getMostSignificantBits()).setLsb(policyLocator.get().getLeastSignificantBits()).build());
    }
    if (currency != null) {
      builder.setCurrency(this.currency);
    }
    if (timezone != null) {
      builder.setTimezone(this.timezone);
    }
    if (basedOnLocator.isPresent()) {
      builder.setBasedOnLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(basedOnLocator.get().getMostSignificantBits()).setLsb(basedOnLocator.get().getLeastSignificantBits()).build());
    }
    if (effectiveTime != null) {
      builder.setEffectiveTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(effectiveTime.getEpochSecond()).setNanos(effectiveTime.getNano()).build());
    }
    if (creatorTransactionLocator.isPresent()) {
      builder.setCreatorTransactionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(creatorTransactionLocator.get().getMostSignificantBits()).setLsb(creatorTransactionLocator.get().getLeastSignificantBits()).build());
    }
    if (latticeCategory != null) {
      builder.setLatticeCategory(this.latticeCategory.name());
    }
    builder.addAllReversedLatticeLocators(this.reversedLatticeLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    builder.addAllReReversedLatticeLocators(this.reReversedLatticeLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    builder.addAllFrames(this.frames.stream().map(f -> f.toProto()).toList());
    return builder.build();
  }

  public InstallmentLattice toTransport() {
    return toBuilder()
        .reversedLatticeLocators(List.of())
        .reReversedLatticeLocators(List.of())
        .frames(List.of())
        .build();
  }

  public static InstallmentLattice fromProto(com.socotra.coremodel.protobuf.InstallmentLattice proto) {
    return new InstallmentLattice(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.hasSettingsLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getSettingsLocator().getMsb(), proto.getSettingsLocator().getLsb())) : Optional.empty(),
         java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos()),
         new java.util.UUID(proto.getCreatedBy().getMsb(), proto.getCreatedBy().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getAccountLocator().getMsb(), proto.getAccountLocator().getLsb()),
         java.time.Instant.ofEpochSecond(proto.getTermStartTime().getSeconds(), proto.getTermStartTime().getNanos()),
         java.time.Instant.ofEpochSecond(proto.getTermEndTime().getSeconds(), proto.getTermEndTime().getNanos()),
         proto.hasTermLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getTermLocator().getMsb(), proto.getTermLocator().getLsb())) : Optional.empty(),
         proto.hasQuoteLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getQuoteLocator().getMsb(), proto.getQuoteLocator().getLsb())) : Optional.empty(),
         proto.hasPolicyLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getPolicyLocator().getMsb(), proto.getPolicyLocator().getLsb())) : Optional.empty(),
         proto.getCurrency(),
         proto.getTimezone(),
         proto.hasBasedOnLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getBasedOnLocator().getMsb(), proto.getBasedOnLocator().getLsb())) : Optional.empty(),
         java.time.Instant.ofEpochSecond(proto.getEffectiveTime().getSeconds(), proto.getEffectiveTime().getNanos()),
         proto.hasCreatorTransactionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getCreatorTransactionLocator().getMsb(), proto.getCreatorTransactionLocator().getLsb())) : Optional.empty(),
         proto.getLatticeCategory().isEmpty() ? null : com.socotra.coremodel.LatticeCategory.valueOf(proto.getLatticeCategory()),
         proto.getReversedLatticeLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.getReReversedLatticeLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.getFramesList().stream().map(f -> InstallmentLatticeFrame.fromProto(f)).toList()
    );
  }

  public static InstallmentLatticeBuilder builder() {
    return new InstallmentLatticeBuilder();
  }

  public static InstallmentLattice copyFrom(com.socotra.coremodel.interfaces.InstallmentLattice other) {
    return new InstallmentLattice(
        other.locator(),
        other.settingsLocator(),
        other.createdAt(),
        other.createdBy(),
        other.accountLocator(),
        other.termStartTime(),
        other.termEndTime(),
        other.termLocator(),
        other.quoteLocator(),
        other.policyLocator(),
        other.currency(),
        other.timezone(),
        other.basedOnLocator(),
        other.effectiveTime(),
        other.creatorTransactionLocator(),
        other.latticeCategory(),
        other.reversedLatticeLocators(),
        other.reReversedLatticeLocators(),
        other.frames()
    );
  }

  public InstallmentLatticeBuilder toBuilder() {
    return new InstallmentLatticeBuilder()
       .locator(this.locator)
       .settingsLocator(this.settingsLocator)
       .createdAt(this.createdAt)
       .createdBy(this.createdBy)
       .accountLocator(this.accountLocator)
       .termStartTime(this.termStartTime)
       .termEndTime(this.termEndTime)
       .termLocator(this.termLocator)
       .quoteLocator(this.quoteLocator)
       .policyLocator(this.policyLocator)
       .currency(this.currency)
       .timezone(this.timezone)
       .basedOnLocator(this.basedOnLocator)
       .effectiveTime(this.effectiveTime)
       .creatorTransactionLocator(this.creatorTransactionLocator)
       .latticeCategory(this.latticeCategory)
       .reversedLatticeLocators(this.reversedLatticeLocators)
       .reReversedLatticeLocators(this.reReversedLatticeLocators)
       .frames(this.frames);
  }


  /**
   * We mark existing lattice as `reversal` when we either create a reversal lattice or a `normal`
   * lattice is being reversed (in this case, the lattice will not contain reversedLatticeLocators
   * or reReversedLatticeLocators)
   *
   * @return true if the lattice was created because of reversal transaction, false otherwise
   */
  public boolean isReversalLattice() {
    return latticeCategory == LatticeCategory.reversal
        && (!reversedLatticeLocators.isEmpty() || !reReversedLatticeLocators.isEmpty());
  }

  public static class InstallmentLatticeBuilder {
    private com.socotra.platform.tools.ULID locator;
    public InstallmentLatticeBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> settingsLocator;
    public InstallmentLatticeBuilder settingsLocator(Optional<com.socotra.platform.tools.ULID> settingsLocator) {
      this.settingsLocator = settingsLocator;
      return this;
    }
    public InstallmentLatticeBuilder settingsLocator(com.socotra.platform.tools.ULID settingsLocator) {
      this.settingsLocator = Optional.ofNullable(settingsLocator);
      return this;
    }
    private java.time.Instant createdAt;
    public InstallmentLatticeBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    private java.util.UUID createdBy;
    public InstallmentLatticeBuilder createdBy(java.util.UUID createdBy) {
      this.createdBy = createdBy;
      return this;
    }
    private com.socotra.platform.tools.ULID accountLocator;
    public InstallmentLatticeBuilder accountLocator(com.socotra.platform.tools.ULID accountLocator) {
      this.accountLocator = accountLocator;
      return this;
    }
    private java.time.Instant termStartTime;
    public InstallmentLatticeBuilder termStartTime(java.time.Instant termStartTime) {
      this.termStartTime = termStartTime;
      return this;
    }
    private java.time.Instant termEndTime;
    public InstallmentLatticeBuilder termEndTime(java.time.Instant termEndTime) {
      this.termEndTime = termEndTime;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> termLocator;
    public InstallmentLatticeBuilder termLocator(Optional<com.socotra.platform.tools.ULID> termLocator) {
      this.termLocator = termLocator;
      return this;
    }
    public InstallmentLatticeBuilder termLocator(com.socotra.platform.tools.ULID termLocator) {
      this.termLocator = Optional.ofNullable(termLocator);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> quoteLocator;
    public InstallmentLatticeBuilder quoteLocator(Optional<com.socotra.platform.tools.ULID> quoteLocator) {
      this.quoteLocator = quoteLocator;
      return this;
    }
    public InstallmentLatticeBuilder quoteLocator(com.socotra.platform.tools.ULID quoteLocator) {
      this.quoteLocator = Optional.ofNullable(quoteLocator);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> policyLocator;
    public InstallmentLatticeBuilder policyLocator(Optional<com.socotra.platform.tools.ULID> policyLocator) {
      this.policyLocator = policyLocator;
      return this;
    }
    public InstallmentLatticeBuilder policyLocator(com.socotra.platform.tools.ULID policyLocator) {
      this.policyLocator = Optional.ofNullable(policyLocator);
      return this;
    }
    private java.lang.String currency;
    public InstallmentLatticeBuilder currency(java.lang.String currency) {
      this.currency = currency;
      return this;
    }
    private java.lang.String timezone;
    public InstallmentLatticeBuilder timezone(java.lang.String timezone) {
      this.timezone = timezone;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> basedOnLocator;
    public InstallmentLatticeBuilder basedOnLocator(Optional<com.socotra.platform.tools.ULID> basedOnLocator) {
      this.basedOnLocator = basedOnLocator;
      return this;
    }
    public InstallmentLatticeBuilder basedOnLocator(com.socotra.platform.tools.ULID basedOnLocator) {
      this.basedOnLocator = Optional.ofNullable(basedOnLocator);
      return this;
    }
    private java.time.Instant effectiveTime;
    public InstallmentLatticeBuilder effectiveTime(java.time.Instant effectiveTime) {
      this.effectiveTime = effectiveTime;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> creatorTransactionLocator;
    public InstallmentLatticeBuilder creatorTransactionLocator(Optional<com.socotra.platform.tools.ULID> creatorTransactionLocator) {
      this.creatorTransactionLocator = creatorTransactionLocator;
      return this;
    }
    public InstallmentLatticeBuilder creatorTransactionLocator(com.socotra.platform.tools.ULID creatorTransactionLocator) {
      this.creatorTransactionLocator = Optional.ofNullable(creatorTransactionLocator);
      return this;
    }
    private com.socotra.coremodel.LatticeCategory latticeCategory;
    public InstallmentLatticeBuilder latticeCategory(com.socotra.coremodel.LatticeCategory latticeCategory) {
      this.latticeCategory = latticeCategory;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> reversedLatticeLocators;
    public InstallmentLatticeBuilder reversedLatticeLocators(Collection<com.socotra.platform.tools.ULID> reversedLatticeLocators) {
      this.reversedLatticeLocators = reversedLatticeLocators;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> reReversedLatticeLocators;
    public InstallmentLatticeBuilder reReversedLatticeLocators(Collection<com.socotra.platform.tools.ULID> reReversedLatticeLocators) {
      this.reReversedLatticeLocators = reReversedLatticeLocators;
      return this;
    }
    private Collection<InstallmentLatticeFrame> frames;
    public InstallmentLatticeBuilder frames(Collection<InstallmentLatticeFrame> frames) {
      this.frames = frames;
      return this;
    }
    public InstallmentLatticeBuilder() {
      reversedLatticeLocators = new ArrayList<>();
      reReversedLatticeLocators = new ArrayList<>();
      frames = new ArrayList<>();
    }
    public InstallmentLattice build() {
      return new InstallmentLattice(
          locator,
          settingsLocator,
          createdAt,
          createdBy,
          accountLocator,
          termStartTime,
          termEndTime,
          termLocator,
          quoteLocator,
          policyLocator,
          currency,
          timezone,
          basedOnLocator,
          effectiveTime,
          creatorTransactionLocator,
          latticeCategory,
          reversedLatticeLocators,
          reReversedLatticeLocators,
          frames
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public InstallmentLatticeBuilder addReversedLatticeLocator(com.socotra.platform.tools.ULID field) {
      this.reversedLatticeLocators = copyIfImmutable(this.reversedLatticeLocators, c -> c.add(field));
      return this;
    }
    public InstallmentLatticeBuilder addReversedLatticeLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.reversedLatticeLocators = copyIfImmutable(this.reversedLatticeLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasReversedLatticeLocators() {
      return !this.reversedLatticeLocators.isEmpty();
    }
    public InstallmentLatticeBuilder addReReversedLatticeLocator(com.socotra.platform.tools.ULID field) {
      this.reReversedLatticeLocators = copyIfImmutable(this.reReversedLatticeLocators, c -> c.add(field));
      return this;
    }
    public InstallmentLatticeBuilder addReReversedLatticeLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.reReversedLatticeLocators = copyIfImmutable(this.reReversedLatticeLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasReReversedLatticeLocators() {
      return !this.reReversedLatticeLocators.isEmpty();
    }
    public InstallmentLatticeBuilder addFrame(InstallmentLatticeFrame field) {
      this.frames = copyIfImmutable(this.frames, c -> c.add(field));
      return this;
    }
    public InstallmentLatticeBuilder addFrames(Collection<InstallmentLatticeFrame> fields) {
      this.frames = copyIfImmutable(this.frames, c -> c.addAll(fields));
      return this;
    }
    public boolean hasFrames() {
      return !this.frames.isEmpty();
    }


  }
}
