/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record InvoiceDetails(
    com.socotra.platform.tools.ULID invoiceLocator,
    com.socotra.platform.tools.ULID accountLocator,
    com.socotra.coremodel.InvoiceState invoiceState,
    java.time.Instant startTime,
    java.time.Instant endTime,
    java.time.Instant generatedTime,
    java.time.Instant dueTime,
    java.lang.String currency,
    java.lang.String timezone,
    java.math.BigDecimal totalAmount,
    java.math.BigDecimal totalRemainingAmount,
    Optional<java.lang.String> invoiceNumber,
    Collection<InvoiceSummary> invoiceSummaries,
    Optional<java.time.Instant> autopayTime,
    Optional<java.time.Instant> unsettledTime,
    Optional<java.time.Instant> settledTime
) 
{
  public InvoiceDetails {
    
    invoiceNumber = invoiceNumber == null ? Optional.empty() : invoiceNumber;
    autopayTime = autopayTime == null ? Optional.empty() : autopayTime;
    unsettledTime = unsettledTime == null ? Optional.empty() : unsettledTime;
    settledTime = settledTime == null ? Optional.empty() : settledTime;
    invoiceSummaries = invoiceSummaries == null ? List.of() : List.copyOf(invoiceSummaries);

    Objects.requireNonNull(invoiceLocator, "invoiceLocator is required but it is null");
    Objects.requireNonNull(accountLocator, "accountLocator is required but it is null");
    Objects.requireNonNull(invoiceState, "invoiceState is required but it is null");
    Objects.requireNonNull(startTime, "startTime is required but it is null");
    Objects.requireNonNull(endTime, "endTime is required but it is null");
    Objects.requireNonNull(generatedTime, "generatedTime is required but it is null");
    Objects.requireNonNull(dueTime, "dueTime is required but it is null");
    Objects.requireNonNull(currency, "currency is required but it is null");
    Objects.requireNonNull(timezone, "timezone is required but it is null");
    Objects.requireNonNull(totalAmount, "totalAmount is required but it is null");
    Objects.requireNonNull(totalRemainingAmount, "totalRemainingAmount is required but it is null");
    Objects.requireNonNull(invoiceNumber, "invoiceNumber is required but it is null");
    Objects.requireNonNull(autopayTime, "autopayTime is required but it is null");
    Objects.requireNonNull(unsettledTime, "unsettledTime is required but it is null");
    Objects.requireNonNull(settledTime, "settledTime is required but it is null");

 }

  public com.socotra.coremodel.protobuf.InvoiceDetails toProto() {
    com.socotra.coremodel.protobuf.InvoiceDetails.Builder builder = com.socotra.coremodel.protobuf.InvoiceDetails.newBuilder();
    if (invoiceLocator != null) {
      builder.setInvoiceLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(invoiceLocator.getMostSignificantBits()).setLsb(invoiceLocator.getLeastSignificantBits()).build());
    }
    if (accountLocator != null) {
      builder.setAccountLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(accountLocator.getMostSignificantBits()).setLsb(accountLocator.getLeastSignificantBits()).build());
    }
    if (invoiceState != null) {
      builder.setInvoiceState(this.invoiceState.name());
    }
    if (startTime != null) {
      builder.setStartTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(startTime.getEpochSecond()).setNanos(startTime.getNano()).build());
    }
    if (endTime != null) {
      builder.setEndTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(endTime.getEpochSecond()).setNanos(endTime.getNano()).build());
    }
    if (generatedTime != null) {
      builder.setGeneratedTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(generatedTime.getEpochSecond()).setNanos(generatedTime.getNano()).build());
    }
    if (dueTime != null) {
      builder.setDueTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(dueTime.getEpochSecond()).setNanos(dueTime.getNano()).build());
    }
    if (currency != null) {
      builder.setCurrency(this.currency);
    }
    if (timezone != null) {
      builder.setTimezone(this.timezone);
    }
    if (totalAmount != null) {
      builder.setTotalAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(totalAmount.scale()).setPrecision(totalAmount.precision()).setValue(com.google.protobuf.ByteString.copyFrom(totalAmount.unscaledValue().toByteArray())).build());
    }
    if (totalRemainingAmount != null) {
      builder.setTotalRemainingAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(totalRemainingAmount.scale()).setPrecision(totalRemainingAmount.precision()).setValue(com.google.protobuf.ByteString.copyFrom(totalRemainingAmount.unscaledValue().toByteArray())).build());
    }
    if (invoiceNumber.isPresent()) {
      builder.setInvoiceNumber(this.invoiceNumber.get());
    }
    builder.addAllInvoiceSummaries(this.invoiceSummaries.stream().map(f -> f.toProto()).toList());
    if (autopayTime.isPresent()) {
      builder.setAutopayTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(autopayTime.get().getEpochSecond()).setNanos(autopayTime.get().getNano()).build());
    }
    if (unsettledTime.isPresent()) {
      builder.setUnsettledTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(unsettledTime.get().getEpochSecond()).setNanos(unsettledTime.get().getNano()).build());
    }
    if (settledTime.isPresent()) {
      builder.setSettledTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(settledTime.get().getEpochSecond()).setNanos(settledTime.get().getNano()).build());
    }
    return builder.build();
  }

  public InvoiceDetails toTransport() {
    return toBuilder()
        .invoiceSummaries(List.of())
        .build();
  }

  public static InvoiceDetails fromProto(com.socotra.coremodel.protobuf.InvoiceDetails proto) {
    return new InvoiceDetails(
         new com.socotra.platform.tools.ULID(proto.getInvoiceLocator().getMsb(), proto.getInvoiceLocator().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getAccountLocator().getMsb(), proto.getAccountLocator().getLsb()),
         proto.getInvoiceState().isEmpty() ? null : com.socotra.coremodel.InvoiceState.valueOf(proto.getInvoiceState()),
         java.time.Instant.ofEpochSecond(proto.getStartTime().getSeconds(), proto.getStartTime().getNanos()),
         java.time.Instant.ofEpochSecond(proto.getEndTime().getSeconds(), proto.getEndTime().getNanos()),
         java.time.Instant.ofEpochSecond(proto.getGeneratedTime().getSeconds(), proto.getGeneratedTime().getNanos()),
         java.time.Instant.ofEpochSecond(proto.getDueTime().getSeconds(), proto.getDueTime().getNanos()),
         proto.getCurrency(),
         proto.getTimezone(),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getTotalAmount().getValue().toByteArray()), proto.getTotalAmount().getScale(), new java.math.MathContext(proto.getTotalAmount().getPrecision())),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getTotalRemainingAmount().getValue().toByteArray()), proto.getTotalRemainingAmount().getScale(), new java.math.MathContext(proto.getTotalRemainingAmount().getPrecision())),
         proto.hasInvoiceNumber() ? Optional.of(proto.getInvoiceNumber()) : Optional.empty(),
         proto.getInvoiceSummariesList().stream().map(f -> InvoiceSummary.fromProto(f)).toList(),
         proto.hasAutopayTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAutopayTime().getSeconds(), proto.getAutopayTime().getNanos())) : Optional.empty(),
         proto.hasUnsettledTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getUnsettledTime().getSeconds(), proto.getUnsettledTime().getNanos())) : Optional.empty(),
         proto.hasSettledTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getSettledTime().getSeconds(), proto.getSettledTime().getNanos())) : Optional.empty()
    );
  }

  public static InvoiceDetailsBuilder builder() {
    return new InvoiceDetailsBuilder();
  }


  public InvoiceDetailsBuilder toBuilder() {
    return new InvoiceDetailsBuilder()
       .invoiceLocator(this.invoiceLocator)
       .accountLocator(this.accountLocator)
       .invoiceState(this.invoiceState)
       .startTime(this.startTime)
       .endTime(this.endTime)
       .generatedTime(this.generatedTime)
       .dueTime(this.dueTime)
       .currency(this.currency)
       .timezone(this.timezone)
       .totalAmount(this.totalAmount)
       .totalRemainingAmount(this.totalRemainingAmount)
       .invoiceNumber(this.invoiceNumber)
       .invoiceSummaries(this.invoiceSummaries)
       .autopayTime(this.autopayTime)
       .unsettledTime(this.unsettledTime)
       .settledTime(this.settledTime);
  }




  public static class InvoiceDetailsBuilder {
    private com.socotra.platform.tools.ULID invoiceLocator;
    public InvoiceDetailsBuilder invoiceLocator(com.socotra.platform.tools.ULID invoiceLocator) {
      this.invoiceLocator = invoiceLocator;
      return this;
    }
    private com.socotra.platform.tools.ULID accountLocator;
    public InvoiceDetailsBuilder accountLocator(com.socotra.platform.tools.ULID accountLocator) {
      this.accountLocator = accountLocator;
      return this;
    }
    private com.socotra.coremodel.InvoiceState invoiceState;
    public InvoiceDetailsBuilder invoiceState(com.socotra.coremodel.InvoiceState invoiceState) {
      this.invoiceState = invoiceState;
      return this;
    }
    private java.time.Instant startTime;
    public InvoiceDetailsBuilder startTime(java.time.Instant startTime) {
      this.startTime = startTime;
      return this;
    }
    private java.time.Instant endTime;
    public InvoiceDetailsBuilder endTime(java.time.Instant endTime) {
      this.endTime = endTime;
      return this;
    }
    private java.time.Instant generatedTime;
    public InvoiceDetailsBuilder generatedTime(java.time.Instant generatedTime) {
      this.generatedTime = generatedTime;
      return this;
    }
    private java.time.Instant dueTime;
    public InvoiceDetailsBuilder dueTime(java.time.Instant dueTime) {
      this.dueTime = dueTime;
      return this;
    }
    private java.lang.String currency;
    public InvoiceDetailsBuilder currency(java.lang.String currency) {
      this.currency = currency;
      return this;
    }
    private java.lang.String timezone;
    public InvoiceDetailsBuilder timezone(java.lang.String timezone) {
      this.timezone = timezone;
      return this;
    }
    private java.math.BigDecimal totalAmount;
    public InvoiceDetailsBuilder totalAmount(java.math.BigDecimal totalAmount) {
      this.totalAmount = totalAmount;
      return this;
    }
    private java.math.BigDecimal totalRemainingAmount;
    public InvoiceDetailsBuilder totalRemainingAmount(java.math.BigDecimal totalRemainingAmount) {
      this.totalRemainingAmount = totalRemainingAmount;
      return this;
    }
    private Optional<java.lang.String> invoiceNumber;
    public InvoiceDetailsBuilder invoiceNumber(Optional<java.lang.String> invoiceNumber) {
      this.invoiceNumber = invoiceNumber;
      return this;
    }
    public InvoiceDetailsBuilder invoiceNumber(java.lang.String invoiceNumber) {
      this.invoiceNumber = Optional.ofNullable(invoiceNumber);
      return this;
    }
    private Collection<InvoiceSummary> invoiceSummaries;
    public InvoiceDetailsBuilder invoiceSummaries(Collection<InvoiceSummary> invoiceSummaries) {
      this.invoiceSummaries = invoiceSummaries;
      return this;
    }
    private Optional<java.time.Instant> autopayTime;
    public InvoiceDetailsBuilder autopayTime(Optional<java.time.Instant> autopayTime) {
      this.autopayTime = autopayTime;
      return this;
    }
    public InvoiceDetailsBuilder autopayTime(java.time.Instant autopayTime) {
      this.autopayTime = Optional.ofNullable(autopayTime);
      return this;
    }
    private Optional<java.time.Instant> unsettledTime;
    public InvoiceDetailsBuilder unsettledTime(Optional<java.time.Instant> unsettledTime) {
      this.unsettledTime = unsettledTime;
      return this;
    }
    public InvoiceDetailsBuilder unsettledTime(java.time.Instant unsettledTime) {
      this.unsettledTime = Optional.ofNullable(unsettledTime);
      return this;
    }
    private Optional<java.time.Instant> settledTime;
    public InvoiceDetailsBuilder settledTime(Optional<java.time.Instant> settledTime) {
      this.settledTime = settledTime;
      return this;
    }
    public InvoiceDetailsBuilder settledTime(java.time.Instant settledTime) {
      this.settledTime = Optional.ofNullable(settledTime);
      return this;
    }
    public InvoiceDetailsBuilder() {
      invoiceSummaries = new ArrayList<>();
    }
    public InvoiceDetails build() {
      return new InvoiceDetails(
          invoiceLocator,
          accountLocator,
          invoiceState,
          startTime,
          endTime,
          generatedTime,
          dueTime,
          currency,
          timezone,
          totalAmount,
          totalRemainingAmount,
          invoiceNumber,
          invoiceSummaries,
          autopayTime,
          unsettledTime,
          settledTime
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public InvoiceDetailsBuilder addInvoiceSummarie(InvoiceSummary field) {
      this.invoiceSummaries = copyIfImmutable(this.invoiceSummaries, c -> c.add(field));
      return this;
    }
    public InvoiceDetailsBuilder addInvoiceSummaries(Collection<InvoiceSummary> fields) {
      this.invoiceSummaries = copyIfImmutable(this.invoiceSummaries, c -> c.addAll(fields));
      return this;
    }
    public boolean hasInvoiceSummaries() {
      return !this.invoiceSummaries.isEmpty();
    }


  }
}
