/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record InvoiceSummary(
    Optional<com.socotra.platform.tools.ULID> policyLocator,
    Optional<com.socotra.platform.tools.ULID> quoteLocator,
    Optional<java.lang.String> productName,
    Collection<InvoiceItemSummary> invoiceItemSummaries
) 
{
  public InvoiceSummary {
    policyLocator = policyLocator == null ? Optional.empty() : policyLocator;
    quoteLocator = quoteLocator == null ? Optional.empty() : quoteLocator;
    productName = productName == null ? Optional.empty() : productName;
    invoiceItemSummaries = invoiceItemSummaries == null ? List.of() : List.copyOf(invoiceItemSummaries);

    Objects.requireNonNull(policyLocator, "policyLocator is required but it is null");
    Objects.requireNonNull(quoteLocator, "quoteLocator is required but it is null");
    Objects.requireNonNull(productName, "productName is required but it is null");

 }

  public com.socotra.coremodel.protobuf.InvoiceSummary toProto() {
    com.socotra.coremodel.protobuf.InvoiceSummary.Builder builder = com.socotra.coremodel.protobuf.InvoiceSummary.newBuilder();
    if (policyLocator.isPresent()) {
      builder.setPolicyLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(policyLocator.get().getMostSignificantBits()).setLsb(policyLocator.get().getLeastSignificantBits()).build());
    }
    if (quoteLocator.isPresent()) {
      builder.setQuoteLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(quoteLocator.get().getMostSignificantBits()).setLsb(quoteLocator.get().getLeastSignificantBits()).build());
    }
    if (productName.isPresent()) {
      builder.setProductName(this.productName.get());
    }
    builder.addAllInvoiceItemSummaries(this.invoiceItemSummaries.stream().map(f -> f.toProto()).toList());
    return builder.build();
  }

  public InvoiceSummary toTransport() {
    return toBuilder()
        .invoiceItemSummaries(List.of())
        .build();
  }

  public static InvoiceSummary fromProto(com.socotra.coremodel.protobuf.InvoiceSummary proto) {
    return new InvoiceSummary(
         proto.hasPolicyLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getPolicyLocator().getMsb(), proto.getPolicyLocator().getLsb())) : Optional.empty(),
         proto.hasQuoteLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getQuoteLocator().getMsb(), proto.getQuoteLocator().getLsb())) : Optional.empty(),
         proto.hasProductName() ? Optional.of(proto.getProductName()) : Optional.empty(),
         proto.getInvoiceItemSummariesList().stream().map(f -> InvoiceItemSummary.fromProto(f)).toList()
    );
  }

  public static InvoiceSummaryBuilder builder() {
    return new InvoiceSummaryBuilder();
  }


  public InvoiceSummaryBuilder toBuilder() {
    return new InvoiceSummaryBuilder()
       .policyLocator(this.policyLocator)
       .quoteLocator(this.quoteLocator)
       .productName(this.productName)
       .invoiceItemSummaries(this.invoiceItemSummaries);
  }




  public static class InvoiceSummaryBuilder {
    private Optional<com.socotra.platform.tools.ULID> policyLocator;
    public InvoiceSummaryBuilder policyLocator(Optional<com.socotra.platform.tools.ULID> policyLocator) {
      this.policyLocator = policyLocator;
      return this;
    }
    public InvoiceSummaryBuilder policyLocator(com.socotra.platform.tools.ULID policyLocator) {
      this.policyLocator = Optional.ofNullable(policyLocator);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> quoteLocator;
    public InvoiceSummaryBuilder quoteLocator(Optional<com.socotra.platform.tools.ULID> quoteLocator) {
      this.quoteLocator = quoteLocator;
      return this;
    }
    public InvoiceSummaryBuilder quoteLocator(com.socotra.platform.tools.ULID quoteLocator) {
      this.quoteLocator = Optional.ofNullable(quoteLocator);
      return this;
    }
    private Optional<java.lang.String> productName;
    public InvoiceSummaryBuilder productName(Optional<java.lang.String> productName) {
      this.productName = productName;
      return this;
    }
    public InvoiceSummaryBuilder productName(java.lang.String productName) {
      this.productName = Optional.ofNullable(productName);
      return this;
    }
    private Collection<InvoiceItemSummary> invoiceItemSummaries;
    public InvoiceSummaryBuilder invoiceItemSummaries(Collection<InvoiceItemSummary> invoiceItemSummaries) {
      this.invoiceItemSummaries = invoiceItemSummaries;
      return this;
    }
    public InvoiceSummaryBuilder() {
      invoiceItemSummaries = new ArrayList<>();
    }
    public InvoiceSummary build() {
      return new InvoiceSummary(
          policyLocator,
          quoteLocator,
          productName,
          invoiceItemSummaries
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public InvoiceSummaryBuilder addInvoiceItemSummarie(InvoiceItemSummary field) {
      this.invoiceItemSummaries = copyIfImmutable(this.invoiceItemSummaries, c -> c.add(field));
      return this;
    }
    public InvoiceSummaryBuilder addInvoiceItemSummaries(Collection<InvoiceItemSummary> fields) {
      this.invoiceItemSummaries = copyIfImmutable(this.invoiceItemSummaries, c -> c.addAll(fields));
      return this;
    }
    public boolean hasInvoiceItemSummaries() {
      return !this.invoiceItemSummaries.isEmpty();
    }


  }
}
