/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record InvoiceItem(
    com.socotra.platform.tools.ULID locator,
    java.lang.String chargeType,
    java.lang.String chargeCategory,
    java.math.BigDecimal amount,
    Optional<java.math.BigDecimal> remainingAmount,
    Optional<java.time.Instant> settlementTime,
    com.socotra.platform.tools.ULID invoiceLocator,
    Collection<com.socotra.platform.tools.ULID> installmentItemLocators,
    java.lang.String timezone,
    Optional<com.socotra.platform.tools.ULID> quoteLocator,
    Optional<com.socotra.platform.tools.ULID> policyLocator,
    Optional<com.socotra.platform.tools.ULID> elementStaticLocator,
    Optional<java.lang.String> elementType,
    Collection<com.socotra.platform.tools.ULID> transactionLocators,
    Optional<java.time.Instant> unsettledTime
) 
{
  public InvoiceItem {
    remainingAmount = remainingAmount == null ? Optional.empty() : remainingAmount;
    settlementTime = settlementTime == null ? Optional.empty() : settlementTime;
    quoteLocator = quoteLocator == null ? Optional.empty() : quoteLocator;
    policyLocator = policyLocator == null ? Optional.empty() : policyLocator;
    elementStaticLocator = elementStaticLocator == null ? Optional.empty() : elementStaticLocator;
    elementType = elementType == null ? Optional.empty() : elementType;
    unsettledTime = unsettledTime == null ? Optional.empty() : unsettledTime;
    installmentItemLocators = installmentItemLocators == null ? List.of() : List.copyOf(installmentItemLocators);
    transactionLocators = transactionLocators == null ? List.of() : List.copyOf(transactionLocators);

    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(chargeType, "chargeType is required but it is null");
    Objects.requireNonNull(chargeCategory, "chargeCategory is required but it is null");
    Objects.requireNonNull(amount, "amount is required but it is null");
    Objects.requireNonNull(remainingAmount, "remainingAmount is required but it is null");
    Objects.requireNonNull(settlementTime, "settlementTime is required but it is null");
    Objects.requireNonNull(invoiceLocator, "invoiceLocator is required but it is null");
    Objects.requireNonNull(timezone, "timezone is required but it is null");
    Objects.requireNonNull(quoteLocator, "quoteLocator is required but it is null");
    Objects.requireNonNull(policyLocator, "policyLocator is required but it is null");
    Objects.requireNonNull(elementStaticLocator, "elementStaticLocator is required but it is null");
    Objects.requireNonNull(elementType, "elementType is required but it is null");
    Objects.requireNonNull(unsettledTime, "unsettledTime is required but it is null");

 }

  public com.socotra.coremodel.protobuf.InvoiceItem toProto() {
    com.socotra.coremodel.protobuf.InvoiceItem.Builder builder = com.socotra.coremodel.protobuf.InvoiceItem.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (chargeType != null) {
      builder.setChargeType(this.chargeType);
    }
    if (chargeCategory != null) {
      builder.setChargeCategory(this.chargeCategory);
    }
    if (amount != null) {
      builder.setAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(amount.scale()).setPrecision(amount.precision()).setValue(com.google.protobuf.ByteString.copyFrom(amount.unscaledValue().toByteArray())).build());
    }
    if (remainingAmount.isPresent()) {
      builder.setRemainingAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(remainingAmount.get().scale()).setPrecision(remainingAmount.get().precision()).setValue(com.google.protobuf.ByteString.copyFrom(remainingAmount.get().unscaledValue().toByteArray())).build());
    }
    if (settlementTime.isPresent()) {
      builder.setSettlementTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(settlementTime.get().getEpochSecond()).setNanos(settlementTime.get().getNano()).build());
    }
    if (invoiceLocator != null) {
      builder.setInvoiceLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(invoiceLocator.getMostSignificantBits()).setLsb(invoiceLocator.getLeastSignificantBits()).build());
    }
    builder.addAllInstallmentItemLocators(this.installmentItemLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    if (timezone != null) {
      builder.setTimezone(this.timezone);
    }
    if (quoteLocator.isPresent()) {
      builder.setQuoteLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(quoteLocator.get().getMostSignificantBits()).setLsb(quoteLocator.get().getLeastSignificantBits()).build());
    }
    if (policyLocator.isPresent()) {
      builder.setPolicyLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(policyLocator.get().getMostSignificantBits()).setLsb(policyLocator.get().getLeastSignificantBits()).build());
    }
    if (elementStaticLocator.isPresent()) {
      builder.setElementStaticLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(elementStaticLocator.get().getMostSignificantBits()).setLsb(elementStaticLocator.get().getLeastSignificantBits()).build());
    }
    if (elementType.isPresent()) {
      builder.setElementType(this.elementType.get());
    }
    builder.addAllTransactionLocators(this.transactionLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    if (unsettledTime.isPresent()) {
      builder.setUnsettledTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(unsettledTime.get().getEpochSecond()).setNanos(unsettledTime.get().getNano()).build());
    }
    return builder.build();
  }

  public InvoiceItem toTransport() {
    return toBuilder()
        .installmentItemLocators(List.of())
        .transactionLocators(List.of())
        .build();
  }

  public static InvoiceItem fromProto(com.socotra.coremodel.protobuf.InvoiceItem proto) {
    return new InvoiceItem(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getChargeType(),
         proto.getChargeCategory(),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getAmount().getValue().toByteArray()), proto.getAmount().getScale(), new java.math.MathContext(proto.getAmount().getPrecision())),
         proto.hasRemainingAmount() ? Optional.of(new java.math.BigDecimal(new java.math.BigInteger(proto.getRemainingAmount().getValue().toByteArray()), proto.getRemainingAmount().getScale(), new java.math.MathContext(proto.getRemainingAmount().getPrecision()))) : Optional.empty(),
         proto.hasSettlementTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getSettlementTime().getSeconds(), proto.getSettlementTime().getNanos())) : Optional.empty(),
         new com.socotra.platform.tools.ULID(proto.getInvoiceLocator().getMsb(), proto.getInvoiceLocator().getLsb()),
         proto.getInstallmentItemLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.getTimezone(),
         proto.hasQuoteLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getQuoteLocator().getMsb(), proto.getQuoteLocator().getLsb())) : Optional.empty(),
         proto.hasPolicyLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getPolicyLocator().getMsb(), proto.getPolicyLocator().getLsb())) : Optional.empty(),
         proto.hasElementStaticLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getElementStaticLocator().getMsb(), proto.getElementStaticLocator().getLsb())) : Optional.empty(),
         proto.hasElementType() ? Optional.of(proto.getElementType()) : Optional.empty(),
         proto.getTransactionLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.hasUnsettledTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getUnsettledTime().getSeconds(), proto.getUnsettledTime().getNanos())) : Optional.empty()
    );
  }

  public static InvoiceItemBuilder builder() {
    return new InvoiceItemBuilder();
  }


  public InvoiceItemBuilder toBuilder() {
    return new InvoiceItemBuilder()
       .locator(this.locator)
       .chargeType(this.chargeType)
       .chargeCategory(this.chargeCategory)
       .amount(this.amount)
       .remainingAmount(this.remainingAmount)
       .settlementTime(this.settlementTime)
       .invoiceLocator(this.invoiceLocator)
       .installmentItemLocators(this.installmentItemLocators)
       .timezone(this.timezone)
       .quoteLocator(this.quoteLocator)
       .policyLocator(this.policyLocator)
       .elementStaticLocator(this.elementStaticLocator)
       .elementType(this.elementType)
       .transactionLocators(this.transactionLocators)
       .unsettledTime(this.unsettledTime);
  }




  public static class InvoiceItemBuilder {
    private com.socotra.platform.tools.ULID locator;
    public InvoiceItemBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private java.lang.String chargeType;
    public InvoiceItemBuilder chargeType(java.lang.String chargeType) {
      this.chargeType = chargeType;
      return this;
    }
    private java.lang.String chargeCategory;
    public InvoiceItemBuilder chargeCategory(java.lang.String chargeCategory) {
      this.chargeCategory = chargeCategory;
      return this;
    }
    private java.math.BigDecimal amount;
    public InvoiceItemBuilder amount(java.math.BigDecimal amount) {
      this.amount = amount;
      return this;
    }
    private Optional<java.math.BigDecimal> remainingAmount;
    public InvoiceItemBuilder remainingAmount(Optional<java.math.BigDecimal> remainingAmount) {
      this.remainingAmount = remainingAmount;
      return this;
    }
    public InvoiceItemBuilder remainingAmount(java.math.BigDecimal remainingAmount) {
      this.remainingAmount = Optional.ofNullable(remainingAmount);
      return this;
    }
    private Optional<java.time.Instant> settlementTime;
    public InvoiceItemBuilder settlementTime(Optional<java.time.Instant> settlementTime) {
      this.settlementTime = settlementTime;
      return this;
    }
    public InvoiceItemBuilder settlementTime(java.time.Instant settlementTime) {
      this.settlementTime = Optional.ofNullable(settlementTime);
      return this;
    }
    private com.socotra.platform.tools.ULID invoiceLocator;
    public InvoiceItemBuilder invoiceLocator(com.socotra.platform.tools.ULID invoiceLocator) {
      this.invoiceLocator = invoiceLocator;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> installmentItemLocators;
    public InvoiceItemBuilder installmentItemLocators(Collection<com.socotra.platform.tools.ULID> installmentItemLocators) {
      this.installmentItemLocators = installmentItemLocators;
      return this;
    }
    private java.lang.String timezone;
    public InvoiceItemBuilder timezone(java.lang.String timezone) {
      this.timezone = timezone;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> quoteLocator;
    public InvoiceItemBuilder quoteLocator(Optional<com.socotra.platform.tools.ULID> quoteLocator) {
      this.quoteLocator = quoteLocator;
      return this;
    }
    public InvoiceItemBuilder quoteLocator(com.socotra.platform.tools.ULID quoteLocator) {
      this.quoteLocator = Optional.ofNullable(quoteLocator);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> policyLocator;
    public InvoiceItemBuilder policyLocator(Optional<com.socotra.platform.tools.ULID> policyLocator) {
      this.policyLocator = policyLocator;
      return this;
    }
    public InvoiceItemBuilder policyLocator(com.socotra.platform.tools.ULID policyLocator) {
      this.policyLocator = Optional.ofNullable(policyLocator);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> elementStaticLocator;
    public InvoiceItemBuilder elementStaticLocator(Optional<com.socotra.platform.tools.ULID> elementStaticLocator) {
      this.elementStaticLocator = elementStaticLocator;
      return this;
    }
    public InvoiceItemBuilder elementStaticLocator(com.socotra.platform.tools.ULID elementStaticLocator) {
      this.elementStaticLocator = Optional.ofNullable(elementStaticLocator);
      return this;
    }
    private Optional<java.lang.String> elementType;
    public InvoiceItemBuilder elementType(Optional<java.lang.String> elementType) {
      this.elementType = elementType;
      return this;
    }
    public InvoiceItemBuilder elementType(java.lang.String elementType) {
      this.elementType = Optional.ofNullable(elementType);
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> transactionLocators;
    public InvoiceItemBuilder transactionLocators(Collection<com.socotra.platform.tools.ULID> transactionLocators) {
      this.transactionLocators = transactionLocators;
      return this;
    }
    private Optional<java.time.Instant> unsettledTime;
    public InvoiceItemBuilder unsettledTime(Optional<java.time.Instant> unsettledTime) {
      this.unsettledTime = unsettledTime;
      return this;
    }
    public InvoiceItemBuilder unsettledTime(java.time.Instant unsettledTime) {
      this.unsettledTime = Optional.ofNullable(unsettledTime);
      return this;
    }
    public InvoiceItemBuilder() {
      installmentItemLocators = new ArrayList<>();
      transactionLocators = new ArrayList<>();
    }
    public InvoiceItem build() {
      return new InvoiceItem(
          locator,
          chargeType,
          chargeCategory,
          amount,
          remainingAmount,
          settlementTime,
          invoiceLocator,
          installmentItemLocators,
          timezone,
          quoteLocator,
          policyLocator,
          elementStaticLocator,
          elementType,
          transactionLocators,
          unsettledTime
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public InvoiceItemBuilder addInstallmentItemLocator(com.socotra.platform.tools.ULID field) {
      this.installmentItemLocators = copyIfImmutable(this.installmentItemLocators, c -> c.add(field));
      return this;
    }
    public InvoiceItemBuilder addInstallmentItemLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.installmentItemLocators = copyIfImmutable(this.installmentItemLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasInstallmentItemLocators() {
      return !this.installmentItemLocators.isEmpty();
    }
    public InvoiceItemBuilder addTransactionLocator(com.socotra.platform.tools.ULID field) {
      this.transactionLocators = copyIfImmutable(this.transactionLocators, c -> c.add(field));
      return this;
    }
    public InvoiceItemBuilder addTransactionLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.transactionLocators = copyIfImmutable(this.transactionLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasTransactionLocators() {
      return !this.transactionLocators.isEmpty();
    }


  }
}
