/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record MediaDataEntryReference(
    com.socotra.coremodel.MediaDataReferenceType type,
    com.socotra.platform.tools.ULID locator
) 
{
  public MediaDataEntryReference {
    

    Objects.requireNonNull(type, "type is required but it is null");
    Objects.requireNonNull(locator, "locator is required but it is null");

 }

  public com.socotra.coremodel.protobuf.MediaDataEntryReference toProto() {
    com.socotra.coremodel.protobuf.MediaDataEntryReference.Builder builder = com.socotra.coremodel.protobuf.MediaDataEntryReference.newBuilder();
    if (type != null) {
      builder.setType(this.type.name());
    }
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    return builder.build();
  }

  public MediaDataEntryReference toTransport() {
    return toBuilder()
        .build();
  }

  public static MediaDataEntryReference fromProto(com.socotra.coremodel.protobuf.MediaDataEntryReference proto) {
    return new MediaDataEntryReference(
         proto.getType().isEmpty() ? null : com.socotra.coremodel.MediaDataReferenceType.valueOf(proto.getType()),
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb())
    );
  }

  public static MediaDataEntryReferenceBuilder builder() {
    return new MediaDataEntryReferenceBuilder();
  }


  public MediaDataEntryReferenceBuilder toBuilder() {
    return new MediaDataEntryReferenceBuilder()
       .type(this.type)
       .locator(this.locator);
  }




  public static class MediaDataEntryReferenceBuilder {
    private com.socotra.coremodel.MediaDataReferenceType type;
    public MediaDataEntryReferenceBuilder type(com.socotra.coremodel.MediaDataReferenceType type) {
      this.type = type;
      return this;
    }
    private com.socotra.platform.tools.ULID locator;
    public MediaDataEntryReferenceBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    public MediaDataEntryReferenceBuilder() {
    }
    public MediaDataEntryReference build() {
      return new MediaDataEntryReference(
          type,
          locator
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
