/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record MoratoriumsResponse(
    Map<java.lang.String,MoratoriumConfigForReporting> moratoriums
) 
{
  public MoratoriumsResponse {
    moratoriums = moratoriums == null ? Map.of() : moratoriums.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));


 }

  public com.socotra.coremodel.protobuf.MoratoriumsResponse toProto() {
    com.socotra.coremodel.protobuf.MoratoriumsResponse.Builder builder = com.socotra.coremodel.protobuf.MoratoriumsResponse.newBuilder();
    builder.putAllMoratoriums(moratoriums.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().toProto())));
    return builder.build();
  }

  public MoratoriumsResponse toTransport() {
    return toBuilder()
        .build();
  }

  public static MoratoriumsResponse fromProto(com.socotra.coremodel.protobuf.MoratoriumsResponse proto) {
    return new MoratoriumsResponse(
         proto.getMoratoriumsMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> MoratoriumConfigForReporting.fromProto(e.getValue())))
    );
  }

  public static MoratoriumsResponseBuilder builder() {
    return new MoratoriumsResponseBuilder();
  }


  public MoratoriumsResponseBuilder toBuilder() {
    return new MoratoriumsResponseBuilder()
       .moratoriums(this.moratoriums);
  }




  public static class MoratoriumsResponseBuilder {
    private Map<java.lang.String,MoratoriumConfigForReporting> moratoriums;
    public MoratoriumsResponseBuilder moratoriums(Map<java.lang.String,MoratoriumConfigForReporting> moratoriums) {
      this.moratoriums = moratoriums;
      return this;
    }
    public MoratoriumsResponseBuilder() {
      moratoriums = new HashMap<>();
    }
    public MoratoriumsResponse build() {
      return new MoratoriumsResponse(
          moratoriums
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
