/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record ParamsChangeInstruction(
    java.time.Instant effectiveTime,
    Optional<java.time.Instant> newPolicyEndTime,
    Optional<Preferences> preferences,
    Optional<java.lang.Boolean> triggerBillingChange,
    @Deprecated Optional<java.lang.Boolean> inheritSettings
)  implements com.socotra.coremodel.TransactionChangeInstruction
{
  public ParamsChangeInstruction {
    newPolicyEndTime = newPolicyEndTime == null ? Optional.empty() : newPolicyEndTime;
    preferences = preferences == null ? Optional.empty() : preferences;
    triggerBillingChange = triggerBillingChange == null ? Optional.empty() : triggerBillingChange;
    inheritSettings = inheritSettings == null ? Optional.empty() : inheritSettings;

    Objects.requireNonNull(newPolicyEndTime, "newPolicyEndTime is required but it is null");
    Objects.requireNonNull(preferences, "preferences is required but it is null");
    Objects.requireNonNull(triggerBillingChange, "triggerBillingChange is required but it is null");
    Objects.requireNonNull(inheritSettings, "inheritSettings is required but it is null");

 }

  public com.socotra.coremodel.protobuf.ParamsChangeInstruction toProto() {
    com.socotra.coremodel.protobuf.ParamsChangeInstruction.Builder builder = com.socotra.coremodel.protobuf.ParamsChangeInstruction.newBuilder();
    if (effectiveTime != null) {
      builder.setEffectiveTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(effectiveTime.getEpochSecond()).setNanos(effectiveTime.getNano()).build());
    }
    if (newPolicyEndTime.isPresent()) {
      builder.setNewPolicyEndTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(newPolicyEndTime.get().getEpochSecond()).setNanos(newPolicyEndTime.get().getNano()).build());
    }
    if (preferences.isPresent()) {
      builder.setPreferences(preferences.get().toProto());
    }
    if (triggerBillingChange.isPresent()) {
      builder.setTriggerBillingChange(this.triggerBillingChange.get());
    }
    if (inheritSettings.isPresent()) {
      builder.setInheritSettings(this.inheritSettings.get());
    }
    return builder.build();
  }

  public ParamsChangeInstruction toTransport() {
    return toBuilder()
        .build();
  }

  public static ParamsChangeInstruction fromProto(com.socotra.coremodel.protobuf.ParamsChangeInstruction proto) {
    return new ParamsChangeInstruction(
         java.time.Instant.ofEpochSecond(proto.getEffectiveTime().getSeconds(), proto.getEffectiveTime().getNanos()),
         proto.hasNewPolicyEndTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getNewPolicyEndTime().getSeconds(), proto.getNewPolicyEndTime().getNanos())) : Optional.empty(),
         proto.hasPreferences() ? Optional.of(Preferences.fromProto(proto.getPreferences())) : Optional.empty(),
         proto.hasTriggerBillingChange() ? Optional.of(proto.getTriggerBillingChange()) : Optional.empty(),
         proto.hasInheritSettings() ? Optional.of(proto.getInheritSettings()) : Optional.empty()
    );
  }

  public static ParamsChangeInstructionBuilder builder() {
    return new ParamsChangeInstructionBuilder();
  }


  public ParamsChangeInstructionBuilder toBuilder() {
    return new ParamsChangeInstructionBuilder()
       .effectiveTime(this.effectiveTime)
       .newPolicyEndTime(this.newPolicyEndTime)
       .preferences(this.preferences)
       .triggerBillingChange(this.triggerBillingChange)
       .inheritSettings(this.inheritSettings);
  }




  public static class ParamsChangeInstructionBuilder {
    private java.time.Instant effectiveTime;
    public ParamsChangeInstructionBuilder effectiveTime(java.time.Instant effectiveTime) {
      this.effectiveTime = effectiveTime;
      return this;
    }
    private Optional<java.time.Instant> newPolicyEndTime;
    public ParamsChangeInstructionBuilder newPolicyEndTime(Optional<java.time.Instant> newPolicyEndTime) {
      this.newPolicyEndTime = newPolicyEndTime;
      return this;
    }
    public ParamsChangeInstructionBuilder newPolicyEndTime(java.time.Instant newPolicyEndTime) {
      this.newPolicyEndTime = Optional.ofNullable(newPolicyEndTime);
      return this;
    }
    private Optional<Preferences> preferences;
    public ParamsChangeInstructionBuilder preferences(Optional<Preferences> preferences) {
      this.preferences = preferences;
      return this;
    }
    public ParamsChangeInstructionBuilder preferences(Preferences preferences) {
      this.preferences = Optional.ofNullable(preferences);
      return this;
    }
    private Optional<java.lang.Boolean> triggerBillingChange;
    public ParamsChangeInstructionBuilder triggerBillingChange(Optional<java.lang.Boolean> triggerBillingChange) {
      this.triggerBillingChange = triggerBillingChange;
      return this;
    }
    public ParamsChangeInstructionBuilder triggerBillingChange(java.lang.Boolean triggerBillingChange) {
      this.triggerBillingChange = Optional.ofNullable(triggerBillingChange);
      return this;
    }
    private @Deprecated Optional<java.lang.Boolean> inheritSettings;
    public ParamsChangeInstructionBuilder inheritSettings(@Deprecated Optional<java.lang.Boolean> inheritSettings) {
      this.inheritSettings = inheritSettings;
      return this;
    }
    public ParamsChangeInstructionBuilder inheritSettings(java.lang.Boolean inheritSettings) {
      this.inheritSettings = Optional.ofNullable(inheritSettings);
      return this;
    }
    public ParamsChangeInstructionBuilder() {
    }
    public ParamsChangeInstruction build() {
      return new ParamsChangeInstruction(
          effectiveTime,
          newPolicyEndTime,
          preferences,
          triggerBillingChange,
          inheritSettings
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
