/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record PaymentPostProcessingResponse(
    Optional<java.time.Instant> nextRequestTime,
    Optional<java.lang.String> note,
    Optional<java.math.BigDecimal> amount,
    Optional<com.socotra.coremodel.PaymentState> paymentState
) 
{
  public PaymentPostProcessingResponse {
    nextRequestTime = nextRequestTime == null ? Optional.empty() : nextRequestTime;
    note = note == null ? Optional.empty() : note;
    amount = amount == null ? Optional.empty() : amount;
    paymentState = paymentState == null ? Optional.empty() : paymentState;

    if (paymentState.isPresent() && (paymentState.get() == PaymentState.executing || paymentState.get() == PaymentState.reversed)) {
      throw new IllegalArgumentException("cannot update payment state to %s when it is executing".formatted(paymentState.get()));
    }
    Objects.requireNonNull(nextRequestTime, "nextRequestTime is required but it is null");
    Objects.requireNonNull(note, "note is required but it is null");
    Objects.requireNonNull(amount, "amount is required but it is null");
    Objects.requireNonNull(paymentState, "paymentState is required but it is null");

 }

  public com.socotra.coremodel.protobuf.PaymentPostProcessingResponse toProto() {
    com.socotra.coremodel.protobuf.PaymentPostProcessingResponse.Builder builder = com.socotra.coremodel.protobuf.PaymentPostProcessingResponse.newBuilder();
    if (nextRequestTime.isPresent()) {
      builder.setNextRequestTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(nextRequestTime.get().getEpochSecond()).setNanos(nextRequestTime.get().getNano()).build());
    }
    if (note.isPresent()) {
      builder.setNote(this.note.get());
    }
    if (amount.isPresent()) {
      builder.setAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(amount.get().scale()).setPrecision(amount.get().precision()).setValue(com.google.protobuf.ByteString.copyFrom(amount.get().unscaledValue().toByteArray())).build());
    }
    if (paymentState.isPresent()) {
      builder.setPaymentState(this.paymentState.get().name());
    }
    return builder.build();
  }

  public PaymentPostProcessingResponse toTransport() {
    return toBuilder()
        .build();
  }

  public static PaymentPostProcessingResponse fromProto(com.socotra.coremodel.protobuf.PaymentPostProcessingResponse proto) {
    return new PaymentPostProcessingResponse(
         proto.hasNextRequestTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getNextRequestTime().getSeconds(), proto.getNextRequestTime().getNanos())) : Optional.empty(),
         proto.hasNote() ? Optional.of(proto.getNote()) : Optional.empty(),
         proto.hasAmount() ? Optional.of(new java.math.BigDecimal(new java.math.BigInteger(proto.getAmount().getValue().toByteArray()), proto.getAmount().getScale(), new java.math.MathContext(proto.getAmount().getPrecision()))) : Optional.empty(),
         proto.hasPaymentState() ? Optional.of(proto.getPaymentState().isEmpty() ? null : com.socotra.coremodel.PaymentState.valueOf(proto.getPaymentState())) : Optional.empty()
    );
  }

  public static PaymentPostProcessingResponseBuilder builder() {
    return new PaymentPostProcessingResponseBuilder();
  }


  public PaymentPostProcessingResponseBuilder toBuilder() {
    return new PaymentPostProcessingResponseBuilder()
       .nextRequestTime(this.nextRequestTime)
       .note(this.note)
       .amount(this.amount)
       .paymentState(this.paymentState);
  }




  public static class PaymentPostProcessingResponseBuilder {
    private Optional<java.time.Instant> nextRequestTime;
    public PaymentPostProcessingResponseBuilder nextRequestTime(Optional<java.time.Instant> nextRequestTime) {
      this.nextRequestTime = nextRequestTime;
      return this;
    }
    public PaymentPostProcessingResponseBuilder nextRequestTime(java.time.Instant nextRequestTime) {
      this.nextRequestTime = Optional.ofNullable(nextRequestTime);
      return this;
    }
    private Optional<java.lang.String> note;
    public PaymentPostProcessingResponseBuilder note(Optional<java.lang.String> note) {
      this.note = note;
      return this;
    }
    public PaymentPostProcessingResponseBuilder note(java.lang.String note) {
      this.note = Optional.ofNullable(note);
      return this;
    }
    private Optional<java.math.BigDecimal> amount;
    public PaymentPostProcessingResponseBuilder amount(Optional<java.math.BigDecimal> amount) {
      this.amount = amount;
      return this;
    }
    public PaymentPostProcessingResponseBuilder amount(java.math.BigDecimal amount) {
      this.amount = Optional.ofNullable(amount);
      return this;
    }
    private Optional<com.socotra.coremodel.PaymentState> paymentState;
    public PaymentPostProcessingResponseBuilder paymentState(Optional<com.socotra.coremodel.PaymentState> paymentState) {
      this.paymentState = paymentState;
      return this;
    }
    public PaymentPostProcessingResponseBuilder paymentState(com.socotra.coremodel.PaymentState paymentState) {
      this.paymentState = Optional.ofNullable(paymentState);
      return this;
    }
    public PaymentPostProcessingResponseBuilder() {
    }
    public PaymentPostProcessingResponse build() {
      return new PaymentPostProcessingResponse(
          nextRequestTime,
          note,
          amount,
          paymentState
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
