/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record PaymentObject(
    java.lang.String type,
    com.socotra.platform.tools.ULID locator,
    com.socotra.coremodel.PaymentState paymentState,
    java.math.BigDecimal amount,
    java.lang.String currency,
    Collection<CreditItem> targets,
    Optional<com.socotra.platform.tools.ULID> accountLocator,
    Map<java.lang.String,java.lang.Object> data,
    Optional<com.socotra.platform.tools.ULID> externalCashTransactionLocator,
    Optional<com.socotra.coremodel.PaymentMode> paymentMode,
    Optional<com.socotra.platform.tools.ULID> aggregatePaymentLocator,
    Collection<Subpayment> subpayments,
    Optional<java.time.Instant> anonymizedAt,
    Optional<java.time.Instant> autopayTime,
    Optional<java.time.Instant> nextRequestTime,
    Collection<PaymentRequestExecution> paymentExecutionHistory,
    Optional<java.lang.String> retryPlanName
)  implements com.socotra.coremodel.interfaces.Payment<Map<String, java.lang.Object>>,com.socotra.coremodel.CustomerDataHolder
{
  public PaymentObject {
    
    accountLocator = accountLocator == null ? Optional.empty() : accountLocator;
    externalCashTransactionLocator = externalCashTransactionLocator == null ? Optional.empty() : externalCashTransactionLocator;
    paymentMode = paymentMode == null ? Optional.empty() : paymentMode;

    aggregatePaymentLocator = aggregatePaymentLocator == null ? Optional.empty() : aggregatePaymentLocator;
    anonymizedAt = anonymizedAt == null ? Optional.empty() : anonymizedAt;
    autopayTime = autopayTime == null ? Optional.empty() : autopayTime;
    nextRequestTime = nextRequestTime == null ? Optional.empty() : nextRequestTime;
    retryPlanName = retryPlanName == null ? Optional.empty() : retryPlanName;
    targets = targets == null ? List.of() : List.copyOf(targets);
    data = data == null ? Map.of() : data.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));
    subpayments = subpayments == null ? List.of() : List.copyOf(subpayments);
    paymentExecutionHistory = paymentExecutionHistory == null ? List.of() : List.copyOf(paymentExecutionHistory);

    Objects.requireNonNull(type, "type is required but it is null");
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(paymentState, "paymentState is required but it is null");
    Objects.requireNonNull(amount, "amount is required but it is null");
    Objects.requireNonNull(currency, "currency is required but it is null");
    Objects.requireNonNull(accountLocator, "accountLocator is required but it is null");
    Objects.requireNonNull(externalCashTransactionLocator, "externalCashTransactionLocator is required but it is null");
    Objects.requireNonNull(paymentMode, "paymentMode is required but it is null");
    Objects.requireNonNull(aggregatePaymentLocator, "aggregatePaymentLocator is required but it is null");
    Objects.requireNonNull(anonymizedAt, "anonymizedAt is required but it is null");
    Objects.requireNonNull(autopayTime, "autopayTime is required but it is null");
    Objects.requireNonNull(nextRequestTime, "nextRequestTime is required but it is null");
    Objects.requireNonNull(retryPlanName, "retryPlanName is required but it is null");

 }

  public com.socotra.coremodel.protobuf.PaymentObject toProto() {
    com.socotra.coremodel.protobuf.PaymentObject.Builder builder = com.socotra.coremodel.protobuf.PaymentObject.newBuilder();
    if (type != null) {
      builder.setType(this.type);
    }
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (paymentState != null) {
      builder.setPaymentState(this.paymentState.name());
    }
    if (amount != null) {
      builder.setAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(amount.scale()).setPrecision(amount.precision()).setValue(com.google.protobuf.ByteString.copyFrom(amount.unscaledValue().toByteArray())).build());
    }
    if (currency != null) {
      builder.setCurrency(this.currency);
    }
    builder.addAllTargets(this.targets.stream().map(f -> f.toProto()).toList());
    if (accountLocator.isPresent()) {
      builder.setAccountLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(accountLocator.get().getMostSignificantBits()).setLsb(accountLocator.get().getLeastSignificantBits()).build());
    }
    builder.putAllData(data.isEmpty() ? Map.of() :data.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> com.socotra.protobuf.Object.newBuilder().setData(MarshallerFactory.getFor(e.getValue().getClass()).write(e.getValue())).setType(e.getValue().getClass().getName()).build())));
    if (externalCashTransactionLocator.isPresent()) {
      builder.setExternalCashTransactionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(externalCashTransactionLocator.get().getMostSignificantBits()).setLsb(externalCashTransactionLocator.get().getLeastSignificantBits()).build());
    }
    if (paymentMode.isPresent()) {
      builder.setPaymentMode(this.paymentMode.get().name());
    }
    if (aggregatePaymentLocator.isPresent()) {
      builder.setAggregatePaymentLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(aggregatePaymentLocator.get().getMostSignificantBits()).setLsb(aggregatePaymentLocator.get().getLeastSignificantBits()).build());
    }
    builder.addAllSubpayments(this.subpayments.stream().map(f -> f.toProto()).toList());
    if (anonymizedAt.isPresent()) {
      builder.setAnonymizedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(anonymizedAt.get().getEpochSecond()).setNanos(anonymizedAt.get().getNano()).build());
    }
    if (autopayTime.isPresent()) {
      builder.setAutopayTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(autopayTime.get().getEpochSecond()).setNanos(autopayTime.get().getNano()).build());
    }
    if (nextRequestTime.isPresent()) {
      builder.setNextRequestTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(nextRequestTime.get().getEpochSecond()).setNanos(nextRequestTime.get().getNano()).build());
    }
    builder.addAllPaymentExecutionHistory(this.paymentExecutionHistory.stream().map(f -> f.toProto()).toList());
    if (retryPlanName.isPresent()) {
      builder.setRetryPlanName(this.retryPlanName.get());
    }
    return builder.build();
  }

  public PaymentObject toTransport() {
    return toBuilder()
        .targets(List.of())
        .subpayments(List.of())
        .paymentExecutionHistory(List.of())
        .build();
  }

  public static PaymentObject fromProto(com.socotra.coremodel.protobuf.PaymentObject proto) {
    return new PaymentObject(
         proto.getType(),
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getPaymentState().isEmpty() ? null : com.socotra.coremodel.PaymentState.valueOf(proto.getPaymentState()),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getAmount().getValue().toByteArray()), proto.getAmount().getScale(), new java.math.MathContext(proto.getAmount().getPrecision())),
         proto.getCurrency(),
         proto.getTargetsList().stream().map(f -> CreditItem.fromProto(f)).toList(),
         proto.hasAccountLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getAccountLocator().getMsb(), proto.getAccountLocator().getLsb())) : Optional.empty(),
         proto.getDataMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> MarshallerFactory.getFor(java.lang.Object.class).read(e.getValue().getData(), e.getValue().getType()))),
         proto.hasExternalCashTransactionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getExternalCashTransactionLocator().getMsb(), proto.getExternalCashTransactionLocator().getLsb())) : Optional.empty(),
         proto.hasPaymentMode() ? Optional.of(proto.getPaymentMode().isEmpty() ? null : com.socotra.coremodel.PaymentMode.valueOf(proto.getPaymentMode())) : Optional.empty(),
         proto.hasAggregatePaymentLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getAggregatePaymentLocator().getMsb(), proto.getAggregatePaymentLocator().getLsb())) : Optional.empty(),
         proto.getSubpaymentsList().stream().map(f -> Subpayment.fromProto(f)).toList(),
         proto.hasAnonymizedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAnonymizedAt().getSeconds(), proto.getAnonymizedAt().getNanos())) : Optional.empty(),
         proto.hasAutopayTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAutopayTime().getSeconds(), proto.getAutopayTime().getNanos())) : Optional.empty(),
         proto.hasNextRequestTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getNextRequestTime().getSeconds(), proto.getNextRequestTime().getNanos())) : Optional.empty(),
         proto.getPaymentExecutionHistoryList().stream().map(f -> PaymentRequestExecution.fromProto(f)).toList(),
         proto.hasRetryPlanName() ? Optional.of(proto.getRetryPlanName()) : Optional.empty()
    );
  }

  public static PaymentObjectBuilder builder() {
    return new PaymentObjectBuilder();
  }

  public static PaymentObject copyFrom(com.socotra.coremodel.interfaces.Payment<Map<String, java.lang.Object>> other) {
    return new PaymentObject(
        other.type(),
        other.locator(),
        other.paymentState(),
        other.amount(),
        other.currency(),
        other.targets(),
        other.accountLocator(),
        other.data(),
        other.externalCashTransactionLocator(),
        other.paymentMode(),
        other.aggregatePaymentLocator(),
        other.subpayments(),
        other.anonymizedAt(),
        other.autopayTime(),
        other.nextRequestTime(),
        other.paymentExecutionHistory(),
        other.retryPlanName()
    );
  }

  public PaymentObjectBuilder toBuilder() {
    return new PaymentObjectBuilder()
       .type(this.type)
       .locator(this.locator)
       .paymentState(this.paymentState)
       .amount(this.amount)
       .currency(this.currency)
       .targets(this.targets)
       .accountLocator(this.accountLocator)
       .data(this.data)
       .externalCashTransactionLocator(this.externalCashTransactionLocator)
       .paymentMode(this.paymentMode)
       .aggregatePaymentLocator(this.aggregatePaymentLocator)
       .subpayments(this.subpayments)
       .anonymizedAt(this.anonymizedAt)
       .autopayTime(this.autopayTime)
       .nextRequestTime(this.nextRequestTime)
       .paymentExecutionHistory(this.paymentExecutionHistory)
       .retryPlanName(this.retryPlanName);
  }


  public PaymentObject mergeWith(DeploymentFactory factory, CustomerObject customerObject) {
    if (customerObject instanceof com.socotra.coremodel.interfaces.Payment payment) {
      return this.toBuilder()
          .data(factory.getObjectMapper().convertValue(payment.data(), new TypeReference<>() {}))
          .build();
    }
    return this;
  }

  public static class PaymentObjectBuilder {
    private java.lang.String type;
    public PaymentObjectBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private com.socotra.platform.tools.ULID locator;
    public PaymentObjectBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.coremodel.PaymentState paymentState;
    public PaymentObjectBuilder paymentState(com.socotra.coremodel.PaymentState paymentState) {
      this.paymentState = paymentState;
      return this;
    }
    private java.math.BigDecimal amount;
    public PaymentObjectBuilder amount(java.math.BigDecimal amount) {
      this.amount = amount;
      return this;
    }
    private java.lang.String currency;
    public PaymentObjectBuilder currency(java.lang.String currency) {
      this.currency = currency;
      return this;
    }
    private Collection<CreditItem> targets;
    public PaymentObjectBuilder targets(Collection<CreditItem> targets) {
      this.targets = targets;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> accountLocator;
    public PaymentObjectBuilder accountLocator(Optional<com.socotra.platform.tools.ULID> accountLocator) {
      this.accountLocator = accountLocator;
      return this;
    }
    public PaymentObjectBuilder accountLocator(com.socotra.platform.tools.ULID accountLocator) {
      this.accountLocator = Optional.ofNullable(accountLocator);
      return this;
    }
    private Map<java.lang.String,java.lang.Object> data;
    public PaymentObjectBuilder data(Map<java.lang.String,java.lang.Object> data) {
      this.data = data;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> externalCashTransactionLocator;
    public PaymentObjectBuilder externalCashTransactionLocator(Optional<com.socotra.platform.tools.ULID> externalCashTransactionLocator) {
      this.externalCashTransactionLocator = externalCashTransactionLocator;
      return this;
    }
    public PaymentObjectBuilder externalCashTransactionLocator(com.socotra.platform.tools.ULID externalCashTransactionLocator) {
      this.externalCashTransactionLocator = Optional.ofNullable(externalCashTransactionLocator);
      return this;
    }
    private Optional<com.socotra.coremodel.PaymentMode> paymentMode;
    public PaymentObjectBuilder paymentMode(Optional<com.socotra.coremodel.PaymentMode> paymentMode) {
      this.paymentMode = paymentMode;
      return this;
    }
    public PaymentObjectBuilder paymentMode(com.socotra.coremodel.PaymentMode paymentMode) {
      this.paymentMode = Optional.ofNullable(paymentMode);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> aggregatePaymentLocator;
    public PaymentObjectBuilder aggregatePaymentLocator(Optional<com.socotra.platform.tools.ULID> aggregatePaymentLocator) {
      this.aggregatePaymentLocator = aggregatePaymentLocator;
      return this;
    }
    public PaymentObjectBuilder aggregatePaymentLocator(com.socotra.platform.tools.ULID aggregatePaymentLocator) {
      this.aggregatePaymentLocator = Optional.ofNullable(aggregatePaymentLocator);
      return this;
    }
    private Collection<Subpayment> subpayments;
    public PaymentObjectBuilder subpayments(Collection<Subpayment> subpayments) {
      this.subpayments = subpayments;
      return this;
    }
    private Optional<java.time.Instant> anonymizedAt;
    public PaymentObjectBuilder anonymizedAt(Optional<java.time.Instant> anonymizedAt) {
      this.anonymizedAt = anonymizedAt;
      return this;
    }
    public PaymentObjectBuilder anonymizedAt(java.time.Instant anonymizedAt) {
      this.anonymizedAt = Optional.ofNullable(anonymizedAt);
      return this;
    }
    private Optional<java.time.Instant> autopayTime;
    public PaymentObjectBuilder autopayTime(Optional<java.time.Instant> autopayTime) {
      this.autopayTime = autopayTime;
      return this;
    }
    public PaymentObjectBuilder autopayTime(java.time.Instant autopayTime) {
      this.autopayTime = Optional.ofNullable(autopayTime);
      return this;
    }
    private Optional<java.time.Instant> nextRequestTime;
    public PaymentObjectBuilder nextRequestTime(Optional<java.time.Instant> nextRequestTime) {
      this.nextRequestTime = nextRequestTime;
      return this;
    }
    public PaymentObjectBuilder nextRequestTime(java.time.Instant nextRequestTime) {
      this.nextRequestTime = Optional.ofNullable(nextRequestTime);
      return this;
    }
    private Collection<PaymentRequestExecution> paymentExecutionHistory;
    public PaymentObjectBuilder paymentExecutionHistory(Collection<PaymentRequestExecution> paymentExecutionHistory) {
      this.paymentExecutionHistory = paymentExecutionHistory;
      return this;
    }
    private Optional<java.lang.String> retryPlanName;
    public PaymentObjectBuilder retryPlanName(Optional<java.lang.String> retryPlanName) {
      this.retryPlanName = retryPlanName;
      return this;
    }
    public PaymentObjectBuilder retryPlanName(java.lang.String retryPlanName) {
      this.retryPlanName = Optional.ofNullable(retryPlanName);
      return this;
    }
    public PaymentObjectBuilder() {
      targets = new ArrayList<>();
      data = new HashMap<>();
      subpayments = new ArrayList<>();
      paymentExecutionHistory = new ArrayList<>();
    }
    public PaymentObject build() {
      return new PaymentObject(
          type,
          locator,
          paymentState,
          amount,
          currency,
          targets,
          accountLocator,
          data,
          externalCashTransactionLocator,
          paymentMode,
          aggregatePaymentLocator,
          subpayments,
          anonymizedAt,
          autopayTime,
          nextRequestTime,
          paymentExecutionHistory,
          retryPlanName
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public PaymentObjectBuilder addTarget(CreditItem field) {
      this.targets = copyIfImmutable(this.targets, c -> c.add(field));
      return this;
    }
    public PaymentObjectBuilder addTargets(Collection<CreditItem> fields) {
      this.targets = copyIfImmutable(this.targets, c -> c.addAll(fields));
      return this;
    }
    public boolean hasTargets() {
      return !this.targets.isEmpty();
    }
    public PaymentObjectBuilder addSubpayment(Subpayment field) {
      this.subpayments = copyIfImmutable(this.subpayments, c -> c.add(field));
      return this;
    }
    public PaymentObjectBuilder addSubpayments(Collection<Subpayment> fields) {
      this.subpayments = copyIfImmutable(this.subpayments, c -> c.addAll(fields));
      return this;
    }
    public boolean hasSubpayments() {
      return !this.subpayments.isEmpty();
    }
    public PaymentObjectBuilder addPaymentExecutionHistory(PaymentRequestExecution field) {
      this.paymentExecutionHistory = copyIfImmutable(this.paymentExecutionHistory, c -> c.add(field));
      return this;
    }
    public PaymentObjectBuilder addPaymentExecutionHistory(Collection<PaymentRequestExecution> fields) {
      this.paymentExecutionHistory = copyIfImmutable(this.paymentExecutionHistory, c -> c.addAll(fields));
      return this;
    }
    public boolean hasPaymentExecutionHistory() {
      return !this.paymentExecutionHistory.isEmpty();
    }


  }
}
