/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record PaymentRequestExecution(
    com.socotra.platform.tools.ULID paymentRequestLocator,
    com.socotra.coremodel.PaymentRequestState paymentRequestState,
    Optional<java.time.Instant> requestTime,
    Optional<java.lang.String> transactionId,
    Optional<java.lang.String> note,
    Map<java.lang.String,java.lang.Object> data
) 
{
  public PaymentRequestExecution {
    
    requestTime = requestTime == null ? Optional.empty() : requestTime;
    transactionId = transactionId == null ? Optional.empty() : transactionId;
    note = note == null ? Optional.empty() : note;
    data = data == null ? Map.of() : data.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));

    Objects.requireNonNull(paymentRequestLocator, "paymentRequestLocator is required but it is null");
    Objects.requireNonNull(paymentRequestState, "paymentRequestState is required but it is null");
    Objects.requireNonNull(requestTime, "requestTime is required but it is null");
    Objects.requireNonNull(transactionId, "transactionId is required but it is null");
    Objects.requireNonNull(note, "note is required but it is null");

 }

  public com.socotra.coremodel.protobuf.PaymentRequestExecution toProto() {
    com.socotra.coremodel.protobuf.PaymentRequestExecution.Builder builder = com.socotra.coremodel.protobuf.PaymentRequestExecution.newBuilder();
    if (paymentRequestLocator != null) {
      builder.setPaymentRequestLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(paymentRequestLocator.getMostSignificantBits()).setLsb(paymentRequestLocator.getLeastSignificantBits()).build());
    }
    if (paymentRequestState != null) {
      builder.setPaymentRequestState(this.paymentRequestState.name());
    }
    if (requestTime.isPresent()) {
      builder.setRequestTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(requestTime.get().getEpochSecond()).setNanos(requestTime.get().getNano()).build());
    }
    if (transactionId.isPresent()) {
      builder.setTransactionId(this.transactionId.get());
    }
    if (note.isPresent()) {
      builder.setNote(this.note.get());
    }
    builder.putAllData(data.isEmpty() ? Map.of() :data.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> com.socotra.protobuf.Object.newBuilder().setData(MarshallerFactory.getFor(e.getValue().getClass()).write(e.getValue())).setType(e.getValue().getClass().getName()).build())));
    return builder.build();
  }

  public PaymentRequestExecution toTransport() {
    return toBuilder()
        .build();
  }

  public static PaymentRequestExecution fromProto(com.socotra.coremodel.protobuf.PaymentRequestExecution proto) {
    return new PaymentRequestExecution(
         new com.socotra.platform.tools.ULID(proto.getPaymentRequestLocator().getMsb(), proto.getPaymentRequestLocator().getLsb()),
         proto.getPaymentRequestState().isEmpty() ? null : com.socotra.coremodel.PaymentRequestState.valueOf(proto.getPaymentRequestState()),
         proto.hasRequestTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getRequestTime().getSeconds(), proto.getRequestTime().getNanos())) : Optional.empty(),
         proto.hasTransactionId() ? Optional.of(proto.getTransactionId()) : Optional.empty(),
         proto.hasNote() ? Optional.of(proto.getNote()) : Optional.empty(),
         proto.getDataMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> MarshallerFactory.getFor(java.lang.Object.class).read(e.getValue().getData(), e.getValue().getType())))
    );
  }

  public static PaymentRequestExecutionBuilder builder() {
    return new PaymentRequestExecutionBuilder();
  }


  public PaymentRequestExecutionBuilder toBuilder() {
    return new PaymentRequestExecutionBuilder()
       .paymentRequestLocator(this.paymentRequestLocator)
       .paymentRequestState(this.paymentRequestState)
       .requestTime(this.requestTime)
       .transactionId(this.transactionId)
       .note(this.note)
       .data(this.data);
  }




  public static class PaymentRequestExecutionBuilder {
    private com.socotra.platform.tools.ULID paymentRequestLocator;
    public PaymentRequestExecutionBuilder paymentRequestLocator(com.socotra.platform.tools.ULID paymentRequestLocator) {
      this.paymentRequestLocator = paymentRequestLocator;
      return this;
    }
    private com.socotra.coremodel.PaymentRequestState paymentRequestState;
    public PaymentRequestExecutionBuilder paymentRequestState(com.socotra.coremodel.PaymentRequestState paymentRequestState) {
      this.paymentRequestState = paymentRequestState;
      return this;
    }
    private Optional<java.time.Instant> requestTime;
    public PaymentRequestExecutionBuilder requestTime(Optional<java.time.Instant> requestTime) {
      this.requestTime = requestTime;
      return this;
    }
    public PaymentRequestExecutionBuilder requestTime(java.time.Instant requestTime) {
      this.requestTime = Optional.ofNullable(requestTime);
      return this;
    }
    private Optional<java.lang.String> transactionId;
    public PaymentRequestExecutionBuilder transactionId(Optional<java.lang.String> transactionId) {
      this.transactionId = transactionId;
      return this;
    }
    public PaymentRequestExecutionBuilder transactionId(java.lang.String transactionId) {
      this.transactionId = Optional.ofNullable(transactionId);
      return this;
    }
    private Optional<java.lang.String> note;
    public PaymentRequestExecutionBuilder note(Optional<java.lang.String> note) {
      this.note = note;
      return this;
    }
    public PaymentRequestExecutionBuilder note(java.lang.String note) {
      this.note = Optional.ofNullable(note);
      return this;
    }
    private Map<java.lang.String,java.lang.Object> data;
    public PaymentRequestExecutionBuilder data(Map<java.lang.String,java.lang.Object> data) {
      this.data = data;
      return this;
    }
    public PaymentRequestExecutionBuilder() {
      data = new HashMap<>();
    }
    public PaymentRequestExecution build() {
      return new PaymentRequestExecution(
          paymentRequestLocator,
          paymentRequestState,
          requestTime,
          transactionId,
          note,
          data
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
