/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record PreCommitDelinquencyEventsResponse(
    Map<java.lang.String,DelinquencyEventUpdateRequest> updateRequests,
    Collection<com.socotra.platform.tools.ULID> removalLocators
) 
{
  public PreCommitDelinquencyEventsResponse {
    updateRequests = updateRequests == null ? Map.of() : updateRequests.entrySet().stream().filter(e -> e.getValue() != null).collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));
    removalLocators = removalLocators == null ? List.of() : List.copyOf(removalLocators);
    removalLocators = removalLocators.stream().distinct().collect(Collectors.toList());
    if(!updateRequests.isEmpty() && !removalLocators.isEmpty()) {
        List<com.socotra.platform.tools.ULID> illegalLocators = new ArrayList<>();
        for (com.socotra.platform.tools.ULID locator : removalLocators) {
            if(updateRequests.containsKey(locator.toString())) {
                illegalLocators.add(locator);
            }
        }
        if(!illegalLocators.isEmpty()) {
            throw new IllegalArgumentException("The delinquencyEvent with locators: [%s] can not be updated and removed at the same time".formatted(illegalLocators));
        }
    }

 }

  public com.socotra.coremodel.protobuf.PreCommitDelinquencyEventsResponse toProto() {
    com.socotra.coremodel.protobuf.PreCommitDelinquencyEventsResponse.Builder builder = com.socotra.coremodel.protobuf.PreCommitDelinquencyEventsResponse.newBuilder();
    builder.putAllUpdateRequests(updateRequests.entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().toProto())));
    builder.addAllRemovalLocators(this.removalLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    return builder.build();
  }

  public PreCommitDelinquencyEventsResponse toTransport() {
    return toBuilder()
        .removalLocators(List.of())
        .build();
  }

  public static PreCommitDelinquencyEventsResponse fromProto(com.socotra.coremodel.protobuf.PreCommitDelinquencyEventsResponse proto) {
    return new PreCommitDelinquencyEventsResponse(
         proto.getUpdateRequestsMap().entrySet().stream().collect(Collectors.toMap(Map.Entry::getKey, e -> DelinquencyEventUpdateRequest.fromProto(e.getValue()))),
         proto.getRemovalLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList()
    );
  }

  public static PreCommitDelinquencyEventsResponseBuilder builder() {
    return new PreCommitDelinquencyEventsResponseBuilder();
  }


  public PreCommitDelinquencyEventsResponseBuilder toBuilder() {
    return new PreCommitDelinquencyEventsResponseBuilder()
       .updateRequests(this.updateRequests)
       .removalLocators(this.removalLocators);
  }




  public static class PreCommitDelinquencyEventsResponseBuilder {
    private Map<java.lang.String,DelinquencyEventUpdateRequest> updateRequests;
    public PreCommitDelinquencyEventsResponseBuilder updateRequests(Map<java.lang.String,DelinquencyEventUpdateRequest> updateRequests) {
      this.updateRequests = updateRequests;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> removalLocators;
    public PreCommitDelinquencyEventsResponseBuilder removalLocators(Collection<com.socotra.platform.tools.ULID> removalLocators) {
      this.removalLocators = removalLocators;
      return this;
    }
    public PreCommitDelinquencyEventsResponseBuilder() {
      updateRequests = new HashMap<>();
      removalLocators = new ArrayList<>();
    }
    public PreCommitDelinquencyEventsResponse build() {
      return new PreCommitDelinquencyEventsResponse(
          updateRequests,
          removalLocators
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public PreCommitDelinquencyEventsResponseBuilder addRemovalLocator(com.socotra.platform.tools.ULID field) {
      this.removalLocators = copyIfImmutable(this.removalLocators, c -> c.add(field));
      return this;
    }
    public PreCommitDelinquencyEventsResponseBuilder addRemovalLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.removalLocators = copyIfImmutable(this.removalLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasRemovalLocators() {
      return !this.removalLocators.isEmpty();
    }


  }
}
