/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record QuoteGroup(
    com.socotra.platform.tools.ULID locator,
    java.lang.String name,
    Optional<java.lang.String> quoteGroupNumber,
    com.socotra.coremodel.QuoteGroupState quoteGroupState,
    QuoteGroupSettings settings,
    java.time.Instant createdAt,
    java.util.UUID createdBy,
    Collection<com.socotra.platform.tools.ULID> quoteLocators,
    Optional<com.socotra.platform.tools.ULID> preferredQuoteLocator
) 
{
  public QuoteGroup {
    quoteGroupNumber = quoteGroupNumber == null ? Optional.empty() : quoteGroupNumber;
    
    preferredQuoteLocator = preferredQuoteLocator == null ? Optional.empty() : preferredQuoteLocator;
    quoteLocators = quoteLocators == null ? List.of() : List.copyOf(quoteLocators);
    if (name != null && name.length() > 64) {
      throw new IllegalArgumentException("name must be at most 64 characters");
    }
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(name, "name is required but it is null");
    Objects.requireNonNull(quoteGroupNumber, "quoteGroupNumber is required but it is null");
    Objects.requireNonNull(quoteGroupState, "quoteGroupState is required but it is null");
    Objects.requireNonNull(settings, "settings is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(createdBy, "createdBy is required but it is null");
    Objects.requireNonNull(preferredQuoteLocator, "preferredQuoteLocator is required but it is null");

 }

  public com.socotra.coremodel.protobuf.QuoteGroup toProto() {
    com.socotra.coremodel.protobuf.QuoteGroup.Builder builder = com.socotra.coremodel.protobuf.QuoteGroup.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (name != null) {
      builder.setName(this.name);
    }
    if (quoteGroupNumber.isPresent()) {
      builder.setQuoteGroupNumber(this.quoteGroupNumber.get());
    }
    if (quoteGroupState != null) {
      builder.setQuoteGroupState(this.quoteGroupState.name());
    }
    if (settings != null) {
      builder.setSettings(settings.toProto());
    }
    if (createdAt != null) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.getEpochSecond()).setNanos(createdAt.getNano()).build());
    }
    if (createdBy != null) {
      builder.setCreatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(createdBy.getMostSignificantBits()).setLsb(createdBy.getLeastSignificantBits()).build());
    }
    builder.addAllQuoteLocators(this.quoteLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    if (preferredQuoteLocator.isPresent()) {
      builder.setPreferredQuoteLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(preferredQuoteLocator.get().getMostSignificantBits()).setLsb(preferredQuoteLocator.get().getLeastSignificantBits()).build());
    }
    return builder.build();
  }

  public QuoteGroup toTransport() {
    return toBuilder()
        .quoteLocators(List.of())
        .build();
  }

  public static QuoteGroup fromProto(com.socotra.coremodel.protobuf.QuoteGroup proto) {
    return new QuoteGroup(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getName(),
         proto.hasQuoteGroupNumber() ? Optional.of(proto.getQuoteGroupNumber()) : Optional.empty(),
         proto.getQuoteGroupState().isEmpty() ? null : com.socotra.coremodel.QuoteGroupState.valueOf(proto.getQuoteGroupState()),
         QuoteGroupSettings.fromProto(proto.getSettings()),
         java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos()),
         new java.util.UUID(proto.getCreatedBy().getMsb(), proto.getCreatedBy().getLsb()),
         proto.getQuoteLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.hasPreferredQuoteLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getPreferredQuoteLocator().getMsb(), proto.getPreferredQuoteLocator().getLsb())) : Optional.empty()
    );
  }

  public static QuoteGroupBuilder builder() {
    return new QuoteGroupBuilder();
  }


  public QuoteGroupBuilder toBuilder() {
    return new QuoteGroupBuilder()
       .locator(this.locator)
       .name(this.name)
       .quoteGroupNumber(this.quoteGroupNumber)
       .quoteGroupState(this.quoteGroupState)
       .settings(this.settings)
       .createdAt(this.createdAt)
       .createdBy(this.createdBy)
       .quoteLocators(this.quoteLocators)
       .preferredQuoteLocator(this.preferredQuoteLocator);
  }




  public static class QuoteGroupBuilder {
    private com.socotra.platform.tools.ULID locator;
    public QuoteGroupBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private java.lang.String name;
    public QuoteGroupBuilder name(java.lang.String name) {
      this.name = name;
      return this;
    }
    private Optional<java.lang.String> quoteGroupNumber;
    public QuoteGroupBuilder quoteGroupNumber(Optional<java.lang.String> quoteGroupNumber) {
      this.quoteGroupNumber = quoteGroupNumber;
      return this;
    }
    public QuoteGroupBuilder quoteGroupNumber(java.lang.String quoteGroupNumber) {
      this.quoteGroupNumber = Optional.ofNullable(quoteGroupNumber);
      return this;
    }
    private com.socotra.coremodel.QuoteGroupState quoteGroupState;
    public QuoteGroupBuilder quoteGroupState(com.socotra.coremodel.QuoteGroupState quoteGroupState) {
      this.quoteGroupState = quoteGroupState;
      return this;
    }
    private QuoteGroupSettings settings;
    public QuoteGroupBuilder settings(QuoteGroupSettings settings) {
      this.settings = settings;
      return this;
    }
    private java.time.Instant createdAt;
    public QuoteGroupBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    private java.util.UUID createdBy;
    public QuoteGroupBuilder createdBy(java.util.UUID createdBy) {
      this.createdBy = createdBy;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> quoteLocators;
    public QuoteGroupBuilder quoteLocators(Collection<com.socotra.platform.tools.ULID> quoteLocators) {
      this.quoteLocators = quoteLocators;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> preferredQuoteLocator;
    public QuoteGroupBuilder preferredQuoteLocator(Optional<com.socotra.platform.tools.ULID> preferredQuoteLocator) {
      this.preferredQuoteLocator = preferredQuoteLocator;
      return this;
    }
    public QuoteGroupBuilder preferredQuoteLocator(com.socotra.platform.tools.ULID preferredQuoteLocator) {
      this.preferredQuoteLocator = Optional.ofNullable(preferredQuoteLocator);
      return this;
    }
    public QuoteGroupBuilder() {
      quoteLocators = new ArrayList<>();
    }
    public QuoteGroup build() {
      return new QuoteGroup(
          locator,
          name,
          quoteGroupNumber,
          quoteGroupState,
          settings,
          createdAt,
          createdBy,
          quoteLocators,
          preferredQuoteLocator
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public QuoteGroupBuilder addQuoteLocator(com.socotra.platform.tools.ULID field) {
      this.quoteLocators = copyIfImmutable(this.quoteLocators, c -> c.add(field));
      return this;
    }
    public QuoteGroupBuilder addQuoteLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.quoteLocators = copyIfImmutable(this.quoteLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasQuoteLocators() {
      return !this.quoteLocators.isEmpty();
    }


  }
}
