/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Quote(
    com.socotra.platform.tools.ULID locator,
    com.socotra.coremodel.QuoteState quoteState,
    java.lang.String productName,
    com.socotra.platform.tools.ULID accountLocator,
    Optional<java.time.Instant> startTime,
    Optional<java.time.Instant> endTime,
    Optional<java.lang.String> timezone,
    Optional<java.lang.String> currency,
    Optional<java.lang.String> underwritingStatus,
    Optional<java.time.Instant> expirationTime,
    Element element,
    java.lang.String type,
    Optional<Preferences> preferences,
    Optional<com.socotra.platform.tools.ULID> policyLocator,
    Optional<java.lang.String> delinquencyPlanName,
    Optional<com.socotra.coremodel.DurationBasis> durationBasis,
    com.socotra.platform.tools.ULID groupLocator,
    Optional<java.lang.String> autoRenewalPlanName,
    com.socotra.coremodel.BillingLevel billingLevel,
    Optional<byte[]> securityId,
    Optional<java.lang.String> region,
    Optional<java.lang.String> quoteNumber,
    Optional<java.math.BigDecimal> duration,
    Optional<java.time.Instant> acceptedTime,
    Optional<java.time.Instant> issuedTime,
    Optional<ValidationResult> validationResult,
    Optional<com.socotra.platform.tools.ULID> quickQuoteLocator,
    Collection<ContactRoles> contacts,
    Optional<java.time.Instant> anonymizedAt,
    Optional<java.math.BigDecimal> invoiceFeeAmount,
    Optional<java.util.UUID> createdBy,
    Optional<java.time.Instant> createdAt,
    Optional<java.lang.Boolean> checkHold,
    Optional<java.lang.String> jurisdiction,
    Optional<java.lang.String> producerCode,
    Optional<com.socotra.platform.tools.ULID> configVersionLocator,
    Optional<java.lang.String> reservedPolicyNumber
)  implements com.socotra.coremodel.interfaces.Quote
{
  public Quote {
    
    startTime = startTime == null ? Optional.empty() : startTime;
    endTime = endTime == null ? Optional.empty() : endTime;
    timezone = timezone == null ? Optional.empty() : timezone;
    currency = currency == null ? Optional.empty() : currency;
    underwritingStatus = underwritingStatus == null ? Optional.empty() : underwritingStatus;
    expirationTime = expirationTime == null ? Optional.empty() : expirationTime;
    preferences = preferences == null ? Optional.empty() : preferences;
    policyLocator = policyLocator == null ? Optional.empty() : policyLocator;
    delinquencyPlanName = delinquencyPlanName == null ? Optional.empty() : delinquencyPlanName;
    durationBasis = durationBasis == null ? Optional.empty() : durationBasis;

    autoRenewalPlanName = autoRenewalPlanName == null ? Optional.empty() : autoRenewalPlanName;
    billingLevel = billingLevel == null ? com.socotra.coremodel.BillingLevel.inherit : billingLevel;

    securityId = securityId == null ? Optional.empty() : securityId;
    region = region == null ? Optional.empty() : region;
    quoteNumber = quoteNumber == null ? Optional.empty() : quoteNumber;
    duration = duration == null ? Optional.empty() : duration;
    acceptedTime = acceptedTime == null ? Optional.empty() : acceptedTime;
    issuedTime = issuedTime == null ? Optional.empty() : issuedTime;
    validationResult = validationResult == null ? Optional.empty() : validationResult;
    quickQuoteLocator = quickQuoteLocator == null ? Optional.empty() : quickQuoteLocator;
    anonymizedAt = anonymizedAt == null ? Optional.empty() : anonymizedAt;
    invoiceFeeAmount = invoiceFeeAmount == null ? Optional.empty() : invoiceFeeAmount;
    createdBy = createdBy == null ? Optional.empty() : createdBy;
    createdAt = createdAt == null ? Optional.empty() : createdAt;
    checkHold = checkHold == null ? Optional.empty() : checkHold;
    jurisdiction = jurisdiction == null ? Optional.empty() : jurisdiction;
    producerCode = producerCode == null ? Optional.empty() : producerCode;
    configVersionLocator = configVersionLocator == null ? Optional.empty() : configVersionLocator;
    reservedPolicyNumber = reservedPolicyNumber == null ? Optional.empty() : reservedPolicyNumber;
    contacts = contacts == null ? List.of() : List.copyOf(contacts);
    startTime = startTime.map(t -> t.truncatedTo(java.time.temporal.ChronoUnit.SECONDS));
    endTime = endTime.map(t -> t.truncatedTo(java.time.temporal.ChronoUnit.SECONDS));
    if(!locator.equals(element.locator())) {
        throw new IllegalArgumentException("locator must match element.locator");
    }
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(quoteState, "quoteState is required but it is null");
    Objects.requireNonNull(productName, "productName is required but it is null");
    Objects.requireNonNull(accountLocator, "accountLocator is required but it is null");
    Objects.requireNonNull(startTime, "startTime is required but it is null");
    Objects.requireNonNull(endTime, "endTime is required but it is null");
    Objects.requireNonNull(timezone, "timezone is required but it is null");
    Objects.requireNonNull(currency, "currency is required but it is null");
    Objects.requireNonNull(underwritingStatus, "underwritingStatus is required but it is null");
    Objects.requireNonNull(expirationTime, "expirationTime is required but it is null");
    Objects.requireNonNull(element, "element is required but it is null");
    Objects.requireNonNull(preferences, "preferences is required but it is null");
    Objects.requireNonNull(policyLocator, "policyLocator is required but it is null");
    Objects.requireNonNull(delinquencyPlanName, "delinquencyPlanName is required but it is null");
    Objects.requireNonNull(durationBasis, "durationBasis is required but it is null");
    Objects.requireNonNull(autoRenewalPlanName, "autoRenewalPlanName is required but it is null");
    Objects.requireNonNull(billingLevel, "billingLevel is required but it is null");
    Objects.requireNonNull(securityId, "securityId is required but it is null");
    Objects.requireNonNull(region, "region is required but it is null");
    Objects.requireNonNull(quoteNumber, "quoteNumber is required but it is null");
    Objects.requireNonNull(duration, "duration is required but it is null");
    Objects.requireNonNull(acceptedTime, "acceptedTime is required but it is null");
    Objects.requireNonNull(issuedTime, "issuedTime is required but it is null");
    Objects.requireNonNull(validationResult, "validationResult is required but it is null");
    Objects.requireNonNull(quickQuoteLocator, "quickQuoteLocator is required but it is null");
    Objects.requireNonNull(anonymizedAt, "anonymizedAt is required but it is null");
    Objects.requireNonNull(invoiceFeeAmount, "invoiceFeeAmount is required but it is null");
    Objects.requireNonNull(createdBy, "createdBy is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(checkHold, "checkHold is required but it is null");
    Objects.requireNonNull(jurisdiction, "jurisdiction is required but it is null");
    Objects.requireNonNull(producerCode, "producerCode is required but it is null");
    Objects.requireNonNull(configVersionLocator, "configVersionLocator is required but it is null");
    Objects.requireNonNull(reservedPolicyNumber, "reservedPolicyNumber is required but it is null");

 }

  public com.socotra.coremodel.protobuf.Quote toProto() {
    com.socotra.coremodel.protobuf.Quote.Builder builder = com.socotra.coremodel.protobuf.Quote.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (quoteState != null) {
      builder.setQuoteState(this.quoteState.name());
    }
    if (productName != null) {
      builder.setProductName(this.productName);
    }
    if (accountLocator != null) {
      builder.setAccountLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(accountLocator.getMostSignificantBits()).setLsb(accountLocator.getLeastSignificantBits()).build());
    }
    if (startTime.isPresent()) {
      builder.setStartTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(startTime.get().getEpochSecond()).setNanos(startTime.get().getNano()).build());
    }
    if (endTime.isPresent()) {
      builder.setEndTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(endTime.get().getEpochSecond()).setNanos(endTime.get().getNano()).build());
    }
    if (timezone.isPresent()) {
      builder.setTimezone(this.timezone.get());
    }
    if (currency.isPresent()) {
      builder.setCurrency(this.currency.get());
    }
    if (underwritingStatus.isPresent()) {
      builder.setUnderwritingStatus(this.underwritingStatus.get());
    }
    if (expirationTime.isPresent()) {
      builder.setExpirationTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(expirationTime.get().getEpochSecond()).setNanos(expirationTime.get().getNano()).build());
    }
    if (element != null) {
      builder.setElement(element.toProto());
    }
    if (type != null) {
      builder.setType(this.type);
    }
    if (preferences.isPresent()) {
      builder.setPreferences(preferences.get().toProto());
    }
    if (policyLocator.isPresent()) {
      builder.setPolicyLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(policyLocator.get().getMostSignificantBits()).setLsb(policyLocator.get().getLeastSignificantBits()).build());
    }
    if (delinquencyPlanName.isPresent()) {
      builder.setDelinquencyPlanName(this.delinquencyPlanName.get());
    }
    if (durationBasis.isPresent()) {
      builder.setDurationBasis(this.durationBasis.get().name());
    }
    if (groupLocator != null) {
      builder.setGroupLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(groupLocator.getMostSignificantBits()).setLsb(groupLocator.getLeastSignificantBits()).build());
    }
    if (autoRenewalPlanName.isPresent()) {
      builder.setAutoRenewalPlanName(this.autoRenewalPlanName.get());
    }
    if (billingLevel != null) {
      builder.setBillingLevel(this.billingLevel.name());
    }
    if (securityId.isPresent()) {
      builder.setSecurityId(com.google.protobuf.ByteString.copyFrom(securityId.get()));
    }
    if (region.isPresent()) {
      builder.setRegion(this.region.get());
    }
    if (quoteNumber.isPresent()) {
      builder.setQuoteNumber(this.quoteNumber.get());
    }
    if (duration.isPresent()) {
      builder.setDuration(com.socotra.protobuf.BigDecimal.newBuilder().setScale(duration.get().scale()).setPrecision(duration.get().precision()).setValue(com.google.protobuf.ByteString.copyFrom(duration.get().unscaledValue().toByteArray())).build());
    }
    if (acceptedTime.isPresent()) {
      builder.setAcceptedTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(acceptedTime.get().getEpochSecond()).setNanos(acceptedTime.get().getNano()).build());
    }
    if (issuedTime.isPresent()) {
      builder.setIssuedTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(issuedTime.get().getEpochSecond()).setNanos(issuedTime.get().getNano()).build());
    }
    if (validationResult.isPresent()) {
      builder.setValidationResult(validationResult.get().toProto());
    }
    if (quickQuoteLocator.isPresent()) {
      builder.setQuickQuoteLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(quickQuoteLocator.get().getMostSignificantBits()).setLsb(quickQuoteLocator.get().getLeastSignificantBits()).build());
    }
    builder.addAllContacts(this.contacts.stream().map(f -> f.toProto()).toList());
    if (anonymizedAt.isPresent()) {
      builder.setAnonymizedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(anonymizedAt.get().getEpochSecond()).setNanos(anonymizedAt.get().getNano()).build());
    }
    if (invoiceFeeAmount.isPresent()) {
      builder.setInvoiceFeeAmount(com.socotra.protobuf.BigDecimal.newBuilder().setScale(invoiceFeeAmount.get().scale()).setPrecision(invoiceFeeAmount.get().precision()).setValue(com.google.protobuf.ByteString.copyFrom(invoiceFeeAmount.get().unscaledValue().toByteArray())).build());
    }
    if (createdBy.isPresent()) {
      builder.setCreatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(createdBy.get().getMostSignificantBits()).setLsb(createdBy.get().getLeastSignificantBits()).build());
    }
    if (createdAt.isPresent()) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.get().getEpochSecond()).setNanos(createdAt.get().getNano()).build());
    }
    if (checkHold.isPresent()) {
      builder.setCheckHold(this.checkHold.get());
    }
    if (jurisdiction.isPresent()) {
      builder.setJurisdiction(this.jurisdiction.get());
    }
    if (producerCode.isPresent()) {
      builder.setProducerCode(this.producerCode.get());
    }
    if (configVersionLocator.isPresent()) {
      builder.setConfigVersionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(configVersionLocator.get().getMostSignificantBits()).setLsb(configVersionLocator.get().getLeastSignificantBits()).build());
    }
    if (reservedPolicyNumber.isPresent()) {
      builder.setReservedPolicyNumber(this.reservedPolicyNumber.get());
    }
    return builder.build();
  }

  public Quote toTransport() {
    return toBuilder()
        .contacts(List.of())
        .build();
  }

  public static Quote fromProto(com.socotra.coremodel.protobuf.Quote proto) {
    return new Quote(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getQuoteState().isEmpty() ? null : com.socotra.coremodel.QuoteState.valueOf(proto.getQuoteState()),
         proto.getProductName(),
         new com.socotra.platform.tools.ULID(proto.getAccountLocator().getMsb(), proto.getAccountLocator().getLsb()),
         proto.hasStartTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getStartTime().getSeconds(), proto.getStartTime().getNanos())) : Optional.empty(),
         proto.hasEndTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getEndTime().getSeconds(), proto.getEndTime().getNanos())) : Optional.empty(),
         proto.hasTimezone() ? Optional.of(proto.getTimezone()) : Optional.empty(),
         proto.hasCurrency() ? Optional.of(proto.getCurrency()) : Optional.empty(),
         proto.hasUnderwritingStatus() ? Optional.of(proto.getUnderwritingStatus()) : Optional.empty(),
         proto.hasExpirationTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getExpirationTime().getSeconds(), proto.getExpirationTime().getNanos())) : Optional.empty(),
         Element.fromProto(proto.getElement()),
         proto.getType(),
         proto.hasPreferences() ? Optional.of(Preferences.fromProto(proto.getPreferences())) : Optional.empty(),
         proto.hasPolicyLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getPolicyLocator().getMsb(), proto.getPolicyLocator().getLsb())) : Optional.empty(),
         proto.hasDelinquencyPlanName() ? Optional.of(proto.getDelinquencyPlanName()) : Optional.empty(),
         proto.hasDurationBasis() ? Optional.of(proto.getDurationBasis().isEmpty() ? null : com.socotra.coremodel.DurationBasis.valueOf(proto.getDurationBasis())) : Optional.empty(),
         new com.socotra.platform.tools.ULID(proto.getGroupLocator().getMsb(), proto.getGroupLocator().getLsb()),
         proto.hasAutoRenewalPlanName() ? Optional.of(proto.getAutoRenewalPlanName()) : Optional.empty(),
         proto.getBillingLevel().isEmpty() ? null : com.socotra.coremodel.BillingLevel.valueOf(proto.getBillingLevel()),
         proto.hasSecurityId() ? Optional.of(proto.getSecurityId().toByteArray()) : Optional.empty(),
         proto.hasRegion() ? Optional.of(proto.getRegion()) : Optional.empty(),
         proto.hasQuoteNumber() ? Optional.of(proto.getQuoteNumber()) : Optional.empty(),
         proto.hasDuration() ? Optional.of(new java.math.BigDecimal(new java.math.BigInteger(proto.getDuration().getValue().toByteArray()), proto.getDuration().getScale(), new java.math.MathContext(proto.getDuration().getPrecision()))) : Optional.empty(),
         proto.hasAcceptedTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAcceptedTime().getSeconds(), proto.getAcceptedTime().getNanos())) : Optional.empty(),
         proto.hasIssuedTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getIssuedTime().getSeconds(), proto.getIssuedTime().getNanos())) : Optional.empty(),
         proto.hasValidationResult() ? Optional.of(ValidationResult.fromProto(proto.getValidationResult())) : Optional.empty(),
         proto.hasQuickQuoteLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getQuickQuoteLocator().getMsb(), proto.getQuickQuoteLocator().getLsb())) : Optional.empty(),
         proto.getContactsList().stream().map(f -> ContactRoles.fromProto(f)).toList(),
         proto.hasAnonymizedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAnonymizedAt().getSeconds(), proto.getAnonymizedAt().getNanos())) : Optional.empty(),
         proto.hasInvoiceFeeAmount() ? Optional.of(new java.math.BigDecimal(new java.math.BigInteger(proto.getInvoiceFeeAmount().getValue().toByteArray()), proto.getInvoiceFeeAmount().getScale(), new java.math.MathContext(proto.getInvoiceFeeAmount().getPrecision()))) : Optional.empty(),
         proto.hasCreatedBy() ? Optional.of(new java.util.UUID(proto.getCreatedBy().getMsb(), proto.getCreatedBy().getLsb())) : Optional.empty(),
         proto.hasCreatedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos())) : Optional.empty(),
         proto.hasCheckHold() ? Optional.of(proto.getCheckHold()) : Optional.empty(),
         proto.hasJurisdiction() ? Optional.of(proto.getJurisdiction()) : Optional.empty(),
         proto.hasProducerCode() ? Optional.of(proto.getProducerCode()) : Optional.empty(),
         proto.hasConfigVersionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getConfigVersionLocator().getMsb(), proto.getConfigVersionLocator().getLsb())) : Optional.empty(),
         proto.hasReservedPolicyNumber() ? Optional.of(proto.getReservedPolicyNumber()) : Optional.empty()
    );
  }

  public static QuoteBuilder builder() {
    return new QuoteBuilder();
  }

  public static Quote copyFrom(com.socotra.coremodel.interfaces.Quote other) {
    return new Quote(
        other.locator(),
        other.quoteState(),
        other.productName(),
        other.accountLocator(),
        other.startTime(),
        other.endTime(),
        other.timezone(),
        other.currency(),
        other.underwritingStatus(),
        other.expirationTime(),
        other.element(),
        other.type(),
        other.preferences(),
        other.policyLocator(),
        other.delinquencyPlanName(),
        other.durationBasis(),
        other.groupLocator(),
        other.autoRenewalPlanName(),
        other.billingLevel(),
        other.securityId(),
        other.region(),
        other.quoteNumber(),
        other.duration(),
        other.acceptedTime(),
        other.issuedTime(),
        other.validationResult(),
        other.quickQuoteLocator(),
        other.contacts(),
        other.anonymizedAt(),
        other.invoiceFeeAmount(),
        other.createdBy(),
        other.createdAt(),
        other.checkHold(),
        other.jurisdiction(),
        other.producerCode(),
        other.configVersionLocator(),
        other.reservedPolicyNumber()
    );
  }

  public QuoteBuilder toBuilder() {
    return new QuoteBuilder()
       .locator(this.locator)
       .quoteState(this.quoteState)
       .productName(this.productName)
       .accountLocator(this.accountLocator)
       .startTime(this.startTime)
       .endTime(this.endTime)
       .timezone(this.timezone)
       .currency(this.currency)
       .underwritingStatus(this.underwritingStatus)
       .expirationTime(this.expirationTime)
       .element(this.element)
       .type(this.type)
       .preferences(this.preferences)
       .policyLocator(this.policyLocator)
       .delinquencyPlanName(this.delinquencyPlanName)
       .durationBasis(this.durationBasis)
       .groupLocator(this.groupLocator)
       .autoRenewalPlanName(this.autoRenewalPlanName)
       .billingLevel(this.billingLevel)
       .securityId(this.securityId)
       .region(this.region)
       .quoteNumber(this.quoteNumber)
       .duration(this.duration)
       .acceptedTime(this.acceptedTime)
       .issuedTime(this.issuedTime)
       .validationResult(this.validationResult)
       .quickQuoteLocator(this.quickQuoteLocator)
       .contacts(this.contacts)
       .anonymizedAt(this.anonymizedAt)
       .invoiceFeeAmount(this.invoiceFeeAmount)
       .createdBy(this.createdBy)
       .createdAt(this.createdAt)
       .checkHold(this.checkHold)
       .jurisdiction(this.jurisdiction)
       .producerCode(this.producerCode)
       .configVersionLocator(this.configVersionLocator)
       .reservedPolicyNumber(this.reservedPolicyNumber);
  }


  public static Quote copyFrom(
      com.socotra.coremodel.interfaces.QuickQuote qq, com.socotra.platform.tools.ULID accountLocator, Element element) {
    com.socotra.platform.tools.ULID locator = element.locator();
    return Quote.builder()
        .locator(locator)
        .quoteState(QuoteState.draft)
        .productName(qq.productName())
        .accountLocator(accountLocator)
        .startTime(qq.startTime())
        .endTime(qq.endTime())
        .timezone(qq.timezone())
        .currency(qq.currency())
        .expirationTime(qq.expirationTime())
        .element(element)
        .type(element.type())
        .duration(qq.duration())
        .durationBasis(qq.durationBasis())
        .preferences(qq.preferences())
        .delinquencyPlanName(qq.delinquencyPlanName())
        .locator(locator)
        .autoRenewalPlanName(qq.autoRenewalPlanName())
        .billingLevel(qq.billingLevel())
        .contacts(qq.contacts())
        .configVersionLocator(qq.configVersionLocator())
        .build();
  }

  public Quote mergeWith(DeploymentFactory factory, CustomerObject customerObject) {
    if (customerObject instanceof com.socotra.coremodel.interfaces.Quote q) {
      Element element = ((Elemental)q).toElement(factory);
      return toBuilder()
          .element(element)
          .endTime(q.endTime())
          .preferences(q.preferences())
          .delinquencyPlanName(q.delinquencyPlanName())
          .autoRenewalPlanName(q.autoRenewalPlanName())
          .billingLevel(q.billingLevel())
          .build();
    }
    return this;
  }

  public static class QuoteBuilder {
    private com.socotra.platform.tools.ULID locator;
    public QuoteBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.coremodel.QuoteState quoteState;
    public QuoteBuilder quoteState(com.socotra.coremodel.QuoteState quoteState) {
      this.quoteState = quoteState;
      return this;
    }
    private java.lang.String productName;
    public QuoteBuilder productName(java.lang.String productName) {
      this.productName = productName;
      return this;
    }
    private com.socotra.platform.tools.ULID accountLocator;
    public QuoteBuilder accountLocator(com.socotra.platform.tools.ULID accountLocator) {
      this.accountLocator = accountLocator;
      return this;
    }
    private Optional<java.time.Instant> startTime;
    public QuoteBuilder startTime(Optional<java.time.Instant> startTime) {
      this.startTime = startTime;
      return this;
    }
    public QuoteBuilder startTime(java.time.Instant startTime) {
      this.startTime = Optional.ofNullable(startTime);
      return this;
    }
    private Optional<java.time.Instant> endTime;
    public QuoteBuilder endTime(Optional<java.time.Instant> endTime) {
      this.endTime = endTime;
      return this;
    }
    public QuoteBuilder endTime(java.time.Instant endTime) {
      this.endTime = Optional.ofNullable(endTime);
      return this;
    }
    private Optional<java.lang.String> timezone;
    public QuoteBuilder timezone(Optional<java.lang.String> timezone) {
      this.timezone = timezone;
      return this;
    }
    public QuoteBuilder timezone(java.lang.String timezone) {
      this.timezone = Optional.ofNullable(timezone);
      return this;
    }
    private Optional<java.lang.String> currency;
    public QuoteBuilder currency(Optional<java.lang.String> currency) {
      this.currency = currency;
      return this;
    }
    public QuoteBuilder currency(java.lang.String currency) {
      this.currency = Optional.ofNullable(currency);
      return this;
    }
    private Optional<java.lang.String> underwritingStatus;
    public QuoteBuilder underwritingStatus(Optional<java.lang.String> underwritingStatus) {
      this.underwritingStatus = underwritingStatus;
      return this;
    }
    public QuoteBuilder underwritingStatus(java.lang.String underwritingStatus) {
      this.underwritingStatus = Optional.ofNullable(underwritingStatus);
      return this;
    }
    private Optional<java.time.Instant> expirationTime;
    public QuoteBuilder expirationTime(Optional<java.time.Instant> expirationTime) {
      this.expirationTime = expirationTime;
      return this;
    }
    public QuoteBuilder expirationTime(java.time.Instant expirationTime) {
      this.expirationTime = Optional.ofNullable(expirationTime);
      return this;
    }
    private Element element;
    public QuoteBuilder element(Element element) {
      this.element = element;
      return this;
    }
    private java.lang.String type;
    public QuoteBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private Optional<Preferences> preferences;
    public QuoteBuilder preferences(Optional<Preferences> preferences) {
      this.preferences = preferences;
      return this;
    }
    public QuoteBuilder preferences(Preferences preferences) {
      this.preferences = Optional.ofNullable(preferences);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> policyLocator;
    public QuoteBuilder policyLocator(Optional<com.socotra.platform.tools.ULID> policyLocator) {
      this.policyLocator = policyLocator;
      return this;
    }
    public QuoteBuilder policyLocator(com.socotra.platform.tools.ULID policyLocator) {
      this.policyLocator = Optional.ofNullable(policyLocator);
      return this;
    }
    private Optional<java.lang.String> delinquencyPlanName;
    public QuoteBuilder delinquencyPlanName(Optional<java.lang.String> delinquencyPlanName) {
      this.delinquencyPlanName = delinquencyPlanName;
      return this;
    }
    public QuoteBuilder delinquencyPlanName(java.lang.String delinquencyPlanName) {
      this.delinquencyPlanName = Optional.ofNullable(delinquencyPlanName);
      return this;
    }
    private Optional<com.socotra.coremodel.DurationBasis> durationBasis;
    public QuoteBuilder durationBasis(Optional<com.socotra.coremodel.DurationBasis> durationBasis) {
      this.durationBasis = durationBasis;
      return this;
    }
    public QuoteBuilder durationBasis(com.socotra.coremodel.DurationBasis durationBasis) {
      this.durationBasis = Optional.ofNullable(durationBasis);
      return this;
    }
    private com.socotra.platform.tools.ULID groupLocator;
    public QuoteBuilder groupLocator(com.socotra.platform.tools.ULID groupLocator) {
      this.groupLocator = groupLocator;
      return this;
    }
    private Optional<java.lang.String> autoRenewalPlanName;
    public QuoteBuilder autoRenewalPlanName(Optional<java.lang.String> autoRenewalPlanName) {
      this.autoRenewalPlanName = autoRenewalPlanName;
      return this;
    }
    public QuoteBuilder autoRenewalPlanName(java.lang.String autoRenewalPlanName) {
      this.autoRenewalPlanName = Optional.ofNullable(autoRenewalPlanName);
      return this;
    }
    private com.socotra.coremodel.BillingLevel billingLevel;
    public QuoteBuilder billingLevel(com.socotra.coremodel.BillingLevel billingLevel) {
      this.billingLevel = billingLevel;
      return this;
    }
    private Optional<byte[]> securityId;
    public QuoteBuilder securityId(Optional<byte[]> securityId) {
      this.securityId = securityId;
      return this;
    }
    public QuoteBuilder securityId(byte[] securityId) {
      this.securityId = Optional.ofNullable(securityId);
      return this;
    }
    private Optional<java.lang.String> region;
    public QuoteBuilder region(Optional<java.lang.String> region) {
      this.region = region;
      return this;
    }
    public QuoteBuilder region(java.lang.String region) {
      this.region = Optional.ofNullable(region);
      return this;
    }
    private Optional<java.lang.String> quoteNumber;
    public QuoteBuilder quoteNumber(Optional<java.lang.String> quoteNumber) {
      this.quoteNumber = quoteNumber;
      return this;
    }
    public QuoteBuilder quoteNumber(java.lang.String quoteNumber) {
      this.quoteNumber = Optional.ofNullable(quoteNumber);
      return this;
    }
    private Optional<java.math.BigDecimal> duration;
    public QuoteBuilder duration(Optional<java.math.BigDecimal> duration) {
      this.duration = duration;
      return this;
    }
    public QuoteBuilder duration(java.math.BigDecimal duration) {
      this.duration = Optional.ofNullable(duration);
      return this;
    }
    private Optional<java.time.Instant> acceptedTime;
    public QuoteBuilder acceptedTime(Optional<java.time.Instant> acceptedTime) {
      this.acceptedTime = acceptedTime;
      return this;
    }
    public QuoteBuilder acceptedTime(java.time.Instant acceptedTime) {
      this.acceptedTime = Optional.ofNullable(acceptedTime);
      return this;
    }
    private Optional<java.time.Instant> issuedTime;
    public QuoteBuilder issuedTime(Optional<java.time.Instant> issuedTime) {
      this.issuedTime = issuedTime;
      return this;
    }
    public QuoteBuilder issuedTime(java.time.Instant issuedTime) {
      this.issuedTime = Optional.ofNullable(issuedTime);
      return this;
    }
    private Optional<ValidationResult> validationResult;
    public QuoteBuilder validationResult(Optional<ValidationResult> validationResult) {
      this.validationResult = validationResult;
      return this;
    }
    public QuoteBuilder validationResult(ValidationResult validationResult) {
      this.validationResult = Optional.ofNullable(validationResult);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> quickQuoteLocator;
    public QuoteBuilder quickQuoteLocator(Optional<com.socotra.platform.tools.ULID> quickQuoteLocator) {
      this.quickQuoteLocator = quickQuoteLocator;
      return this;
    }
    public QuoteBuilder quickQuoteLocator(com.socotra.platform.tools.ULID quickQuoteLocator) {
      this.quickQuoteLocator = Optional.ofNullable(quickQuoteLocator);
      return this;
    }
    private Collection<ContactRoles> contacts;
    public QuoteBuilder contacts(Collection<ContactRoles> contacts) {
      this.contacts = contacts;
      return this;
    }
    private Optional<java.time.Instant> anonymizedAt;
    public QuoteBuilder anonymizedAt(Optional<java.time.Instant> anonymizedAt) {
      this.anonymizedAt = anonymizedAt;
      return this;
    }
    public QuoteBuilder anonymizedAt(java.time.Instant anonymizedAt) {
      this.anonymizedAt = Optional.ofNullable(anonymizedAt);
      return this;
    }
    private Optional<java.math.BigDecimal> invoiceFeeAmount;
    public QuoteBuilder invoiceFeeAmount(Optional<java.math.BigDecimal> invoiceFeeAmount) {
      this.invoiceFeeAmount = invoiceFeeAmount;
      return this;
    }
    public QuoteBuilder invoiceFeeAmount(java.math.BigDecimal invoiceFeeAmount) {
      this.invoiceFeeAmount = Optional.ofNullable(invoiceFeeAmount);
      return this;
    }
    private Optional<java.util.UUID> createdBy;
    public QuoteBuilder createdBy(Optional<java.util.UUID> createdBy) {
      this.createdBy = createdBy;
      return this;
    }
    public QuoteBuilder createdBy(java.util.UUID createdBy) {
      this.createdBy = Optional.ofNullable(createdBy);
      return this;
    }
    private Optional<java.time.Instant> createdAt;
    public QuoteBuilder createdAt(Optional<java.time.Instant> createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    public QuoteBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }
    private Optional<java.lang.Boolean> checkHold;
    public QuoteBuilder checkHold(Optional<java.lang.Boolean> checkHold) {
      this.checkHold = checkHold;
      return this;
    }
    public QuoteBuilder checkHold(java.lang.Boolean checkHold) {
      this.checkHold = Optional.ofNullable(checkHold);
      return this;
    }
    private Optional<java.lang.String> jurisdiction;
    public QuoteBuilder jurisdiction(Optional<java.lang.String> jurisdiction) {
      this.jurisdiction = jurisdiction;
      return this;
    }
    public QuoteBuilder jurisdiction(java.lang.String jurisdiction) {
      this.jurisdiction = Optional.ofNullable(jurisdiction);
      return this;
    }
    private Optional<java.lang.String> producerCode;
    public QuoteBuilder producerCode(Optional<java.lang.String> producerCode) {
      this.producerCode = producerCode;
      return this;
    }
    public QuoteBuilder producerCode(java.lang.String producerCode) {
      this.producerCode = Optional.ofNullable(producerCode);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> configVersionLocator;
    public QuoteBuilder configVersionLocator(Optional<com.socotra.platform.tools.ULID> configVersionLocator) {
      this.configVersionLocator = configVersionLocator;
      return this;
    }
    public QuoteBuilder configVersionLocator(com.socotra.platform.tools.ULID configVersionLocator) {
      this.configVersionLocator = Optional.ofNullable(configVersionLocator);
      return this;
    }
    private Optional<java.lang.String> reservedPolicyNumber;
    public QuoteBuilder reservedPolicyNumber(Optional<java.lang.String> reservedPolicyNumber) {
      this.reservedPolicyNumber = reservedPolicyNumber;
      return this;
    }
    public QuoteBuilder reservedPolicyNumber(java.lang.String reservedPolicyNumber) {
      this.reservedPolicyNumber = Optional.ofNullable(reservedPolicyNumber);
      return this;
    }
    public QuoteBuilder() {
      contacts = new ArrayList<>();
    }
    public Quote build() {
      return new Quote(
          locator,
          quoteState,
          productName,
          accountLocator,
          startTime,
          endTime,
          timezone,
          currency,
          underwritingStatus,
          expirationTime,
          element,
          type,
          preferences,
          policyLocator,
          delinquencyPlanName,
          durationBasis,
          groupLocator,
          autoRenewalPlanName,
          billingLevel,
          securityId,
          region,
          quoteNumber,
          duration,
          acceptedTime,
          issuedTime,
          validationResult,
          quickQuoteLocator,
          contacts,
          anonymizedAt,
          invoiceFeeAmount,
          createdBy,
          createdAt,
          checkHold,
          jurisdiction,
          producerCode,
          configVersionLocator,
          reservedPolicyNumber
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public QuoteBuilder addContact(ContactRoles field) {
      this.contacts = copyIfImmutable(this.contacts, c -> c.add(field));
      return this;
    }
    public QuoteBuilder addContacts(Collection<ContactRoles> fields) {
      this.contacts = copyIfImmutable(this.contacts, c -> c.addAll(fields));
      return this;
    }
    public boolean hasContacts() {
      return !this.contacts.isEmpty();
    }


  }
}
