/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record QuotePricing(
    com.socotra.platform.tools.ULID quoteLocator,
    com.socotra.platform.tools.ULID accountLocator,
    com.socotra.coremodel.QuoteState quoteState,
    java.lang.String productName,
    java.time.Instant startTime,
    java.time.Instant endTime,
    java.math.BigDecimal duration,
    com.socotra.coremodel.DurationBasis durationBasis,
    Collection<Charge> items
) 
{
  public QuotePricing {
    
    
    items = items == null ? List.of() : List.copyOf(items);
    if(startTime != null) {
      startTime = startTime.truncatedTo(java.time.temporal.ChronoUnit.SECONDS);
    }
    if(endTime != null) {
      endTime = endTime.truncatedTo(java.time.temporal.ChronoUnit.SECONDS);
    }
    Objects.requireNonNull(quoteLocator, "quoteLocator is required but it is null");
    Objects.requireNonNull(accountLocator, "accountLocator is required but it is null");
    Objects.requireNonNull(quoteState, "quoteState is required but it is null");
    Objects.requireNonNull(productName, "productName is required but it is null");
    Objects.requireNonNull(startTime, "startTime is required but it is null");
    Objects.requireNonNull(endTime, "endTime is required but it is null");
    Objects.requireNonNull(duration, "duration is required but it is null");
    Objects.requireNonNull(durationBasis, "durationBasis is required but it is null");

 }

  public com.socotra.coremodel.protobuf.QuotePricing toProto() {
    com.socotra.coremodel.protobuf.QuotePricing.Builder builder = com.socotra.coremodel.protobuf.QuotePricing.newBuilder();
    if (quoteLocator != null) {
      builder.setQuoteLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(quoteLocator.getMostSignificantBits()).setLsb(quoteLocator.getLeastSignificantBits()).build());
    }
    if (accountLocator != null) {
      builder.setAccountLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(accountLocator.getMostSignificantBits()).setLsb(accountLocator.getLeastSignificantBits()).build());
    }
    if (quoteState != null) {
      builder.setQuoteState(this.quoteState.name());
    }
    if (productName != null) {
      builder.setProductName(this.productName);
    }
    if (startTime != null) {
      builder.setStartTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(startTime.getEpochSecond()).setNanos(startTime.getNano()).build());
    }
    if (endTime != null) {
      builder.setEndTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(endTime.getEpochSecond()).setNanos(endTime.getNano()).build());
    }
    if (duration != null) {
      builder.setDuration(com.socotra.protobuf.BigDecimal.newBuilder().setScale(duration.scale()).setPrecision(duration.precision()).setValue(com.google.protobuf.ByteString.copyFrom(duration.unscaledValue().toByteArray())).build());
    }
    if (durationBasis != null) {
      builder.setDurationBasis(this.durationBasis.name());
    }
    builder.addAllItems(this.items.stream().map(f -> f.toProto()).toList());
    return builder.build();
  }

  public QuotePricing toTransport() {
    return toBuilder()
        .items(List.of())
        .build();
  }

  public static QuotePricing fromProto(com.socotra.coremodel.protobuf.QuotePricing proto) {
    return new QuotePricing(
         new com.socotra.platform.tools.ULID(proto.getQuoteLocator().getMsb(), proto.getQuoteLocator().getLsb()),
         new com.socotra.platform.tools.ULID(proto.getAccountLocator().getMsb(), proto.getAccountLocator().getLsb()),
         proto.getQuoteState().isEmpty() ? null : com.socotra.coremodel.QuoteState.valueOf(proto.getQuoteState()),
         proto.getProductName(),
         java.time.Instant.ofEpochSecond(proto.getStartTime().getSeconds(), proto.getStartTime().getNanos()),
         java.time.Instant.ofEpochSecond(proto.getEndTime().getSeconds(), proto.getEndTime().getNanos()),
         new java.math.BigDecimal(new java.math.BigInteger(proto.getDuration().getValue().toByteArray()), proto.getDuration().getScale(), new java.math.MathContext(proto.getDuration().getPrecision())),
         proto.getDurationBasis().isEmpty() ? null : com.socotra.coremodel.DurationBasis.valueOf(proto.getDurationBasis()),
         proto.getItemsList().stream().map(f -> Charge.fromProto(f)).toList()
    );
  }

  public static QuotePricingBuilder builder() {
    return new QuotePricingBuilder();
  }


  public QuotePricingBuilder toBuilder() {
    return new QuotePricingBuilder()
       .quoteLocator(this.quoteLocator)
       .accountLocator(this.accountLocator)
       .quoteState(this.quoteState)
       .productName(this.productName)
       .startTime(this.startTime)
       .endTime(this.endTime)
       .duration(this.duration)
       .durationBasis(this.durationBasis)
       .items(this.items);
  }




  public static class QuotePricingBuilder {
    private com.socotra.platform.tools.ULID quoteLocator;
    public QuotePricingBuilder quoteLocator(com.socotra.platform.tools.ULID quoteLocator) {
      this.quoteLocator = quoteLocator;
      return this;
    }
    private com.socotra.platform.tools.ULID accountLocator;
    public QuotePricingBuilder accountLocator(com.socotra.platform.tools.ULID accountLocator) {
      this.accountLocator = accountLocator;
      return this;
    }
    private com.socotra.coremodel.QuoteState quoteState;
    public QuotePricingBuilder quoteState(com.socotra.coremodel.QuoteState quoteState) {
      this.quoteState = quoteState;
      return this;
    }
    private java.lang.String productName;
    public QuotePricingBuilder productName(java.lang.String productName) {
      this.productName = productName;
      return this;
    }
    private java.time.Instant startTime;
    public QuotePricingBuilder startTime(java.time.Instant startTime) {
      this.startTime = startTime;
      return this;
    }
    private java.time.Instant endTime;
    public QuotePricingBuilder endTime(java.time.Instant endTime) {
      this.endTime = endTime;
      return this;
    }
    private java.math.BigDecimal duration;
    public QuotePricingBuilder duration(java.math.BigDecimal duration) {
      this.duration = duration;
      return this;
    }
    private com.socotra.coremodel.DurationBasis durationBasis;
    public QuotePricingBuilder durationBasis(com.socotra.coremodel.DurationBasis durationBasis) {
      this.durationBasis = durationBasis;
      return this;
    }
    private Collection<Charge> items;
    public QuotePricingBuilder items(Collection<Charge> items) {
      this.items = items;
      return this;
    }
    public QuotePricingBuilder() {
      items = new ArrayList<>();
    }
    public QuotePricing build() {
      return new QuotePricing(
          quoteLocator,
          accountLocator,
          quoteState,
          productName,
          startTime,
          endTime,
          duration,
          durationBasis,
          items
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public QuotePricingBuilder addItem(Charge field) {
      this.items = copyIfImmutable(this.items, c -> c.add(field));
      return this;
    }
    public QuotePricingBuilder addItems(Collection<Charge> fields) {
      this.items = copyIfImmutable(this.items, c -> c.addAll(fields));
      return this;
    }
    public boolean hasItems() {
      return !this.items.isEmpty();
    }


  }
}
