/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record TaskCreateRequest(
    java.lang.String type,
    Collection<TaskReference> references,
    Collection<com.socotra.platform.tools.ULID> underwritingFlagLocators,
    Optional<java.time.Instant> deadlineTime,
    Optional<java.util.UUID> assignedTo,
    Optional<java.lang.String> description,
    Optional<com.socotra.platform.tools.ULID> workgroupToBeAssignedLocator,
    Optional<java.lang.String> source,
    Optional<java.lang.String> tag
) 
{
  public TaskCreateRequest {
    deadlineTime = deadlineTime == null ? Optional.empty() : deadlineTime;
    assignedTo = assignedTo == null ? Optional.empty() : assignedTo;
    description = description == null ? Optional.empty() : description;
    workgroupToBeAssignedLocator = workgroupToBeAssignedLocator == null ? Optional.empty() : workgroupToBeAssignedLocator;
    source = source == null ? Optional.empty() : source;
    tag = tag == null ? Optional.empty() : tag;
    references = references == null ? List.of() : List.copyOf(references);
    underwritingFlagLocators = underwritingFlagLocators == null ? List.of() : List.copyOf(underwritingFlagLocators);

    Objects.requireNonNull(type, "type is required but it is null");
    Objects.requireNonNull(deadlineTime, "deadlineTime is required but it is null");
    Objects.requireNonNull(assignedTo, "assignedTo is required but it is null");
    Objects.requireNonNull(description, "description is required but it is null");
    Objects.requireNonNull(workgroupToBeAssignedLocator, "workgroupToBeAssignedLocator is required but it is null");
    Objects.requireNonNull(source, "source is required but it is null");
    Objects.requireNonNull(tag, "tag is required but it is null");

 }

  public com.socotra.coremodel.protobuf.TaskCreateRequest toProto() {
    com.socotra.coremodel.protobuf.TaskCreateRequest.Builder builder = com.socotra.coremodel.protobuf.TaskCreateRequest.newBuilder();
    if (type != null) {
      builder.setType(this.type);
    }
    builder.addAllReferences(this.references.stream().map(f -> f.toProto()).toList());
    builder.addAllUnderwritingFlagLocators(this.underwritingFlagLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    if (deadlineTime.isPresent()) {
      builder.setDeadlineTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(deadlineTime.get().getEpochSecond()).setNanos(deadlineTime.get().getNano()).build());
    }
    if (assignedTo.isPresent()) {
      builder.setAssignedTo(com.socotra.protobuf.UUID.newBuilder().setMsb(assignedTo.get().getMostSignificantBits()).setLsb(assignedTo.get().getLeastSignificantBits()).build());
    }
    if (description.isPresent()) {
      builder.setDescription(this.description.get());
    }
    if (workgroupToBeAssignedLocator.isPresent()) {
      builder.setWorkgroupToBeAssignedLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(workgroupToBeAssignedLocator.get().getMostSignificantBits()).setLsb(workgroupToBeAssignedLocator.get().getLeastSignificantBits()).build());
    }
    if (source.isPresent()) {
      builder.setSource(this.source.get());
    }
    if (tag.isPresent()) {
      builder.setTag(this.tag.get());
    }
    return builder.build();
  }

  public TaskCreateRequest toTransport() {
    return toBuilder()
        .references(List.of())
        .underwritingFlagLocators(List.of())
        .build();
  }

  public static TaskCreateRequest fromProto(com.socotra.coremodel.protobuf.TaskCreateRequest proto) {
    return new TaskCreateRequest(
         proto.getType(),
         proto.getReferencesList().stream().map(f -> TaskReference.fromProto(f)).toList(),
         proto.getUnderwritingFlagLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.hasDeadlineTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getDeadlineTime().getSeconds(), proto.getDeadlineTime().getNanos())) : Optional.empty(),
         proto.hasAssignedTo() ? Optional.of(new java.util.UUID(proto.getAssignedTo().getMsb(), proto.getAssignedTo().getLsb())) : Optional.empty(),
         proto.hasDescription() ? Optional.of(proto.getDescription()) : Optional.empty(),
         proto.hasWorkgroupToBeAssignedLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getWorkgroupToBeAssignedLocator().getMsb(), proto.getWorkgroupToBeAssignedLocator().getLsb())) : Optional.empty(),
         proto.hasSource() ? Optional.of(proto.getSource()) : Optional.empty(),
         proto.hasTag() ? Optional.of(proto.getTag()) : Optional.empty()
    );
  }

  public static TaskCreateRequestBuilder builder() {
    return new TaskCreateRequestBuilder();
  }


  public TaskCreateRequestBuilder toBuilder() {
    return new TaskCreateRequestBuilder()
       .type(this.type)
       .references(this.references)
       .underwritingFlagLocators(this.underwritingFlagLocators)
       .deadlineTime(this.deadlineTime)
       .assignedTo(this.assignedTo)
       .description(this.description)
       .workgroupToBeAssignedLocator(this.workgroupToBeAssignedLocator)
       .source(this.source)
       .tag(this.tag);
  }




  public static class TaskCreateRequestBuilder {
    private java.lang.String type;
    public TaskCreateRequestBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private Collection<TaskReference> references;
    public TaskCreateRequestBuilder references(Collection<TaskReference> references) {
      this.references = references;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> underwritingFlagLocators;
    public TaskCreateRequestBuilder underwritingFlagLocators(Collection<com.socotra.platform.tools.ULID> underwritingFlagLocators) {
      this.underwritingFlagLocators = underwritingFlagLocators;
      return this;
    }
    private Optional<java.time.Instant> deadlineTime;
    public TaskCreateRequestBuilder deadlineTime(Optional<java.time.Instant> deadlineTime) {
      this.deadlineTime = deadlineTime;
      return this;
    }
    public TaskCreateRequestBuilder deadlineTime(java.time.Instant deadlineTime) {
      this.deadlineTime = Optional.ofNullable(deadlineTime);
      return this;
    }
    private Optional<java.util.UUID> assignedTo;
    public TaskCreateRequestBuilder assignedTo(Optional<java.util.UUID> assignedTo) {
      this.assignedTo = assignedTo;
      return this;
    }
    public TaskCreateRequestBuilder assignedTo(java.util.UUID assignedTo) {
      this.assignedTo = Optional.ofNullable(assignedTo);
      return this;
    }
    private Optional<java.lang.String> description;
    public TaskCreateRequestBuilder description(Optional<java.lang.String> description) {
      this.description = description;
      return this;
    }
    public TaskCreateRequestBuilder description(java.lang.String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> workgroupToBeAssignedLocator;
    public TaskCreateRequestBuilder workgroupToBeAssignedLocator(Optional<com.socotra.platform.tools.ULID> workgroupToBeAssignedLocator) {
      this.workgroupToBeAssignedLocator = workgroupToBeAssignedLocator;
      return this;
    }
    public TaskCreateRequestBuilder workgroupToBeAssignedLocator(com.socotra.platform.tools.ULID workgroupToBeAssignedLocator) {
      this.workgroupToBeAssignedLocator = Optional.ofNullable(workgroupToBeAssignedLocator);
      return this;
    }
    private Optional<java.lang.String> source;
    public TaskCreateRequestBuilder source(Optional<java.lang.String> source) {
      this.source = source;
      return this;
    }
    public TaskCreateRequestBuilder source(java.lang.String source) {
      this.source = Optional.ofNullable(source);
      return this;
    }
    private Optional<java.lang.String> tag;
    public TaskCreateRequestBuilder tag(Optional<java.lang.String> tag) {
      this.tag = tag;
      return this;
    }
    public TaskCreateRequestBuilder tag(java.lang.String tag) {
      this.tag = Optional.ofNullable(tag);
      return this;
    }
    public TaskCreateRequestBuilder() {
      references = new ArrayList<>();
      underwritingFlagLocators = new ArrayList<>();
    }
    public TaskCreateRequest build() {
      return new TaskCreateRequest(
          type,
          references,
          underwritingFlagLocators,
          deadlineTime,
          assignedTo,
          description,
          workgroupToBeAssignedLocator,
          source,
          tag
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public TaskCreateRequestBuilder addReference(TaskReference field) {
      this.references = copyIfImmutable(this.references, c -> c.add(field));
      return this;
    }
    public TaskCreateRequestBuilder addReferences(Collection<TaskReference> fields) {
      this.references = copyIfImmutable(this.references, c -> c.addAll(fields));
      return this;
    }
    public boolean hasReferences() {
      return !this.references.isEmpty();
    }
    public TaskCreateRequestBuilder addUnderwritingFlagLocator(com.socotra.platform.tools.ULID field) {
      this.underwritingFlagLocators = copyIfImmutable(this.underwritingFlagLocators, c -> c.add(field));
      return this;
    }
    public TaskCreateRequestBuilder addUnderwritingFlagLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.underwritingFlagLocators = copyIfImmutable(this.underwritingFlagLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasUnderwritingFlagLocators() {
      return !this.underwritingFlagLocators.isEmpty();
    }


  }
}
