/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Task(
    com.socotra.platform.tools.ULID locator,
    java.lang.String category,
    java.lang.String type,
    com.socotra.coremodel.TaskState taskState,
    Collection<TaskReference> references,
    Collection<com.socotra.platform.tools.ULID> underwritingFlagLocators,
    Optional<java.time.Instant> deadlineTime,
    Optional<java.util.UUID> assignedTo,
    java.util.UUID createdBy,
    java.time.Instant createdAt,
    Optional<java.util.UUID> updatedBy,
    Optional<java.time.Instant> updatedAt,
    Optional<java.lang.String> description,
    Optional<java.lang.String> taskNumber,
    Optional<java.time.Instant> completedAt,
    Optional<java.util.UUID> completedBy,
    Optional<java.lang.String> source,
    Optional<java.lang.String> tag
) 
{
  public Task {
    
    deadlineTime = deadlineTime == null ? Optional.empty() : deadlineTime;
    assignedTo = assignedTo == null ? Optional.empty() : assignedTo;
    updatedBy = updatedBy == null ? Optional.empty() : updatedBy;
    updatedAt = updatedAt == null ? Optional.empty() : updatedAt;
    description = description == null ? Optional.empty() : description;
    taskNumber = taskNumber == null ? Optional.empty() : taskNumber;
    completedAt = completedAt == null ? Optional.empty() : completedAt;
    completedBy = completedBy == null ? Optional.empty() : completedBy;
    source = source == null ? Optional.empty() : source;
    tag = tag == null ? Optional.empty() : tag;
    references = references == null ? List.of() : List.copyOf(references);
    underwritingFlagLocators = underwritingFlagLocators == null ? List.of() : List.copyOf(underwritingFlagLocators);
    references = Collections.unmodifiableSet(new LinkedHashSet<>(references));
    underwritingFlagLocators = Collections.unmodifiableSet(new LinkedHashSet<>(underwritingFlagLocators));
    deadlineTime = deadlineTime.map(i -> i.truncatedTo(java.time.temporal.ChronoUnit.SECONDS));
    createdAt = createdAt == null ? createdAt : createdAt.truncatedTo(java.time.temporal.ChronoUnit.SECONDS);
    updatedAt = updatedAt.map(i -> i.truncatedTo(java.time.temporal.ChronoUnit.SECONDS));
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(category, "category is required but it is null");
    Objects.requireNonNull(type, "type is required but it is null");
    Objects.requireNonNull(taskState, "taskState is required but it is null");
    Objects.requireNonNull(deadlineTime, "deadlineTime is required but it is null");
    Objects.requireNonNull(assignedTo, "assignedTo is required but it is null");
    Objects.requireNonNull(createdBy, "createdBy is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(updatedBy, "updatedBy is required but it is null");
    Objects.requireNonNull(updatedAt, "updatedAt is required but it is null");
    Objects.requireNonNull(description, "description is required but it is null");
    Objects.requireNonNull(taskNumber, "taskNumber is required but it is null");
    Objects.requireNonNull(completedAt, "completedAt is required but it is null");
    Objects.requireNonNull(completedBy, "completedBy is required but it is null");
    Objects.requireNonNull(source, "source is required but it is null");
    Objects.requireNonNull(tag, "tag is required but it is null");

 }

  public com.socotra.coremodel.protobuf.Task toProto() {
    com.socotra.coremodel.protobuf.Task.Builder builder = com.socotra.coremodel.protobuf.Task.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (category != null) {
      builder.setCategory(this.category);
    }
    if (type != null) {
      builder.setType(this.type);
    }
    if (taskState != null) {
      builder.setTaskState(this.taskState.name());
    }
    builder.addAllReferences(this.references.stream().map(f -> f.toProto()).toList());
    builder.addAllUnderwritingFlagLocators(this.underwritingFlagLocators.stream().map(f -> com.socotra.protobuf.ULID.newBuilder().setMsb(f.getMostSignificantBits()).setLsb(f.getLeastSignificantBits()).build()).toList());
    if (deadlineTime.isPresent()) {
      builder.setDeadlineTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(deadlineTime.get().getEpochSecond()).setNanos(deadlineTime.get().getNano()).build());
    }
    if (assignedTo.isPresent()) {
      builder.setAssignedTo(com.socotra.protobuf.UUID.newBuilder().setMsb(assignedTo.get().getMostSignificantBits()).setLsb(assignedTo.get().getLeastSignificantBits()).build());
    }
    if (createdBy != null) {
      builder.setCreatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(createdBy.getMostSignificantBits()).setLsb(createdBy.getLeastSignificantBits()).build());
    }
    if (createdAt != null) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.getEpochSecond()).setNanos(createdAt.getNano()).build());
    }
    if (updatedBy.isPresent()) {
      builder.setUpdatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(updatedBy.get().getMostSignificantBits()).setLsb(updatedBy.get().getLeastSignificantBits()).build());
    }
    if (updatedAt.isPresent()) {
      builder.setUpdatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(updatedAt.get().getEpochSecond()).setNanos(updatedAt.get().getNano()).build());
    }
    if (description.isPresent()) {
      builder.setDescription(this.description.get());
    }
    if (taskNumber.isPresent()) {
      builder.setTaskNumber(this.taskNumber.get());
    }
    if (completedAt.isPresent()) {
      builder.setCompletedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(completedAt.get().getEpochSecond()).setNanos(completedAt.get().getNano()).build());
    }
    if (completedBy.isPresent()) {
      builder.setCompletedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(completedBy.get().getMostSignificantBits()).setLsb(completedBy.get().getLeastSignificantBits()).build());
    }
    if (source.isPresent()) {
      builder.setSource(this.source.get());
    }
    if (tag.isPresent()) {
      builder.setTag(this.tag.get());
    }
    return builder.build();
  }

  public Task toTransport() {
    return toBuilder()
        .references(List.of())
        .underwritingFlagLocators(List.of())
        .build();
  }

  public static Task fromProto(com.socotra.coremodel.protobuf.Task proto) {
    return new Task(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getCategory(),
         proto.getType(),
         proto.getTaskState().isEmpty() ? null : com.socotra.coremodel.TaskState.valueOf(proto.getTaskState()),
         proto.getReferencesList().stream().map(f -> TaskReference.fromProto(f)).toList(),
         proto.getUnderwritingFlagLocatorsList().stream().map(f -> new com.socotra.platform.tools.ULID(f.getMsb(), f.getLsb())).toList(),
         proto.hasDeadlineTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getDeadlineTime().getSeconds(), proto.getDeadlineTime().getNanos())) : Optional.empty(),
         proto.hasAssignedTo() ? Optional.of(new java.util.UUID(proto.getAssignedTo().getMsb(), proto.getAssignedTo().getLsb())) : Optional.empty(),
         new java.util.UUID(proto.getCreatedBy().getMsb(), proto.getCreatedBy().getLsb()),
         java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos()),
         proto.hasUpdatedBy() ? Optional.of(new java.util.UUID(proto.getUpdatedBy().getMsb(), proto.getUpdatedBy().getLsb())) : Optional.empty(),
         proto.hasUpdatedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getUpdatedAt().getSeconds(), proto.getUpdatedAt().getNanos())) : Optional.empty(),
         proto.hasDescription() ? Optional.of(proto.getDescription()) : Optional.empty(),
         proto.hasTaskNumber() ? Optional.of(proto.getTaskNumber()) : Optional.empty(),
         proto.hasCompletedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getCompletedAt().getSeconds(), proto.getCompletedAt().getNanos())) : Optional.empty(),
         proto.hasCompletedBy() ? Optional.of(new java.util.UUID(proto.getCompletedBy().getMsb(), proto.getCompletedBy().getLsb())) : Optional.empty(),
         proto.hasSource() ? Optional.of(proto.getSource()) : Optional.empty(),
         proto.hasTag() ? Optional.of(proto.getTag()) : Optional.empty()
    );
  }

  public static TaskBuilder builder() {
    return new TaskBuilder();
  }


  public TaskBuilder toBuilder() {
    return new TaskBuilder()
       .locator(this.locator)
       .category(this.category)
       .type(this.type)
       .taskState(this.taskState)
       .references(this.references)
       .underwritingFlagLocators(this.underwritingFlagLocators)
       .deadlineTime(this.deadlineTime)
       .assignedTo(this.assignedTo)
       .createdBy(this.createdBy)
       .createdAt(this.createdAt)
       .updatedBy(this.updatedBy)
       .updatedAt(this.updatedAt)
       .description(this.description)
       .taskNumber(this.taskNumber)
       .completedAt(this.completedAt)
       .completedBy(this.completedBy)
       .source(this.source)
       .tag(this.tag);
  }




  public static class TaskBuilder {
    private com.socotra.platform.tools.ULID locator;
    public TaskBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private java.lang.String category;
    public TaskBuilder category(java.lang.String category) {
      this.category = category;
      return this;
    }
    private java.lang.String type;
    public TaskBuilder type(java.lang.String type) {
      this.type = type;
      return this;
    }
    private com.socotra.coremodel.TaskState taskState;
    public TaskBuilder taskState(com.socotra.coremodel.TaskState taskState) {
      this.taskState = taskState;
      return this;
    }
    private Collection<TaskReference> references;
    public TaskBuilder references(Collection<TaskReference> references) {
      this.references = references;
      return this;
    }
    private Collection<com.socotra.platform.tools.ULID> underwritingFlagLocators;
    public TaskBuilder underwritingFlagLocators(Collection<com.socotra.platform.tools.ULID> underwritingFlagLocators) {
      this.underwritingFlagLocators = underwritingFlagLocators;
      return this;
    }
    private Optional<java.time.Instant> deadlineTime;
    public TaskBuilder deadlineTime(Optional<java.time.Instant> deadlineTime) {
      this.deadlineTime = deadlineTime;
      return this;
    }
    public TaskBuilder deadlineTime(java.time.Instant deadlineTime) {
      this.deadlineTime = Optional.ofNullable(deadlineTime);
      return this;
    }
    private Optional<java.util.UUID> assignedTo;
    public TaskBuilder assignedTo(Optional<java.util.UUID> assignedTo) {
      this.assignedTo = assignedTo;
      return this;
    }
    public TaskBuilder assignedTo(java.util.UUID assignedTo) {
      this.assignedTo = Optional.ofNullable(assignedTo);
      return this;
    }
    private java.util.UUID createdBy;
    public TaskBuilder createdBy(java.util.UUID createdBy) {
      this.createdBy = createdBy;
      return this;
    }
    private java.time.Instant createdAt;
    public TaskBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    private Optional<java.util.UUID> updatedBy;
    public TaskBuilder updatedBy(Optional<java.util.UUID> updatedBy) {
      this.updatedBy = updatedBy;
      return this;
    }
    public TaskBuilder updatedBy(java.util.UUID updatedBy) {
      this.updatedBy = Optional.ofNullable(updatedBy);
      return this;
    }
    private Optional<java.time.Instant> updatedAt;
    public TaskBuilder updatedAt(Optional<java.time.Instant> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }
    public TaskBuilder updatedAt(java.time.Instant updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }
    private Optional<java.lang.String> description;
    public TaskBuilder description(Optional<java.lang.String> description) {
      this.description = description;
      return this;
    }
    public TaskBuilder description(java.lang.String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }
    private Optional<java.lang.String> taskNumber;
    public TaskBuilder taskNumber(Optional<java.lang.String> taskNumber) {
      this.taskNumber = taskNumber;
      return this;
    }
    public TaskBuilder taskNumber(java.lang.String taskNumber) {
      this.taskNumber = Optional.ofNullable(taskNumber);
      return this;
    }
    private Optional<java.time.Instant> completedAt;
    public TaskBuilder completedAt(Optional<java.time.Instant> completedAt) {
      this.completedAt = completedAt;
      return this;
    }
    public TaskBuilder completedAt(java.time.Instant completedAt) {
      this.completedAt = Optional.ofNullable(completedAt);
      return this;
    }
    private Optional<java.util.UUID> completedBy;
    public TaskBuilder completedBy(Optional<java.util.UUID> completedBy) {
      this.completedBy = completedBy;
      return this;
    }
    public TaskBuilder completedBy(java.util.UUID completedBy) {
      this.completedBy = Optional.ofNullable(completedBy);
      return this;
    }
    private Optional<java.lang.String> source;
    public TaskBuilder source(Optional<java.lang.String> source) {
      this.source = source;
      return this;
    }
    public TaskBuilder source(java.lang.String source) {
      this.source = Optional.ofNullable(source);
      return this;
    }
    private Optional<java.lang.String> tag;
    public TaskBuilder tag(Optional<java.lang.String> tag) {
      this.tag = tag;
      return this;
    }
    public TaskBuilder tag(java.lang.String tag) {
      this.tag = Optional.ofNullable(tag);
      return this;
    }
    public TaskBuilder() {
      references = new ArrayList<>();
      underwritingFlagLocators = new ArrayList<>();
    }
    public Task build() {
      return new Task(
          locator,
          category,
          type,
          taskState,
          references,
          underwritingFlagLocators,
          deadlineTime,
          assignedTo,
          createdBy,
          createdAt,
          updatedBy,
          updatedAt,
          description,
          taskNumber,
          completedAt,
          completedBy,
          source,
          tag
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public TaskBuilder addReference(TaskReference field) {
      this.references = copyIfImmutable(this.references, c -> c.add(field));
      return this;
    }
    public TaskBuilder addReferences(Collection<TaskReference> fields) {
      this.references = copyIfImmutable(this.references, c -> c.addAll(fields));
      return this;
    }
    public boolean hasReferences() {
      return !this.references.isEmpty();
    }
    public TaskBuilder addUnderwritingFlagLocator(com.socotra.platform.tools.ULID field) {
      this.underwritingFlagLocators = copyIfImmutable(this.underwritingFlagLocators, c -> c.add(field));
      return this;
    }
    public TaskBuilder addUnderwritingFlagLocators(Collection<com.socotra.platform.tools.ULID> fields) {
      this.underwritingFlagLocators = copyIfImmutable(this.underwritingFlagLocators, c -> c.addAll(fields));
      return this;
    }
    public boolean hasUnderwritingFlagLocators() {
      return !this.underwritingFlagLocators.isEmpty();
    }


  }
}
