/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record TaskCreateResponse(
    com.socotra.platform.tools.ULID locator
) 
{
  public TaskCreateResponse {

    Objects.requireNonNull(locator, "locator is required but it is null");

 }

  public com.socotra.coremodel.protobuf.TaskCreateResponse toProto() {
    com.socotra.coremodel.protobuf.TaskCreateResponse.Builder builder = com.socotra.coremodel.protobuf.TaskCreateResponse.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    return builder.build();
  }

  public TaskCreateResponse toTransport() {
    return toBuilder()
        .build();
  }

  public static TaskCreateResponse fromProto(com.socotra.coremodel.protobuf.TaskCreateResponse proto) {
    return new TaskCreateResponse(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb())
    );
  }

  public static TaskCreateResponseBuilder builder() {
    return new TaskCreateResponseBuilder();
  }


  public TaskCreateResponseBuilder toBuilder() {
    return new TaskCreateResponseBuilder()
       .locator(this.locator);
  }




  public static class TaskCreateResponseBuilder {
    private com.socotra.platform.tools.ULID locator;
    public TaskCreateResponseBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    public TaskCreateResponseBuilder() {
    }
    public TaskCreateResponse build() {
      return new TaskCreateResponse(
          locator
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
