/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record TemplateSnippetConfig(
    java.lang.String name,
    com.socotra.coremodel.SelectionTimeBasis selectionTimeBasis
)  implements com.socotra.coremodel.interfaces.TemplateSnippetConfig
{
  public TemplateSnippetConfig {
    selectionTimeBasis = selectionTimeBasis == null ? com.socotra.coremodel.SelectionTimeBasis.currentTime : selectionTimeBasis;


    Objects.requireNonNull(name, "name is required but it is null");
    Objects.requireNonNull(selectionTimeBasis, "selectionTimeBasis is required but it is null");

 }

  public com.socotra.coremodel.protobuf.TemplateSnippetConfig toProto() {
    com.socotra.coremodel.protobuf.TemplateSnippetConfig.Builder builder = com.socotra.coremodel.protobuf.TemplateSnippetConfig.newBuilder();
    if (name != null) {
      builder.setName(this.name);
    }
    if (selectionTimeBasis != null) {
      builder.setSelectionTimeBasis(this.selectionTimeBasis.name());
    }
    return builder.build();
  }

  public TemplateSnippetConfig toTransport() {
    return toBuilder()
        .build();
  }

  public static TemplateSnippetConfig fromProto(com.socotra.coremodel.protobuf.TemplateSnippetConfig proto) {
    return new TemplateSnippetConfig(
         proto.getName(),
         proto.getSelectionTimeBasis().isEmpty() ? null : com.socotra.coremodel.SelectionTimeBasis.valueOf(proto.getSelectionTimeBasis())
    );
  }

  public static TemplateSnippetConfigBuilder builder() {
    return new TemplateSnippetConfigBuilder();
  }

  public static TemplateSnippetConfig copyFrom(com.socotra.coremodel.interfaces.TemplateSnippetConfig other) {
    return new TemplateSnippetConfig(
        other.name(),
        other.selectionTimeBasis()
    );
  }

  public TemplateSnippetConfigBuilder toBuilder() {
    return new TemplateSnippetConfigBuilder()
       .name(this.name)
       .selectionTimeBasis(this.selectionTimeBasis);
  }




  public static class TemplateSnippetConfigBuilder {
    private java.lang.String name;
    public TemplateSnippetConfigBuilder name(java.lang.String name) {
      this.name = name;
      return this;
    }
    private com.socotra.coremodel.SelectionTimeBasis selectionTimeBasis;
    public TemplateSnippetConfigBuilder selectionTimeBasis(com.socotra.coremodel.SelectionTimeBasis selectionTimeBasis) {
      this.selectionTimeBasis = selectionTimeBasis;
      return this;
    }
    public TemplateSnippetConfigBuilder() {
    }
    public TemplateSnippetConfig build() {
      return new TemplateSnippetConfig(
          name,
          selectionTimeBasis
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
