/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record Transaction(
    com.socotra.platform.tools.ULID locator,
    com.socotra.coremodel.TransactionCategory transactionCategory,
    com.socotra.coremodel.TransactionState transactionState,
    Optional<java.lang.String> underwritingStatus,
    com.socotra.platform.tools.ULID policyLocator,
    Optional<com.socotra.platform.tools.ULID> baseTransactionLocator,
    Optional<com.socotra.platform.tools.ULID> aggregateTransactionLocator,
    java.time.Instant createdAt,
    java.util.UUID createdBy,
    Optional<ValidationResult> validationResult,
    Collection<java.lang.Object> changeInstructions,
    java.time.Instant effectiveTime,
    Collection<Transaction> aggregatedTransactions,
    com.socotra.platform.tools.ULID termLocator,
    Optional<Preferences> preferences,
    java.lang.String transactionType,
    Optional<java.time.Instant> issuedTime,
    Optional<java.time.Instant> acceptedTime,
    Optional<com.socotra.platform.tools.ULID> reapplicationOfLocator,
    Optional<com.socotra.coremodel.DataMaskingLevel> maskingLevel,
    Optional<java.time.Instant> anonymizedAt,
    com.socotra.platform.tools.ULID staticLocator
)  implements com.socotra.coremodel.SensitiveObject
{
  public Transaction {
    
    
    underwritingStatus = underwritingStatus == null ? Optional.empty() : underwritingStatus;
    baseTransactionLocator = baseTransactionLocator == null ? Optional.empty() : baseTransactionLocator;
    aggregateTransactionLocator = aggregateTransactionLocator == null ? Optional.empty() : aggregateTransactionLocator;
    validationResult = validationResult == null ? Optional.empty() : validationResult;
    preferences = preferences == null ? Optional.empty() : preferences;
    issuedTime = issuedTime == null ? Optional.empty() : issuedTime;
    acceptedTime = acceptedTime == null ? Optional.empty() : acceptedTime;
    reapplicationOfLocator = reapplicationOfLocator == null ? Optional.empty() : reapplicationOfLocator;
    maskingLevel = maskingLevel == null ? Optional.empty() : maskingLevel;

    anonymizedAt = anonymizedAt == null ? Optional.empty() : anonymizedAt;
    changeInstructions = changeInstructions == null ? List.of() : List.copyOf(changeInstructions);
    aggregatedTransactions = aggregatedTransactions == null ? List.of() : List.copyOf(aggregatedTransactions);
    if(staticLocator == null) {
      staticLocator = locator;
    }
    if(transactionType == null)  {
      transactionType = transactionCategory.name();
    }
    if(effectiveTime != null) {
      effectiveTime = effectiveTime.truncatedTo(java.time.temporal.ChronoUnit.SECONDS);
    }
    baseTransactionLocator.filter(locator::equals).ifPresent(b -> {
      throw new IllegalArgumentException("baseTransactionLocator can not be equal to locator");
    });
    if(transactionCategory == TransactionCategory.issuance) {
      if(baseTransactionLocator.isPresent()) {
        throw new IllegalArgumentException(transactionCategory.name() + " must not have baseTransactionLocator");
      }
    } else if(baseTransactionLocator.isEmpty()) {
      throw new IllegalArgumentException("baseTransactionLocator is required for " + transactionCategory.name());
    }
    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(transactionCategory, "transactionCategory is required but it is null");
    Objects.requireNonNull(transactionState, "transactionState is required but it is null");
    Objects.requireNonNull(underwritingStatus, "underwritingStatus is required but it is null");
    Objects.requireNonNull(policyLocator, "policyLocator is required but it is null");
    Objects.requireNonNull(baseTransactionLocator, "baseTransactionLocator is required but it is null");
    Objects.requireNonNull(aggregateTransactionLocator, "aggregateTransactionLocator is required but it is null");
    Objects.requireNonNull(createdAt, "createdAt is required but it is null");
    Objects.requireNonNull(createdBy, "createdBy is required but it is null");
    Objects.requireNonNull(validationResult, "validationResult is required but it is null");
    Objects.requireNonNull(effectiveTime, "effectiveTime is required but it is null");
    Objects.requireNonNull(termLocator, "termLocator is required but it is null");
    Objects.requireNonNull(preferences, "preferences is required but it is null");
    Objects.requireNonNull(transactionType, "transactionType is required but it is null");
    Objects.requireNonNull(issuedTime, "issuedTime is required but it is null");
    Objects.requireNonNull(acceptedTime, "acceptedTime is required but it is null");
    Objects.requireNonNull(reapplicationOfLocator, "reapplicationOfLocator is required but it is null");
    Objects.requireNonNull(maskingLevel, "maskingLevel is required but it is null");
    Objects.requireNonNull(anonymizedAt, "anonymizedAt is required but it is null");
    Objects.requireNonNull(staticLocator, "staticLocator is required but it is null");

 }

  public com.socotra.coremodel.protobuf.Transaction toProto() {
    com.socotra.coremodel.protobuf.Transaction.Builder builder = com.socotra.coremodel.protobuf.Transaction.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (transactionCategory != null) {
      builder.setTransactionCategory(this.transactionCategory.name());
    }
    if (transactionState != null) {
      builder.setTransactionState(this.transactionState.name());
    }
    if (underwritingStatus.isPresent()) {
      builder.setUnderwritingStatus(this.underwritingStatus.get());
    }
    if (policyLocator != null) {
      builder.setPolicyLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(policyLocator.getMostSignificantBits()).setLsb(policyLocator.getLeastSignificantBits()).build());
    }
    if (baseTransactionLocator.isPresent()) {
      builder.setBaseTransactionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(baseTransactionLocator.get().getMostSignificantBits()).setLsb(baseTransactionLocator.get().getLeastSignificantBits()).build());
    }
    if (aggregateTransactionLocator.isPresent()) {
      builder.setAggregateTransactionLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(aggregateTransactionLocator.get().getMostSignificantBits()).setLsb(aggregateTransactionLocator.get().getLeastSignificantBits()).build());
    }
    if (createdAt != null) {
      builder.setCreatedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(createdAt.getEpochSecond()).setNanos(createdAt.getNano()).build());
    }
    if (createdBy != null) {
      builder.setCreatedBy(com.socotra.protobuf.UUID.newBuilder().setMsb(createdBy.getMostSignificantBits()).setLsb(createdBy.getLeastSignificantBits()).build());
    }
    if (validationResult.isPresent()) {
      builder.setValidationResult(validationResult.get().toProto());
    }
    builder.addAllChangeInstructions(this.changeInstructions.stream().map(e -> com.socotra.protobuf.Object.newBuilder().setType(e.getClass().getName()).setData(MarshallerFactory.getFor(e.getClass()).write(e)).build()).toList());
    if (effectiveTime != null) {
      builder.setEffectiveTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(effectiveTime.getEpochSecond()).setNanos(effectiveTime.getNano()).build());
    }
    builder.addAllAggregatedTransactions(this.aggregatedTransactions.stream().map(f -> f.toProto()).toList());
    if (termLocator != null) {
      builder.setTermLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(termLocator.getMostSignificantBits()).setLsb(termLocator.getLeastSignificantBits()).build());
    }
    if (preferences.isPresent()) {
      builder.setPreferences(preferences.get().toProto());
    }
    if (transactionType != null) {
      builder.setTransactionType(this.transactionType);
    }
    if (issuedTime.isPresent()) {
      builder.setIssuedTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(issuedTime.get().getEpochSecond()).setNanos(issuedTime.get().getNano()).build());
    }
    if (acceptedTime.isPresent()) {
      builder.setAcceptedTime(com.google.protobuf.Timestamp.newBuilder().setSeconds(acceptedTime.get().getEpochSecond()).setNanos(acceptedTime.get().getNano()).build());
    }
    if (reapplicationOfLocator.isPresent()) {
      builder.setReapplicationOfLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(reapplicationOfLocator.get().getMostSignificantBits()).setLsb(reapplicationOfLocator.get().getLeastSignificantBits()).build());
    }
    if (maskingLevel.isPresent()) {
      builder.setMaskingLevel(this.maskingLevel.get().name());
    }
    if (anonymizedAt.isPresent()) {
      builder.setAnonymizedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(anonymizedAt.get().getEpochSecond()).setNanos(anonymizedAt.get().getNano()).build());
    }
    if (staticLocator != null) {
      builder.setStaticLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(staticLocator.getMostSignificantBits()).setLsb(staticLocator.getLeastSignificantBits()).build());
    }
    return builder.build();
  }

  public Transaction toTransport() {
    return toBuilder()
        .changeInstructions(List.of())
        .aggregatedTransactions(List.of())
        .build();
  }

  public static Transaction fromProto(com.socotra.coremodel.protobuf.Transaction proto) {
    return new Transaction(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getTransactionCategory().isEmpty() ? null : com.socotra.coremodel.TransactionCategory.valueOf(proto.getTransactionCategory()),
         proto.getTransactionState().isEmpty() ? null : com.socotra.coremodel.TransactionState.valueOf(proto.getTransactionState()),
         proto.hasUnderwritingStatus() ? Optional.of(proto.getUnderwritingStatus()) : Optional.empty(),
         new com.socotra.platform.tools.ULID(proto.getPolicyLocator().getMsb(), proto.getPolicyLocator().getLsb()),
         proto.hasBaseTransactionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getBaseTransactionLocator().getMsb(), proto.getBaseTransactionLocator().getLsb())) : Optional.empty(),
         proto.hasAggregateTransactionLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getAggregateTransactionLocator().getMsb(), proto.getAggregateTransactionLocator().getLsb())) : Optional.empty(),
         java.time.Instant.ofEpochSecond(proto.getCreatedAt().getSeconds(), proto.getCreatedAt().getNanos()),
         new java.util.UUID(proto.getCreatedBy().getMsb(), proto.getCreatedBy().getLsb()),
         proto.hasValidationResult() ? Optional.of(ValidationResult.fromProto(proto.getValidationResult())) : Optional.empty(),
         proto.getChangeInstructionsList().stream().map(e -> ((java.lang.Object)MarshallerFactory.getFor(java.lang.Object.class).read(e.getData()))).toList(),
         java.time.Instant.ofEpochSecond(proto.getEffectiveTime().getSeconds(), proto.getEffectiveTime().getNanos()),
         proto.getAggregatedTransactionsList().stream().map(f -> Transaction.fromProto(f)).toList(),
         new com.socotra.platform.tools.ULID(proto.getTermLocator().getMsb(), proto.getTermLocator().getLsb()),
         proto.hasPreferences() ? Optional.of(Preferences.fromProto(proto.getPreferences())) : Optional.empty(),
         proto.getTransactionType(),
         proto.hasIssuedTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getIssuedTime().getSeconds(), proto.getIssuedTime().getNanos())) : Optional.empty(),
         proto.hasAcceptedTime() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAcceptedTime().getSeconds(), proto.getAcceptedTime().getNanos())) : Optional.empty(),
         proto.hasReapplicationOfLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getReapplicationOfLocator().getMsb(), proto.getReapplicationOfLocator().getLsb())) : Optional.empty(),
         proto.hasMaskingLevel() ? Optional.of(proto.getMaskingLevel().isEmpty() ? null : com.socotra.coremodel.DataMaskingLevel.valueOf(proto.getMaskingLevel())) : Optional.empty(),
         proto.hasAnonymizedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getAnonymizedAt().getSeconds(), proto.getAnonymizedAt().getNanos())) : Optional.empty(),
         new com.socotra.platform.tools.ULID(proto.getStaticLocator().getMsb(), proto.getStaticLocator().getLsb())
    );
  }

  public static TransactionBuilder builder() {
    return new TransactionBuilder();
  }


  public TransactionBuilder toBuilder() {
    return new TransactionBuilder()
       .locator(this.locator)
       .transactionCategory(this.transactionCategory)
       .transactionState(this.transactionState)
       .underwritingStatus(this.underwritingStatus)
       .policyLocator(this.policyLocator)
       .baseTransactionLocator(this.baseTransactionLocator)
       .aggregateTransactionLocator(this.aggregateTransactionLocator)
       .createdAt(this.createdAt)
       .createdBy(this.createdBy)
       .validationResult(this.validationResult)
       .changeInstructions(this.changeInstructions)
       .effectiveTime(this.effectiveTime)
       .aggregatedTransactions(this.aggregatedTransactions)
       .termLocator(this.termLocator)
       .preferences(this.preferences)
       .transactionType(this.transactionType)
       .issuedTime(this.issuedTime)
       .acceptedTime(this.acceptedTime)
       .reapplicationOfLocator(this.reapplicationOfLocator)
       .maskingLevel(this.maskingLevel)
       .anonymizedAt(this.anonymizedAt)
       .staticLocator(this.staticLocator);
  }


  @Override
  public Transaction maskData(DataMaskingLevel level) {
    if (this.aggregatedTransactions() != null && !this.aggregatedTransactions().isEmpty()) {
        // Aggregated transaction has maskingLevel=none always
        return toBuilder()
            .aggregatedTransactions(
                aggregatedTransactions().stream()
                    .map(t -> t.maskData(level))
                    .collect(Collectors.toList()))
            .changeInstructions(changeInstructions().stream()
              .map(c -> (java.lang.Object) ((TransactionChangeInstruction) c).metadata())
              .toList())
            .build();
    }

    if (level.compareTo(this.maskingLevel().orElse(DataMaskingLevel.none)) < 0) {
      return toBuilder()
          .changeInstructions(
              changeInstructions().stream()
                  .map(c -> (java.lang.Object) ((TransactionChangeInstruction) c).metadata())
                  .toList())
          .build();
    }
    return this;
  }

  public static class TransactionBuilder {
    private com.socotra.platform.tools.ULID locator;
    public TransactionBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.coremodel.TransactionCategory transactionCategory;
    public TransactionBuilder transactionCategory(com.socotra.coremodel.TransactionCategory transactionCategory) {
      this.transactionCategory = transactionCategory;
      return this;
    }
    private com.socotra.coremodel.TransactionState transactionState;
    public TransactionBuilder transactionState(com.socotra.coremodel.TransactionState transactionState) {
      this.transactionState = transactionState;
      return this;
    }
    private Optional<java.lang.String> underwritingStatus;
    public TransactionBuilder underwritingStatus(Optional<java.lang.String> underwritingStatus) {
      this.underwritingStatus = underwritingStatus;
      return this;
    }
    public TransactionBuilder underwritingStatus(java.lang.String underwritingStatus) {
      this.underwritingStatus = Optional.ofNullable(underwritingStatus);
      return this;
    }
    private com.socotra.platform.tools.ULID policyLocator;
    public TransactionBuilder policyLocator(com.socotra.platform.tools.ULID policyLocator) {
      this.policyLocator = policyLocator;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> baseTransactionLocator;
    public TransactionBuilder baseTransactionLocator(Optional<com.socotra.platform.tools.ULID> baseTransactionLocator) {
      this.baseTransactionLocator = baseTransactionLocator;
      return this;
    }
    public TransactionBuilder baseTransactionLocator(com.socotra.platform.tools.ULID baseTransactionLocator) {
      this.baseTransactionLocator = Optional.ofNullable(baseTransactionLocator);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> aggregateTransactionLocator;
    public TransactionBuilder aggregateTransactionLocator(Optional<com.socotra.platform.tools.ULID> aggregateTransactionLocator) {
      this.aggregateTransactionLocator = aggregateTransactionLocator;
      return this;
    }
    public TransactionBuilder aggregateTransactionLocator(com.socotra.platform.tools.ULID aggregateTransactionLocator) {
      this.aggregateTransactionLocator = Optional.ofNullable(aggregateTransactionLocator);
      return this;
    }
    private java.time.Instant createdAt;
    public TransactionBuilder createdAt(java.time.Instant createdAt) {
      this.createdAt = createdAt;
      return this;
    }
    private java.util.UUID createdBy;
    public TransactionBuilder createdBy(java.util.UUID createdBy) {
      this.createdBy = createdBy;
      return this;
    }
    private Optional<ValidationResult> validationResult;
    public TransactionBuilder validationResult(Optional<ValidationResult> validationResult) {
      this.validationResult = validationResult;
      return this;
    }
    public TransactionBuilder validationResult(ValidationResult validationResult) {
      this.validationResult = Optional.ofNullable(validationResult);
      return this;
    }
    private Collection<java.lang.Object> changeInstructions;
    public TransactionBuilder changeInstructions(Collection<java.lang.Object> changeInstructions) {
      this.changeInstructions = changeInstructions;
      return this;
    }
    private java.time.Instant effectiveTime;
    public TransactionBuilder effectiveTime(java.time.Instant effectiveTime) {
      this.effectiveTime = effectiveTime;
      return this;
    }
    private Collection<Transaction> aggregatedTransactions;
    public TransactionBuilder aggregatedTransactions(Collection<Transaction> aggregatedTransactions) {
      this.aggregatedTransactions = aggregatedTransactions;
      return this;
    }
    private com.socotra.platform.tools.ULID termLocator;
    public TransactionBuilder termLocator(com.socotra.platform.tools.ULID termLocator) {
      this.termLocator = termLocator;
      return this;
    }
    private Optional<Preferences> preferences;
    public TransactionBuilder preferences(Optional<Preferences> preferences) {
      this.preferences = preferences;
      return this;
    }
    public TransactionBuilder preferences(Preferences preferences) {
      this.preferences = Optional.ofNullable(preferences);
      return this;
    }
    private java.lang.String transactionType;
    public TransactionBuilder transactionType(java.lang.String transactionType) {
      this.transactionType = transactionType;
      return this;
    }
    private Optional<java.time.Instant> issuedTime;
    public TransactionBuilder issuedTime(Optional<java.time.Instant> issuedTime) {
      this.issuedTime = issuedTime;
      return this;
    }
    public TransactionBuilder issuedTime(java.time.Instant issuedTime) {
      this.issuedTime = Optional.ofNullable(issuedTime);
      return this;
    }
    private Optional<java.time.Instant> acceptedTime;
    public TransactionBuilder acceptedTime(Optional<java.time.Instant> acceptedTime) {
      this.acceptedTime = acceptedTime;
      return this;
    }
    public TransactionBuilder acceptedTime(java.time.Instant acceptedTime) {
      this.acceptedTime = Optional.ofNullable(acceptedTime);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> reapplicationOfLocator;
    public TransactionBuilder reapplicationOfLocator(Optional<com.socotra.platform.tools.ULID> reapplicationOfLocator) {
      this.reapplicationOfLocator = reapplicationOfLocator;
      return this;
    }
    public TransactionBuilder reapplicationOfLocator(com.socotra.platform.tools.ULID reapplicationOfLocator) {
      this.reapplicationOfLocator = Optional.ofNullable(reapplicationOfLocator);
      return this;
    }
    private Optional<com.socotra.coremodel.DataMaskingLevel> maskingLevel;
    public TransactionBuilder maskingLevel(Optional<com.socotra.coremodel.DataMaskingLevel> maskingLevel) {
      this.maskingLevel = maskingLevel;
      return this;
    }
    public TransactionBuilder maskingLevel(com.socotra.coremodel.DataMaskingLevel maskingLevel) {
      this.maskingLevel = Optional.ofNullable(maskingLevel);
      return this;
    }
    private Optional<java.time.Instant> anonymizedAt;
    public TransactionBuilder anonymizedAt(Optional<java.time.Instant> anonymizedAt) {
      this.anonymizedAt = anonymizedAt;
      return this;
    }
    public TransactionBuilder anonymizedAt(java.time.Instant anonymizedAt) {
      this.anonymizedAt = Optional.ofNullable(anonymizedAt);
      return this;
    }
    private com.socotra.platform.tools.ULID staticLocator;
    public TransactionBuilder staticLocator(com.socotra.platform.tools.ULID staticLocator) {
      this.staticLocator = staticLocator;
      return this;
    }
    public TransactionBuilder() {
      changeInstructions = new ArrayList<>();
      aggregatedTransactions = new ArrayList<>();
    }
    public Transaction build() {
      return new Transaction(
          locator,
          transactionCategory,
          transactionState,
          underwritingStatus,
          policyLocator,
          baseTransactionLocator,
          aggregateTransactionLocator,
          createdAt,
          createdBy,
          validationResult,
          changeInstructions,
          effectiveTime,
          aggregatedTransactions,
          termLocator,
          preferences,
          transactionType,
          issuedTime,
          acceptedTime,
          reapplicationOfLocator,
          maskingLevel,
          anonymizedAt,
          staticLocator
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public TransactionBuilder addChangeInstruction(java.lang.Object field) {
      this.changeInstructions = copyIfImmutable(this.changeInstructions, c -> c.add(field));
      return this;
    }
    public TransactionBuilder addChangeInstructions(Collection<java.lang.Object> fields) {
      this.changeInstructions = copyIfImmutable(this.changeInstructions, c -> c.addAll(fields));
      return this;
    }
    public boolean hasChangeInstructions() {
      return !this.changeInstructions.isEmpty();
    }
    public TransactionBuilder addAggregatedTransaction(Transaction field) {
      this.aggregatedTransactions = copyIfImmutable(this.aggregatedTransactions, c -> c.add(field));
      return this;
    }
    public TransactionBuilder addAggregatedTransactions(Collection<Transaction> fields) {
      this.aggregatedTransactions = copyIfImmutable(this.aggregatedTransactions, c -> c.addAll(fields));
      return this;
    }
    public boolean hasAggregatedTransactions() {
      return !this.aggregatedTransactions.isEmpty();
    }


  }
}
