/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record UnderwritingFlag(
    com.socotra.platform.tools.ULID locator,
    com.socotra.coremodel.UnderwritingLevel level,
    Optional<java.lang.String> note,
    Optional<com.socotra.platform.tools.ULID> elementLocator,
    com.socotra.coremodel.UnderwritingReferenceType referenceType,
    com.socotra.platform.tools.ULID referenceLocator,
    Optional<java.time.Instant> clearedAt,
    Optional<java.lang.String> tag
) 
{
  public UnderwritingFlag {
    
    note = note == null ? Optional.empty() : note;
    elementLocator = elementLocator == null ? Optional.empty() : elementLocator;
    
    clearedAt = clearedAt == null ? Optional.empty() : clearedAt;
    tag = tag == null ? Optional.empty() : tag;

    Objects.requireNonNull(locator, "locator is required but it is null");
    Objects.requireNonNull(level, "level is required but it is null");
    Objects.requireNonNull(note, "note is required but it is null");
    Objects.requireNonNull(elementLocator, "elementLocator is required but it is null");
    Objects.requireNonNull(referenceType, "referenceType is required but it is null");
    Objects.requireNonNull(referenceLocator, "referenceLocator is required but it is null");
    Objects.requireNonNull(clearedAt, "clearedAt is required but it is null");
    Objects.requireNonNull(tag, "tag is required but it is null");

 }

  public com.socotra.coremodel.protobuf.UnderwritingFlag toProto() {
    com.socotra.coremodel.protobuf.UnderwritingFlag.Builder builder = com.socotra.coremodel.protobuf.UnderwritingFlag.newBuilder();
    if (locator != null) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.getMostSignificantBits()).setLsb(locator.getLeastSignificantBits()).build());
    }
    if (level != null) {
      builder.setLevel(this.level.name());
    }
    if (note.isPresent()) {
      builder.setNote(this.note.get());
    }
    if (elementLocator.isPresent()) {
      builder.setElementLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(elementLocator.get().getMostSignificantBits()).setLsb(elementLocator.get().getLeastSignificantBits()).build());
    }
    if (referenceType != null) {
      builder.setReferenceType(this.referenceType.name());
    }
    if (referenceLocator != null) {
      builder.setReferenceLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(referenceLocator.getMostSignificantBits()).setLsb(referenceLocator.getLeastSignificantBits()).build());
    }
    if (clearedAt.isPresent()) {
      builder.setClearedAt(com.google.protobuf.Timestamp.newBuilder().setSeconds(clearedAt.get().getEpochSecond()).setNanos(clearedAt.get().getNano()).build());
    }
    if (tag.isPresent()) {
      builder.setTag(this.tag.get());
    }
    return builder.build();
  }

  public UnderwritingFlag toTransport() {
    return toBuilder()
        .build();
  }

  public static UnderwritingFlag fromProto(com.socotra.coremodel.protobuf.UnderwritingFlag proto) {
    return new UnderwritingFlag(
         new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb()),
         proto.getLevel().isEmpty() ? null : com.socotra.coremodel.UnderwritingLevel.valueOf(proto.getLevel()),
         proto.hasNote() ? Optional.of(proto.getNote()) : Optional.empty(),
         proto.hasElementLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getElementLocator().getMsb(), proto.getElementLocator().getLsb())) : Optional.empty(),
         proto.getReferenceType().isEmpty() ? null : com.socotra.coremodel.UnderwritingReferenceType.valueOf(proto.getReferenceType()),
         new com.socotra.platform.tools.ULID(proto.getReferenceLocator().getMsb(), proto.getReferenceLocator().getLsb()),
         proto.hasClearedAt() ? Optional.of(java.time.Instant.ofEpochSecond(proto.getClearedAt().getSeconds(), proto.getClearedAt().getNanos())) : Optional.empty(),
         proto.hasTag() ? Optional.of(proto.getTag()) : Optional.empty()
    );
  }

  public static UnderwritingFlagBuilder builder() {
    return new UnderwritingFlagBuilder();
  }


  public UnderwritingFlagBuilder toBuilder() {
    return new UnderwritingFlagBuilder()
       .locator(this.locator)
       .level(this.level)
       .note(this.note)
       .elementLocator(this.elementLocator)
       .referenceType(this.referenceType)
       .referenceLocator(this.referenceLocator)
       .clearedAt(this.clearedAt)
       .tag(this.tag);
  }




  public static class UnderwritingFlagBuilder {
    private com.socotra.platform.tools.ULID locator;
    public UnderwritingFlagBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = locator;
      return this;
    }
    private com.socotra.coremodel.UnderwritingLevel level;
    public UnderwritingFlagBuilder level(com.socotra.coremodel.UnderwritingLevel level) {
      this.level = level;
      return this;
    }
    private Optional<java.lang.String> note;
    public UnderwritingFlagBuilder note(Optional<java.lang.String> note) {
      this.note = note;
      return this;
    }
    public UnderwritingFlagBuilder note(java.lang.String note) {
      this.note = Optional.ofNullable(note);
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> elementLocator;
    public UnderwritingFlagBuilder elementLocator(Optional<com.socotra.platform.tools.ULID> elementLocator) {
      this.elementLocator = elementLocator;
      return this;
    }
    public UnderwritingFlagBuilder elementLocator(com.socotra.platform.tools.ULID elementLocator) {
      this.elementLocator = Optional.ofNullable(elementLocator);
      return this;
    }
    private com.socotra.coremodel.UnderwritingReferenceType referenceType;
    public UnderwritingFlagBuilder referenceType(com.socotra.coremodel.UnderwritingReferenceType referenceType) {
      this.referenceType = referenceType;
      return this;
    }
    private com.socotra.platform.tools.ULID referenceLocator;
    public UnderwritingFlagBuilder referenceLocator(com.socotra.platform.tools.ULID referenceLocator) {
      this.referenceLocator = referenceLocator;
      return this;
    }
    private Optional<java.time.Instant> clearedAt;
    public UnderwritingFlagBuilder clearedAt(Optional<java.time.Instant> clearedAt) {
      this.clearedAt = clearedAt;
      return this;
    }
    public UnderwritingFlagBuilder clearedAt(java.time.Instant clearedAt) {
      this.clearedAt = Optional.ofNullable(clearedAt);
      return this;
    }
    private Optional<java.lang.String> tag;
    public UnderwritingFlagBuilder tag(Optional<java.lang.String> tag) {
      this.tag = tag;
      return this;
    }
    public UnderwritingFlagBuilder tag(java.lang.String tag) {
      this.tag = Optional.ofNullable(tag);
      return this;
    }
    public UnderwritingFlagBuilder() {
    }
    public UnderwritingFlag build() {
      return new UnderwritingFlag(
          locator,
          level,
          note,
          elementLocator,
          referenceType,
          referenceLocator,
          clearedAt,
          tag
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
