/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record UserAssociationCreateRequest(
    java.util.UUID userLocator,
    java.lang.String userAssociationRole,
    com.socotra.coremodel.TaskReferenceType referenceType,
    com.socotra.platform.tools.ULID referenceLocator
) 
{
  public UserAssociationCreateRequest {
    

    Objects.requireNonNull(userLocator, "userLocator is required but it is null");
    Objects.requireNonNull(userAssociationRole, "userAssociationRole is required but it is null");
    Objects.requireNonNull(referenceType, "referenceType is required but it is null");
    Objects.requireNonNull(referenceLocator, "referenceLocator is required but it is null");

 }

  public com.socotra.coremodel.protobuf.UserAssociationCreateRequest toProto() {
    com.socotra.coremodel.protobuf.UserAssociationCreateRequest.Builder builder = com.socotra.coremodel.protobuf.UserAssociationCreateRequest.newBuilder();
    if (userLocator != null) {
      builder.setUserLocator(com.socotra.protobuf.UUID.newBuilder().setMsb(userLocator.getMostSignificantBits()).setLsb(userLocator.getLeastSignificantBits()).build());
    }
    if (userAssociationRole != null) {
      builder.setUserAssociationRole(this.userAssociationRole);
    }
    if (referenceType != null) {
      builder.setReferenceType(this.referenceType.name());
    }
    if (referenceLocator != null) {
      builder.setReferenceLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(referenceLocator.getMostSignificantBits()).setLsb(referenceLocator.getLeastSignificantBits()).build());
    }
    return builder.build();
  }

  public UserAssociationCreateRequest toTransport() {
    return toBuilder()
        .build();
  }

  public static UserAssociationCreateRequest fromProto(com.socotra.coremodel.protobuf.UserAssociationCreateRequest proto) {
    return new UserAssociationCreateRequest(
         new java.util.UUID(proto.getUserLocator().getMsb(), proto.getUserLocator().getLsb()),
         proto.getUserAssociationRole(),
         proto.getReferenceType().isEmpty() ? null : com.socotra.coremodel.TaskReferenceType.valueOf(proto.getReferenceType()),
         new com.socotra.platform.tools.ULID(proto.getReferenceLocator().getMsb(), proto.getReferenceLocator().getLsb())
    );
  }

  public static UserAssociationCreateRequestBuilder builder() {
    return new UserAssociationCreateRequestBuilder();
  }


  public UserAssociationCreateRequestBuilder toBuilder() {
    return new UserAssociationCreateRequestBuilder()
       .userLocator(this.userLocator)
       .userAssociationRole(this.userAssociationRole)
       .referenceType(this.referenceType)
       .referenceLocator(this.referenceLocator);
  }




  public static class UserAssociationCreateRequestBuilder {
    private java.util.UUID userLocator;
    public UserAssociationCreateRequestBuilder userLocator(java.util.UUID userLocator) {
      this.userLocator = userLocator;
      return this;
    }
    private java.lang.String userAssociationRole;
    public UserAssociationCreateRequestBuilder userAssociationRole(java.lang.String userAssociationRole) {
      this.userAssociationRole = userAssociationRole;
      return this;
    }
    private com.socotra.coremodel.TaskReferenceType referenceType;
    public UserAssociationCreateRequestBuilder referenceType(com.socotra.coremodel.TaskReferenceType referenceType) {
      this.referenceType = referenceType;
      return this;
    }
    private com.socotra.platform.tools.ULID referenceLocator;
    public UserAssociationCreateRequestBuilder referenceLocator(com.socotra.platform.tools.ULID referenceLocator) {
      this.referenceLocator = referenceLocator;
      return this;
    }
    public UserAssociationCreateRequestBuilder() {
    }
    public UserAssociationCreateRequest build() {
      return new UserAssociationCreateRequest(
          userLocator,
          userAssociationRole,
          referenceType,
          referenceLocator
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }



  }
}
