/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.coremodel;

import java.util.*;
import java.util.function.Consumer;
import java.util.stream.*;
import com.socotra.protobuf.*;
import com.socotra.coremodel.protobuf.*;
import com.socotra.deployment.*;
import java.util.UUID;
import java.lang.reflect.Method;
import java.time.*;
import java.math.RoundingMode;
import java.util.function.*;
import com.socotra.platform.tools.ULID;
import com.fasterxml.jackson.core.type.TypeReference;

public record ValidationItem(
    java.lang.String elementType,
    Optional<com.socotra.platform.tools.ULID> locator,
    Collection<java.lang.String> errors
) 
{
  public ValidationItem {
    locator = locator == null ? Optional.empty() : locator;
    errors = errors == null ? List.of() : List.copyOf(errors);


 }

  public com.socotra.coremodel.protobuf.ValidationItem toProto() {
    com.socotra.coremodel.protobuf.ValidationItem.Builder builder = com.socotra.coremodel.protobuf.ValidationItem.newBuilder();
    if (elementType != null) {
      builder.setElementType(this.elementType);
    }
    if (locator.isPresent()) {
      builder.setLocator(com.socotra.protobuf.ULID.newBuilder().setMsb(locator.get().getMostSignificantBits()).setLsb(locator.get().getLeastSignificantBits()).build());
    }
    if (errors != null) {
      builder.addAllErrors(this.errors);
    }
    return builder.build();
  }

  public ValidationItem toTransport() {
    return toBuilder()
        .errors(List.of())
        .build();
  }

  public static ValidationItem fromProto(com.socotra.coremodel.protobuf.ValidationItem proto) {
    return new ValidationItem(
         proto.getElementType(),
         proto.hasLocator() ? Optional.of(new com.socotra.platform.tools.ULID(proto.getLocator().getMsb(), proto.getLocator().getLsb())) : Optional.empty(),
         proto.getErrorsList()
    );
  }

  public static ValidationItemBuilder builder() {
    return new ValidationItemBuilder();
  }


  public ValidationItemBuilder toBuilder() {
    return new ValidationItemBuilder()
       .elementType(this.elementType)
       .locator(this.locator)
       .errors(this.errors);
  }




  public static class ValidationItemBuilder {
    private java.lang.String elementType;
    public ValidationItemBuilder elementType(java.lang.String elementType) {
      this.elementType = elementType;
      return this;
    }
    private Optional<com.socotra.platform.tools.ULID> locator;
    public ValidationItemBuilder locator(Optional<com.socotra.platform.tools.ULID> locator) {
      this.locator = locator;
      return this;
    }
    public ValidationItemBuilder locator(com.socotra.platform.tools.ULID locator) {
      this.locator = Optional.ofNullable(locator);
      return this;
    }
    private Collection<java.lang.String> errors;
    public ValidationItemBuilder errors(Collection<java.lang.String> errors) {
      this.errors = errors;
      return this;
    }
    public ValidationItemBuilder() {
      errors = new ArrayList<>();
    }
    public ValidationItem build() {
      return new ValidationItem(
          elementType,
          locator,
          errors
      );
    }

    private <T> Collection<T> copyIfImmutable(Collection<T> c, Consumer<Collection<T>> consumer) {
      if(c == null) {
        c = new ArrayList<>();
      }
      try {
        consumer.accept(c);
      } catch(UnsupportedOperationException e) {
        c = new ArrayList<>(c);
        consumer.accept(c);
      }
      return c;
    }

    public ValidationItemBuilder addError(java.lang.String field) {
      this.errors = copyIfImmutable(this.errors, c -> c.add(field));
      return this;
    }
    public ValidationItemBuilder addErrors(Collection<java.lang.String> fields) {
      this.errors = copyIfImmutable(this.errors, c -> c.addAll(fields));
      return this;
    }
    public boolean hasErrors() {
      return !this.errors.isEmpty();
    }

  @Deprecated
  public ValidationItemBuilder addErrors(String... fields) {
    this.errors = this.copyIfImmutable(this.errors, (c) -> {
      c.addAll(Arrays.asList(fields));
    });
    return this;
  }
  }
}
