/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.core.type.*;
import com.socotra.coremodel.*;
import com.socotra.coremodel.constraints.*;
import com.socotra.coremodel.views.Internal;
import com.socotra.deployment.*;
import com.socotra.platform.tools.ULID;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.*;
import java.util.stream.Collectors;

public record AccidentalDamageQuote(
    ZeroDeductible zeroDeductible,
    AccidentalDamageQuoteData data,
    @JsonView({Internal.class}) Element element
    ) implements AccidentalDamage, Validatable<AccidentalDamageQuote>, Elemental, CustomerObject, SensitiveDataHolder<AccidentalDamageQuote.AccidentalDamageQuoteData> {

  public static final String TYPE = "AccidentalDamageQuote";

  public String type() { return TYPE; }

  public AccidentalDamageQuote maskData(DataMaskingLevel level) {
    AccidentalDamageQuoteBuilder builder = toBuilder();
    builder.data(this.data.maskData(level));
    return builder.build();
  }

  public AccidentalDamageQuote anonymizeData() {
    AccidentalDamageQuoteBuilder builder = toBuilder();
    builder.data(this.data.anonymizeData());
    return builder.build();
  }

  public AccidentalDamageQuote {
    if(data == null) {
      data = AccidentalDamageQuoteData.builder().build();
    }
  }

  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    Collection<ValidationItem> validationItems = new ArrayList<>();
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder()
        .elementType(type()).locator(element.locator());
    if (this.zeroDeductible == null) {
      validationItemBuilder.addError("'zeroDeductible' is required");
    } else {
      validationItems.addAll(this.zeroDeductible.validate(config, context));
    }

    this.data.validate(config, context).forEach(error -> error.errors().forEach(validationItemBuilder::addError));
    if (validationItemBuilder.hasErrors()) {
      validationItems.add(validationItemBuilder.build());
    }
    return validationItems;
  }

  @Override
  public AccidentalDamageQuote correct(DeploymentConfig config, ValidationErrorResolver resolver) {
    AccidentalDamageQuoteBuilder builder = toBuilder();
    Map<String, java.lang.reflect.RecordComponent> fields = Arrays.stream(this.getClass().getRecordComponents()).collect(Collectors.toMap(java.lang.reflect.RecordComponent::getName, c -> c));
    if(zeroDeductible != null) {
      builder.zeroDeductible(zeroDeductible.correct(config, resolver));
    } else {
      resolver.correct(this, fields.get("zeroDeductible"), builder::zeroDeductible, new Required<>(zeroDeductible));
    }
    builder.data(this.data.correct(config, resolver));

    return builder.build();
  }

  public AccidentalDamageQuote applyDefaults(DeploymentConfig config) {
    AccidentalDamageQuoteBuilder builder = toBuilder();
    if (this.zeroDeductible == null) { builder.zeroDeductible(com.socotra.deployment.customer.ZeroDeductible.defaultOption()); }
    return builder.build();
  }

  public AccidentalDamageQuote applyAvailabilityRemovals(Instant referenceDate) {
    AccidentalDamageQuoteBuilder builder = toBuilder();
    if (this.zeroDeductible != null) {
      builder.zeroDeductible(zeroDeductible.applyAvailabilityRemovals(referenceDate));
    }

    builder.data(this.data.applyAvailabilityRemovals(referenceDate));
    return builder.build();
  }

  @JsonIgnore
  public ULID locator() {
    return element.locator();
  }

  public Element toElement(DeploymentFactory factory) {
    Map<String, Object> ct = new HashMap<>();
    if (this.zeroDeductible != null) {
      ct.put("ZeroDeductible", this.zeroDeductible);
    }
    Collection<Element> subElements = List.of();
    Map<String, Object> data = CustomerDataHolder.transform(factory, this.data());
    return element.toBuilder()
        .type(type())
        .elements(Collections.unmodifiableCollection(subElements))
        .coverageTerms(ct)
        .data(data)
        .category(ElementCategory.coverage)
        .build();
  }

  public static AccidentalDamageQuote fromElement(DeploymentFactory factory, Element element) {
    if (element == null) {
      return null;
    }
    return new AccidentalDamageQuote(
        com.socotra.deployment.customer.ZeroDeductible.fromMap(element.coverageTerms()),
        element.resolve(AccidentalDamageQuoteData.TYPE, factory),
        element);
  }

  public static AccidentalDamageQuoteBuilder builder(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ULID staticLocator, Instant originalEffectiveTime) {
    Element origin = Element.builder()
        .tenantLocator(tenantLocator)
        .type("AccidentalDamageQuote")
        .locator(ULID.generate())
        .staticLocator(staticLocator)
        .rootLocator(rootLocator)
        .parentLocator(parentLocator)
        .originalEffectiveTime(originalEffectiveTime)
        .build();
    return new AccidentalDamageQuoteBuilder().element(origin).data(AccidentalDamageQuoteData.builder().build());
  }

  public AccidentalDamageQuoteBuilder toBuilder() {
    return new AccidentalDamageQuoteBuilder()
        .zeroDeductible(this.zeroDeductible)

        .data(this.data)
        .element(this.element);
  }

  public static class AccidentalDamageQuoteBuilder {
    private ZeroDeductible zeroDeductible;
    public AccidentalDamageQuoteBuilder zeroDeductible(ZeroDeductible zeroDeductible) { this.zeroDeductible = zeroDeductible; return this; }

    private AccidentalDamageQuoteData data;
    public AccidentalDamageQuoteBuilder data(AccidentalDamageQuoteData data) { this.data = data; return this; }
    private Element element;
    public AccidentalDamageQuoteBuilder element(Element element) { this.element = element; return this; }

    private AccidentalDamageQuoteBuilder() {}

    public AccidentalDamageQuote build() {
      return new AccidentalDamageQuote(
          this.zeroDeductible,
          this.data,
          this.element
      );
    }
  }

  public record AccidentalDamageQuoteData(String labourCovered, String partsCovered) implements AccidentalDamageData, CustomerObject, Validatable<AccidentalDamageQuoteData> {
    public static final String TYPE = "AccidentalDamageQuoteData";
    public static final Set<String> labourCoveredOptions = Set.of("true","false");
    public static final Set<String> partsCoveredOptions = Set.of("true","false");

    public AccidentalDamageQuoteData {
    if (labourCovered == null || labourCovered.isBlank()) { labourCovered = "true";}
    if (partsCovered == null || partsCovered.isBlank()) { partsCovered = "true";}
    }

    public String type() { return TYPE; }

    public AccidentalDamageQuoteData maskData(DataMaskingLevel level) {
      AccidentalDamageQuoteDataBuilder builder = toBuilder();
      if (level == DataMaskingLevel.level1) {
      }
      if (level == DataMaskingLevel.level2) {
      }
      if (level == DataMaskingLevel.none) {
      }
      return builder.build();
    }

    public AccidentalDamageQuoteData anonymizeData() {
      AccidentalDamageQuoteDataBuilder builder = toBuilder();
      return builder.build();
    }

    @Override
    public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
      ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder().elementType(TYPE);
      if (labourCovered != null && labourCovered.length() > 20000) { validationItemBuilder.addError("'accidentalDamageQuoteData.labourCovered' length is more than max length of 20000"); }
      if (labourCovered != null && !labourCoveredOptions.contains(labourCovered)) { validationItemBuilder.addError("Property 'accidentalDamageQuoteData.labourCovered' should be one of " + labourCoveredOptions); }
      if (partsCovered != null && partsCovered.length() > 20000) { validationItemBuilder.addError("'accidentalDamageQuoteData.partsCovered' length is more than max length of 20000"); }
      if (partsCovered != null && !partsCoveredOptions.contains(partsCovered)) { validationItemBuilder.addError("Property 'accidentalDamageQuoteData.partsCovered' should be one of " + partsCoveredOptions); }

      return validationItemBuilder.hasErrors() ? List.of(validationItemBuilder.build()) : List.of();
    }

    @Override
    public AccidentalDamageQuoteData correct(DeploymentConfig config, ValidationErrorResolver resolver) {
      AccidentalDamageQuoteDataBuilder builder = this.toBuilder();
      Map<String, java.lang.reflect.RecordComponent> fields = Arrays.stream(this.getClass().getRecordComponents()).collect(java.util.stream.Collectors.toMap(java.lang.reflect.RecordComponent::getName, c -> c));
      resolver.correct(this, fields.get("labourCovered"), builder::labourCovered, new MaxLength(20000), new Options<>(labourCoveredOptions));
      resolver.correct(this, fields.get("partsCovered"), builder::partsCovered, new MaxLength(20000), new Options<>(partsCoveredOptions));

      return builder.build();
    }

    @Override
    public AccidentalDamageQuoteData applyAvailabilityRemovals(Instant referenceDate) {
      AccidentalDamageQuoteDataBuilder builder = toBuilder();

      return builder.build();
    }

    public static AccidentalDamageQuoteDataBuilder builder() {
      return new AccidentalDamageQuoteDataBuilder();
    }
    public AccidentalDamageQuoteDataBuilder toBuilder() {
      return new AccidentalDamageQuoteDataBuilder()
      .labourCovered(this.labourCovered)
      .partsCovered(this.partsCovered);
    }

    public static class AccidentalDamageQuoteDataBuilder {
      private String labourCovered;
      public AccidentalDamageQuoteDataBuilder labourCovered(String labourCovered) { this.labourCovered = labourCovered; return this; }
      private String partsCovered;
      public AccidentalDamageQuoteDataBuilder partsCovered(String partsCovered) { this.partsCovered = partsCovered; return this; }

      public AccidentalDamageQuoteData build() {
        return new AccidentalDamageQuoteData(labourCovered, partsCovered);
      }
    }
  }

  public static boolean canAccessFields(DataMaskingLevel level, Map<String, Object> fields) {
    return true;
  }
  public static DataMaskingLevel fieldsMaximumLevel(Map<String, Object> fields) {
    DataMaskingLevel maxLevel = DataMaskingLevel.none;
    return maxLevel;
  }
  public static Map<String, Object> anonymizeFields(Map<String, Object> fields) {
    Map<String, Object> result = new HashMap<>();
    for (Map.Entry<String, Object> entry: fields.entrySet()) {
      String keyName = entry.getKey();
      Object fieldValue = entry.getValue();
      result.put(keyName, fieldValue);
    }
    return result;
  }
}