/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.socotra.coremodel.*;

import java.time.*;
import java.util.*;
import java.math.*;
import java.util.function.Consumer;

import com.socotra.platform.tools.ULID;

public interface AccidentalDamage extends Chargeable {
  ZeroDeductible zeroDeductible();
  AccidentalDamageData data();

  @Override
  default void consumeChargeableElements(Consumer<Chargeable> consumer) {
  }

  public interface AccidentalDamageData {
    String labourCovered();
    String partsCovered();
  }

  @Override
  default Collection<Charge> charges() {
    return Arrays.asList(Charge.values());
  }

  enum Charge implements com.socotra.coremodel.ChargeType {
    premium(ChargeType.premium),
    tax(ChargeType.tax),
    premiumExclDiscount(ChargeType.premiumExclDiscount);

    private final ChargeType chargeType;

    Charge(ChargeType chargeType) {
      this.chargeType = chargeType;
    }

    @Override
    public ChargeCategory category() {
      return chargeType.category();
    }

    @Override
    public ChargeInvoicing invoicing() {
      return chargeType.invoicing();
    }

    @Override
    public ChargeHandling handling() {
      return chargeType.handling();
    }
  }
}
