/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;
import com.socotra.coremodel.*;
import com.socotra.platform.tools.*;
import java.math.*;
import java.time.*;

public record CountyCodes(String countyCode, String county) implements CustomerObject, TableMetadata {
    @Override
    public String type() {
        return staticName();
    }

    public static String getStaticName() {
        return "CountyCodes";
    }

    @Override
    public String staticName() {
        return getStaticName();
    }

    public static SelectionTimeBasis getSelectionTimeBasis() {
        return SelectionTimeBasis.termStartTime;
    }

    @Override
    public SelectionTimeBasis selectionTimeBasis() {
        return getSelectionTimeBasis();
    }

    public static byte[] makeKey(String countyCode) {
        return TableUtils.makeKey(countyCode);
    }

    @Override
    public byte[] makeKey() {
        return makeKey(countyCode);
    }
}
