/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.socotra.coremodel.*;
import com.socotra.coremodel.constraints.*;
import com.socotra.deployment.DeploymentConfig;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.regex.*;
import java.util.stream.Collectors;

public record CoverData(String labourCovered, LocalDate manufacturerLabourGuaranteeEndDate, LocalDate manufacturerPartsGuaranteeEndDate, String partsCovered, LocalDate perilEndDate, LocalDate perilStartDate, BigDecimal premium, BigDecimal taxAmount, BigDecimal taxRate) implements CustomerObject, Validatable<CoverData> {

  public static final String TYPE = "CoverData";
    public static final Set<String> labourCoveredOptions = Set.of("true","false","");
    public static final Set<String> partsCoveredOptions = Set.of("true","false","");

  public CoverData {
      if (premium != null) { premium = com.socotra.platform.tools.NumberUtils.trimScale(premium, 2, RoundingMode.HALF_EVEN);}
    if (taxRate != null) { taxRate = com.socotra.platform.tools.NumberUtils.trimScale(taxRate, 5, RoundingMode.HALF_EVEN);}
    if (taxAmount != null) { taxAmount = com.socotra.platform.tools.NumberUtils.trimScale(taxAmount, 2, RoundingMode.HALF_EVEN);}
  }

  public CoverData() {
    this(null, null, null, null, null, null, null, null, null);
  }

  @Override
  public String type() { return TYPE; }

  public CoverData maskData(DataMaskingLevel level) {
    CoverDataBuilder builder = toBuilder();
    if (level == DataMaskingLevel.level1) {
    }
    if (level == DataMaskingLevel.level2) {
    }
    if (level == DataMaskingLevel.none) {
    }
    return builder.build();
  }

  public CoverData anonymizeData() {
    CoverDataBuilder builder = toBuilder();
    return builder.build();
  }

  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder().elementType(TYPE);
      if (labourCovered != null && labourCovered.length() > 20000) { validationItemBuilder.addError("'coverData.labourCovered' length is more than max length of 20000"); }
      if (labourCovered != null && !labourCoveredOptions.contains(labourCovered)) { validationItemBuilder.addError("Property 'coverData.labourCovered' should be one of " + labourCoveredOptions); }
      if (partsCovered != null && partsCovered.length() > 20000) { validationItemBuilder.addError("'coverData.partsCovered' length is more than max length of 20000"); }
      if (partsCovered != null && !partsCoveredOptions.contains(partsCovered)) { validationItemBuilder.addError("Property 'coverData.partsCovered' should be one of " + partsCoveredOptions); }

    return validationItemBuilder.hasErrors() ? List.of(validationItemBuilder.build()) : List.of();
  }

  @Override
  public CoverData correct(DeploymentConfig config, ValidationErrorResolver resolver) {
    CoverDataBuilder builder = this.toBuilder();
    Map<String, java.lang.reflect.RecordComponent> fields = Arrays.stream(this.getClass().getRecordComponents()).collect(java.util.stream.Collectors.toMap(java.lang.reflect.RecordComponent::getName, c -> c));
    resolver.correct(this, fields.get("labourCovered"), builder::labourCovered, new MaxLength(20000), new Options<>(labourCoveredOptions));
    resolver.correct(this, fields.get("partsCovered"), builder::partsCovered, new MaxLength(20000), new Options<>(partsCoveredOptions));

    return builder.build();
  }

  @Override
  public CoverData applyAvailabilityRemovals(Instant referenceDate) {
    CoverDataBuilder builder = toBuilder();

    return builder.build();
  }

  public static CoverDataBuilder builder() {
    return new CoverDataBuilder();
  }
  public CoverDataBuilder toBuilder() {
    return new CoverDataBuilder()
      .labourCovered(this.labourCovered)
      .manufacturerLabourGuaranteeEndDate(this.manufacturerLabourGuaranteeEndDate)
      .manufacturerPartsGuaranteeEndDate(this.manufacturerPartsGuaranteeEndDate)
      .partsCovered(this.partsCovered)
      .perilEndDate(this.perilEndDate)
      .perilStartDate(this.perilStartDate)
      .premium(this.premium)
      .taxAmount(this.taxAmount)
      .taxRate(this.taxRate);
  }

  public static class CoverDataBuilder {
      private String labourCovered;
      public CoverDataBuilder labourCovered(String labourCovered) { this.labourCovered = labourCovered; return this; }
      private LocalDate manufacturerLabourGuaranteeEndDate;
      public CoverDataBuilder manufacturerLabourGuaranteeEndDate(LocalDate manufacturerLabourGuaranteeEndDate) { this.manufacturerLabourGuaranteeEndDate = manufacturerLabourGuaranteeEndDate; return this; }
      private LocalDate manufacturerPartsGuaranteeEndDate;
      public CoverDataBuilder manufacturerPartsGuaranteeEndDate(LocalDate manufacturerPartsGuaranteeEndDate) { this.manufacturerPartsGuaranteeEndDate = manufacturerPartsGuaranteeEndDate; return this; }
      private String partsCovered;
      public CoverDataBuilder partsCovered(String partsCovered) { this.partsCovered = partsCovered; return this; }
      private LocalDate perilEndDate;
      public CoverDataBuilder perilEndDate(LocalDate perilEndDate) { this.perilEndDate = perilEndDate; return this; }
      private LocalDate perilStartDate;
      public CoverDataBuilder perilStartDate(LocalDate perilStartDate) { this.perilStartDate = perilStartDate; return this; }
      private BigDecimal premium;
      public CoverDataBuilder premium(BigDecimal premium) { this.premium = premium; return this; }
      private BigDecimal taxAmount;
      public CoverDataBuilder taxAmount(BigDecimal taxAmount) { this.taxAmount = taxAmount; return this; }
      private BigDecimal taxRate;
      public CoverDataBuilder taxRate(BigDecimal taxRate) { this.taxRate = taxRate; return this; }
    public CoverData build() {
      return new CoverData(labourCovered, manufacturerLabourGuaranteeEndDate, manufacturerPartsGuaranteeEndDate, partsCovered, perilEndDate, perilStartDate, premium, taxAmount, taxRate);
    }
  }

  public static boolean canAccessFields(DataMaskingLevel level, Map<String, Object> fields) {
    return true;
  }
  public static DataMaskingLevel fieldsMaximumLevel(Map<String, Object> fields) {
    DataMaskingLevel maxLevel = DataMaskingLevel.none;
    return maxLevel;
  }
  public static Map<String, Object> anonymizeFields(Map<String, Object> fields) {
    Map<String, Object> result = new HashMap<>();
    for (Map.Entry<String, Object> entry: fields.entrySet()) {
      String keyName = entry.getKey();
      Object fieldValue = entry.getValue();
      result.put(keyName, fieldValue);
    }
    return result;
  }
}