/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.core.type.*;
import com.socotra.coremodel.*;
import com.socotra.coremodel.constraints.*;
import com.socotra.coremodel.views.Internal;
import com.socotra.deployment.*;
import com.socotra.platform.tools.ULID;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Consumer;
import java.util.regex.*;
import java.util.stream.Collectors;

public record ItemPolicy(
    AccidentalDamagePolicy accidentalDamage,
    BreakdownPolicy breakdown,
    TheftPolicy theft,
    ItemPolicyData data,
    @JsonView({Internal.class}) Element element
    ) implements Item, Validatable<ItemPolicy>, Elemental, CustomerObject, SensitiveDataHolder<ItemPolicy.ItemPolicyData> {

  public static final String TYPE = "ItemPolicy";

  public String type() { return TYPE; }

  public ItemPolicy maskData(DataMaskingLevel level) {
    ItemPolicyBuilder builder = toBuilder();
    builder.data(this.data.maskData(level));
    if (this.accidentalDamage != null) {
      builder.accidentalDamage(accidentalDamage.maskData(level));
    }
    if (this.breakdown != null) {
      builder.breakdown(breakdown.maskData(level));
    }
    if (this.theft != null) {
      builder.theft(theft.maskData(level));
    }
    return builder.build();
  }

  public ItemPolicy anonymizeData() {
    ItemPolicyBuilder builder = toBuilder();
    builder.data(this.data.anonymizeData());
    if (this.accidentalDamage != null) {
      builder.accidentalDamage(accidentalDamage.anonymizeData());
    }
    if (this.breakdown != null) {
      builder.breakdown(breakdown.anonymizeData());
    }
    if (this.theft != null) {
      builder.theft(theft.anonymizeData());
    }
    return builder.build();
  }

  public ItemPolicy {
    if(data == null) {
      data = ItemPolicyData.builder().build();
    }
  }

  public Instant originalEffectiveTime() {
    return element.originalEffectiveTime().orElse(null);
  }
  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    Collection<ValidationItem> validationItems = new ArrayList<>();
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder()
        .elementType(type()).locator(element.locator());
    if (this.accidentalDamage != null) {
      validationItems.addAll(this.accidentalDamage.validate(config, context));
    }

    if (this.breakdown == null) {
      validationItemBuilder.addError("'breakdown' is required");
    } else {
      validationItems.addAll(this.breakdown.validate(config, context));
    }

    if (this.theft != null) {
      validationItems.addAll(this.theft.validate(config, context));
    }

    this.data.validate(config, context).forEach(error -> error.errors().forEach(validationItemBuilder::addError));
    if (validationItemBuilder.hasErrors()) {
      validationItems.add(validationItemBuilder.build());
    }
    return validationItems;
  }

  @Override
  public ItemPolicy correct(DeploymentConfig config, ValidationErrorResolver resolver) {
    ItemPolicyBuilder builder = toBuilder();
    Map<String, java.lang.reflect.RecordComponent> fields = Arrays.stream(this.getClass().getRecordComponents()).collect(Collectors.toMap(java.lang.reflect.RecordComponent::getName, c -> c));
    if(accidentalDamage != null) {
      builder.accidentalDamage(accidentalDamage.correct(config, resolver));
    }
    if(breakdown != null) {
      builder.breakdown(breakdown.correct(config, resolver));
    } else {
      resolver.correct(this, fields.get("breakdown"), builder::breakdown, new Required<>(breakdown));
    }
    if(theft != null) {
      builder.theft(theft.correct(config, resolver));
    }
    builder.data(this.data.correct(config, resolver));

    return builder.build();
  }

  public ItemPolicy applyDefaults(DeploymentConfig config) {
    ItemPolicyBuilder builder = toBuilder();
    if (this.accidentalDamage != null) { builder.accidentalDamage(this.accidentalDamage.applyDefaults(config)); }

    { BreakdownPolicy a = this.breakdown; if (this.breakdown == null) { a = BreakdownPolicy.builder(element.tenantLocator(), element.rootLocator(), element.locator(), null, null).build(); }; builder.breakdown(a.applyDefaults(config)); }

    if (this.theft != null) { builder.theft(this.theft.applyDefaults(config)); }

    return builder.build();
  }

  public ItemPolicy applyAvailabilityRemovals(Instant referenceDate) {
    ItemPolicyBuilder builder = toBuilder();
    if (this.accidentalDamage != null) {
      builder.accidentalDamage(accidentalDamage.applyAvailabilityRemovals(referenceDate));
    }

    if (this.breakdown != null) {
      builder.breakdown(breakdown.applyAvailabilityRemovals(referenceDate));
    }

    if (this.theft != null) {
      builder.theft(theft.applyAvailabilityRemovals(referenceDate));
    }

    builder.data(this.data.applyAvailabilityRemovals(referenceDate));
    return builder.build();
  }

  @JsonIgnore
  public ULID locator() {
    return element.locator();
  }

  public Element toElement(DeploymentFactory factory) {
    Map<String, Object> ct = Map.of();
    Collection<Element> subElements = new ArrayList<>();
    if (this.accidentalDamage != null) {
      subElements.add(this.accidentalDamage.toElement(factory));
    }
    if (this.breakdown != null) {
      subElements.add(this.breakdown.toElement(factory));
    }
    if (this.theft != null) {
      subElements.add(this.theft.toElement(factory));
    }

    Map<String, Object> data = CustomerDataHolder.transform(factory, this.data());
    return element.toBuilder()
        .type(type())
        .elements(Collections.unmodifiableCollection(subElements))
        .coverageTerms(ct)
        .data(data)
        .category(ElementCategory.exposure)
        .build();
  }

  public static ItemPolicy fromElement(DeploymentFactory factory, Element element) {
    if (element == null) {
      return null;
    }
    return new ItemPolicy(
        AccidentalDamagePolicy.fromElement(factory, element.elements().stream().filter(e -> e.type().equalsIgnoreCase(AccidentalDamagePolicy.TYPE)).findAny().orElse(null)),
        BreakdownPolicy.fromElement(factory, element.elements().stream().filter(e -> e.type().equalsIgnoreCase(BreakdownPolicy.TYPE)).findAny().orElse(null)),
        TheftPolicy.fromElement(factory, element.elements().stream().filter(e -> e.type().equalsIgnoreCase(TheftPolicy.TYPE)).findAny().orElse(null)),
        element.resolve(ItemPolicyData.TYPE, factory),
        element);
  }

  public static ItemPolicy copyFrom(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ItemQuote other) {
    if (other == null) {
      return null;
    }
    ItemPolicyBuilder builder = builder(tenantLocator, rootLocator, parentLocator, other.element().locator(), other.element().originalEffectiveTime().orElse(null));
    return builder
        .accidentalDamage(AccidentalDamagePolicy.copyFrom(tenantLocator, rootLocator, builder.element.locator(), other.accidentalDamage()))
        .breakdown(BreakdownPolicy.copyFrom(tenantLocator, rootLocator, builder.element.locator(), other.breakdown()))
        .theft(TheftPolicy.copyFrom(tenantLocator, rootLocator, builder.element.locator(), other.theft()))
        .data(ItemPolicyData.copyFrom(other.data()))
        .build();
  }

  public static ItemPolicy copyFrom(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ItemPolicy other) {
    if (other == null) {
      return null;
    }
    ItemPolicyBuilder builder = builder(tenantLocator, rootLocator, parentLocator, other.element().staticLocator(), other.element().originalEffectiveTime().orElse(null));
    return builder
        .accidentalDamage(AccidentalDamagePolicy.copyFrom(tenantLocator, rootLocator, builder.element.locator(), other.accidentalDamage()))
        .breakdown(BreakdownPolicy.copyFrom(tenantLocator, rootLocator, builder.element.locator(), other.breakdown()))
        .theft(TheftPolicy.copyFrom(tenantLocator, rootLocator, builder.element.locator(), other.theft()))
        .data(ItemPolicyData.copyFrom(other.data()))
        .build();
  }

  public static ItemPolicyBuilder builder(UUID tenantLocator, ULID rootLocator, ULID parentLocator, ULID staticLocator, Instant originalEffectiveTime) {
    Element origin = Element.builder()
        .tenantLocator(tenantLocator)
        .type("ItemPolicy")
        .locator(ULID.generate())
        .staticLocator(staticLocator)
        .rootLocator(rootLocator)
        .parentLocator(parentLocator)
        .originalEffectiveTime(originalEffectiveTime)
        .build();
    return new ItemPolicyBuilder().element(origin).data(ItemPolicyData.builder().build());
  }

  public ItemPolicyBuilder toBuilder() {
    return new ItemPolicyBuilder()
        .accidentalDamage(this.accidentalDamage)
.breakdown(this.breakdown)
.theft(this.theft)

        .data(this.data)
        .element(this.element);
  }

  public static class ItemPolicyBuilder {
    private AccidentalDamagePolicy accidentalDamage;
    public ItemPolicyBuilder accidentalDamage(AccidentalDamagePolicy accidentalDamage) { this.accidentalDamage = accidentalDamage; return this; }
    public ItemPolicyBuilder addAccidentalDamage(Consumer<AccidentalDamagePolicy.AccidentalDamagePolicyBuilder> mutator) { AccidentalDamagePolicy.AccidentalDamagePolicyBuilder builder = AccidentalDamagePolicy.builder(this.element.tenantLocator(), this.element.rootLocator(), this.element.locator(), null, null); mutator.accept(builder); this.accidentalDamage = builder.build(); return this; }
    private BreakdownPolicy breakdown;
    public ItemPolicyBuilder breakdown(BreakdownPolicy breakdown) { this.breakdown = breakdown; return this; }
    public ItemPolicyBuilder addBreakdown(Consumer<BreakdownPolicy.BreakdownPolicyBuilder> mutator) { BreakdownPolicy.BreakdownPolicyBuilder builder = BreakdownPolicy.builder(this.element.tenantLocator(), this.element.rootLocator(), this.element.locator(), null, null); mutator.accept(builder); this.breakdown = builder.build(); return this; }
    private TheftPolicy theft;
    public ItemPolicyBuilder theft(TheftPolicy theft) { this.theft = theft; return this; }
    public ItemPolicyBuilder addTheft(Consumer<TheftPolicy.TheftPolicyBuilder> mutator) { TheftPolicy.TheftPolicyBuilder builder = TheftPolicy.builder(this.element.tenantLocator(), this.element.rootLocator(), this.element.locator(), null, null); mutator.accept(builder); this.theft = builder.build(); return this; }
    private ItemPolicyData data;
    public ItemPolicyBuilder data(ItemPolicyData data) { this.data = data; return this; }
    private Element element;
    public ItemPolicyBuilder element(Element element) { this.element = element; return this; }

    private ItemPolicyBuilder() {}

    public ItemPolicy build() {
      return new ItemPolicy(
          this.accidentalDamage,
          this.breakdown,
          this.theft,
          this.data,
          this.element
      );
    }
  }

  public record ItemPolicyData(Boolean itemInWarrantyAtTakeup, Boolean itemInWorkingOrderAtTakeup, String itemTypeCode, Integer manufacturerLabourGuaranteePeriod, LocalDate purchaseDate, BigDecimal purchasePrice, Integer serialNumber) implements ItemData, CustomerObject, Validatable<ItemPolicyData> {
    public static final String TYPE = "ItemPolicyData";
    public static final Set<String> itemTypeCodeOptions = Set.of("WASHING_MACHINE","DISHWASHER","FRIDGE_FREEZER","TUMBLE_DRYER","OVEN");

    public ItemPolicyData {
      if (purchasePrice != null) { purchasePrice = com.socotra.platform.tools.NumberUtils.trimScale(purchasePrice, 2, RoundingMode.HALF_EVEN);}
    }

    public String type() { return TYPE; }

    public ItemPolicyData maskData(DataMaskingLevel level) {
      ItemPolicyDataBuilder builder = toBuilder();
      if (level == DataMaskingLevel.level1) {
      }
      if (level == DataMaskingLevel.level2) {
      }
      if (level == DataMaskingLevel.none) {
      }
      return builder.build();
    }

    public ItemPolicyData anonymizeData() {
      ItemPolicyDataBuilder builder = toBuilder();
      return builder.build();
    }

    @Override
    public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
      ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder().elementType(TYPE);
      if (itemInWarrantyAtTakeup == null) { validationItemBuilder.addError("Non optional property 'itemPolicyData.itemInWarrantyAtTakeup' is missing"); }
      if (itemInWorkingOrderAtTakeup == null) { validationItemBuilder.addError("Non optional property 'itemPolicyData.itemInWorkingOrderAtTakeup' is missing"); }
      if (itemTypeCode == null || itemTypeCode.isBlank()) { validationItemBuilder.addError("Non optional property 'itemPolicyData.itemTypeCode' is missing"); }
      if (itemTypeCode != null && itemTypeCode.length() > 20000) { validationItemBuilder.addError("'itemPolicyData.itemTypeCode' length is more than max length of 20000"); }
      if (itemTypeCode != null && !itemTypeCodeOptions.contains(itemTypeCode)) { validationItemBuilder.addError("Property 'itemPolicyData.itemTypeCode' should be one of " + itemTypeCodeOptions); }
      if (purchaseDate == null) { validationItemBuilder.addError("Non optional property 'itemPolicyData.purchaseDate' is missing"); }
      if (purchasePrice == null) { validationItemBuilder.addError("Non optional property 'itemPolicyData.purchasePrice' is missing"); }
      if (serialNumber == null) { validationItemBuilder.addError("Non optional property 'itemPolicyData.serialNumber' is missing"); }

      return validationItemBuilder.hasErrors() ? List.of(validationItemBuilder.build()) : List.of();
    }

    @Override
    public ItemPolicyData correct(DeploymentConfig config, ValidationErrorResolver resolver) {
      ItemPolicyDataBuilder builder = this.toBuilder();
      Map<String, java.lang.reflect.RecordComponent> fields = Arrays.stream(this.getClass().getRecordComponents()).collect(java.util.stream.Collectors.toMap(java.lang.reflect.RecordComponent::getName, c -> c));
      resolver.correct(this, fields.get("itemInWarrantyAtTakeup"), builder::itemInWarrantyAtTakeup, new Required<>(itemInWarrantyAtTakeup));
      resolver.correct(this, fields.get("itemInWorkingOrderAtTakeup"), builder::itemInWorkingOrderAtTakeup, new Required<>(itemInWorkingOrderAtTakeup));
      resolver.correct(this, fields.get("itemTypeCode"), builder::itemTypeCode, new Required<>(itemTypeCode), new MaxLength(20000), new Options<>(itemTypeCodeOptions));
      resolver.correct(this, fields.get("purchaseDate"), builder::purchaseDate, new Required<>(purchaseDate));
      resolver.correct(this, fields.get("purchasePrice"), builder::purchasePrice, new Required<>(purchasePrice));
      resolver.correct(this, fields.get("serialNumber"), builder::serialNumber, new Required<>(serialNumber));

      return builder.build();
    }

    @Override
    public ItemPolicyData applyAvailabilityRemovals(Instant referenceDate) {
      ItemPolicyDataBuilder builder = toBuilder();

      return builder.build();
    }

    public static ItemPolicyDataBuilder builder() {
      return new ItemPolicyDataBuilder();
    }
    public ItemPolicyDataBuilder toBuilder() {
      return new ItemPolicyDataBuilder()
      .itemInWarrantyAtTakeup(this.itemInWarrantyAtTakeup)
      .itemInWorkingOrderAtTakeup(this.itemInWorkingOrderAtTakeup)
      .itemTypeCode(this.itemTypeCode)
      .manufacturerLabourGuaranteePeriod(this.manufacturerLabourGuaranteePeriod)
      .purchaseDate(this.purchaseDate)
      .purchasePrice(this.purchasePrice)
      .serialNumber(this.serialNumber);
    }

    public static class ItemPolicyDataBuilder {
      private Boolean itemInWarrantyAtTakeup;
      public ItemPolicyDataBuilder itemInWarrantyAtTakeup(Boolean itemInWarrantyAtTakeup) { this.itemInWarrantyAtTakeup = itemInWarrantyAtTakeup; return this; }
      private Boolean itemInWorkingOrderAtTakeup;
      public ItemPolicyDataBuilder itemInWorkingOrderAtTakeup(Boolean itemInWorkingOrderAtTakeup) { this.itemInWorkingOrderAtTakeup = itemInWorkingOrderAtTakeup; return this; }
      private String itemTypeCode;
      public ItemPolicyDataBuilder itemTypeCode(String itemTypeCode) { this.itemTypeCode = itemTypeCode; return this; }
      private Integer manufacturerLabourGuaranteePeriod;
      public ItemPolicyDataBuilder manufacturerLabourGuaranteePeriod(Integer manufacturerLabourGuaranteePeriod) { this.manufacturerLabourGuaranteePeriod = manufacturerLabourGuaranteePeriod; return this; }
      private LocalDate purchaseDate;
      public ItemPolicyDataBuilder purchaseDate(LocalDate purchaseDate) { this.purchaseDate = purchaseDate; return this; }
      private BigDecimal purchasePrice;
      public ItemPolicyDataBuilder purchasePrice(BigDecimal purchasePrice) { this.purchasePrice = purchasePrice; return this; }
      private Integer serialNumber;
      public ItemPolicyDataBuilder serialNumber(Integer serialNumber) { this.serialNumber = serialNumber; return this; }

      public ItemPolicyData build() {
        return new ItemPolicyData(itemInWarrantyAtTakeup, itemInWorkingOrderAtTakeup, itemTypeCode, manufacturerLabourGuaranteePeriod, purchaseDate, purchasePrice, serialNumber);
      }
    }

    public static ItemPolicyData copyFrom(ItemQuote.ItemQuoteData other) {
      if (other == null) {
        return null;
      }
      return new ItemPolicyData(
          other.itemInWarrantyAtTakeup(),
          other.itemInWorkingOrderAtTakeup(),
          other.itemTypeCode(),
          other.manufacturerLabourGuaranteePeriod(),
          other.purchaseDate(),
          other.purchasePrice(),
          other.serialNumber()
      );
    }

    public static ItemPolicyData copyFrom(ItemPolicyData other) {
      if (other == null) {
        return null;
      }
      return new ItemPolicyData(
          other.itemInWarrantyAtTakeup(),
          other.itemInWorkingOrderAtTakeup(),
          other.itemTypeCode(),
          other.manufacturerLabourGuaranteePeriod(),
          other.purchaseDate(),
          other.purchasePrice(),
          other.serialNumber()
      );
    }
  }

  public static boolean canAccessFields(DataMaskingLevel level, Map<String, Object> fields) {
    return true;
  }
  public static DataMaskingLevel fieldsMaximumLevel(Map<String, Object> fields) {
    DataMaskingLevel maxLevel = DataMaskingLevel.none;
    return maxLevel;
  }
  public static Map<String, Object> anonymizeFields(Map<String, Object> fields) {
    Map<String, Object> result = new HashMap<>();
    for (Map.Entry<String, Object> entry: fields.entrySet()) {
      String keyName = entry.getKey();
      Object fieldValue = entry.getValue();
      result.put(keyName, fieldValue);
    }
    return result;
  }
}