/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.socotra.coremodel.*;
import com.socotra.coremodel.constraints.*;
import com.socotra.deployment.DeploymentConfig;
import com.socotra.platform.tools.ULID;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.regex.*;
import java.util.stream.Collectors;

public record StandardPayment(
  ULID locator,
  PaymentState paymentState,
  BigDecimal amount,
  String currency,
  List<CreditItem> targets,
  Optional<ULID> accountLocator,
  Optional<ULID> financialInstrumentLocator,
  Optional<ExternalCashTransactionMethod> transactionMethod,
  Optional<String> transactionNumber,
  Optional<PaymentMode> paymentMode,
  Optional<ULID> aggregatePaymentLocator,
  Collection<Subpayment> subpayments,
  StandardPaymentData data
) implements Payment<StandardPayment.StandardPaymentData>, CustomerObject, Validatable<StandardPayment> {

  public static final String TYPE = "StandardPayment";

  @Override
  public String type() { return TYPE; }

  @Override
  public StandardPayment maskData(DataMaskingLevel level) {
    return toBuilder().data(data.maskData(level)).build();
  }

  @Override
  public StandardPayment anonymizeData() {
    return toBuilder().data(data.anonymizeData()).build();
  }

  public StandardPayment {
    if(data == null) {
      data = StandardPaymentData.builder().build();
    }
  }

  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    ValidationItem.ValidationItemBuilder builder = ValidationItem.builder().elementType(TYPE);
    this.data.validate(config, context).forEach(error -> error.errors().forEach(builder::addError));
    return builder.hasErrors() ? List.of(builder.build()) : List.of();
  }

  // For backwards compatibility with existing plugin references due to changing state to paymentState
  @Deprecated
  public PaymentState state() {
    return paymentState;
  }

  public static StandardPaymentBuilder builder() {
    return new StandardPaymentBuilder();
  }

  public StandardPaymentBuilder toBuilder() {
    return new StandardPaymentBuilder()
          .locator(this.locator)
          .paymentState(this.paymentState)
          .amount(this.amount)
          .currency(this.currency)
          .targets(this.targets)
          .accountLocator(this.accountLocator)
          .financialInstrumentLocator(this.financialInstrumentLocator)
          .transactionMethod(this.transactionMethod)
          .transactionNumber(this.transactionNumber)
          .paymentMode(this.paymentMode)
          .aggregatePaymentLocator(this.aggregatePaymentLocator)
          .subpayments(this.subpayments)
          .data(this.data);
  }

  public static class StandardPaymentBuilder {
    private ULID locator;
    private PaymentState paymentState;
    private BigDecimal amount;
    private String currency;
    private List<CreditItem> targets;
    private Optional<ULID> accountLocator;
    private Optional<ULID> financialInstrumentLocator;
    private Optional<ExternalCashTransactionMethod> transactionMethod;
    private Optional<String> transactionNumber;
    private Optional<PaymentMode> paymentMode;
    private Optional<ULID> aggregatePaymentLocator;
    private Collection<Subpayment> subpayments;
    private StandardPaymentData data;

    public StandardPaymentBuilder locator(ULID locator) {this.locator = locator; return this;}
    public StandardPaymentBuilder state(PaymentState state) {this.paymentState = state; return this;}
    public StandardPaymentBuilder paymentState(PaymentState paymentState) {this.paymentState = paymentState; return this;}
    public StandardPaymentBuilder amount(BigDecimal amount) {this.amount = amount; return this;}
    public StandardPaymentBuilder currency(String currency) {this.currency = currency; return this;}
    public StandardPaymentBuilder targets(List<CreditItem> targets) {this.targets = targets == null ? List.of() : List.copyOf(targets); return this;}
    public StandardPaymentBuilder accountLocator(Optional<ULID> accountLocator) {this.accountLocator = accountLocator; return this;}
    public StandardPaymentBuilder accountLocator(ULID accountLocator) {this.accountLocator = Optional.ofNullable(accountLocator); return this;}
    public StandardPaymentBuilder financialInstrumentLocator(Optional<ULID> financialInstrumentLocator) {this.financialInstrumentLocator = financialInstrumentLocator; return this;}
    public StandardPaymentBuilder financialInstrumentLocator(ULID financialInstrumentLocator) {this.financialInstrumentLocator = Optional.ofNullable(financialInstrumentLocator); return this;}
    public StandardPaymentBuilder transactionMethod(Optional<ExternalCashTransactionMethod> transactionMethod) {this.transactionMethod = transactionMethod; return this;}
    public StandardPaymentBuilder transactionMethod(ExternalCashTransactionMethod transactionMethod) {this.transactionMethod = Optional.ofNullable(transactionMethod); return this;}
    public StandardPaymentBuilder transactionNumber(Optional<String> transactionNumber) {this.transactionNumber = transactionNumber; return this;}
    public StandardPaymentBuilder transactionNumber(String transactionNumber) {this.transactionNumber = Optional.ofNullable(transactionNumber); return this;}
    public StandardPaymentBuilder paymentMode(Optional<PaymentMode> paymentMode) {this.paymentMode = paymentMode; return this;}
    public StandardPaymentBuilder paymentMode(PaymentMode paymentMode) {this.paymentMode = Optional.ofNullable(paymentMode); return this;}
    public StandardPaymentBuilder aggregatePaymentLocator(Optional<ULID> aggregatePaymentLocator) {this.aggregatePaymentLocator = aggregatePaymentLocator; return this;}
    public StandardPaymentBuilder aggregatePaymentLocator(ULID aggregatePaymentLocator) {this.aggregatePaymentLocator = Optional.ofNullable(aggregatePaymentLocator); return this;}
    public StandardPaymentBuilder subpayments(Collection<Subpayment> subpayments) { this.subpayments = subpayments; return this; }
    public StandardPaymentBuilder data(StandardPaymentData data) {this.data = data; return this;}

    public StandardPayment build() {
      return new StandardPayment(
          locator,
          paymentState,
          amount,
          currency,
          targets,
          accountLocator,
          financialInstrumentLocator,
          transactionMethod,
          transactionNumber,
          paymentMode,
          aggregatePaymentLocator,
          subpayments,
          data
      );
    }
  }

  public record StandardPaymentData(String errorCode, LocalDate paidDate, String paymentChannelCode) implements CustomerObject, Validatable<StandardPaymentData> {
    public static final String TYPE = "StandardPaymentData";
    public static final Set<String> paymentChannelCodeOptions = Set.of("Online","Phone","Branch","App");

    public String type() { return TYPE; }

    public StandardPaymentData maskData(DataMaskingLevel level) {
      StandardPaymentDataBuilder builder = toBuilder();
      if (level == DataMaskingLevel.level1) {
      }
      if (level == DataMaskingLevel.level2) {
      }
      if (level == DataMaskingLevel.none) {
      }
      return builder.build();
    }

    public StandardPaymentData anonymizeData() {
      StandardPaymentDataBuilder builder = toBuilder();
      return builder.build();
    }

    @Override
    public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
      ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder().elementType(TYPE);
      if (errorCode != null && errorCode.length() > 20000) { validationItemBuilder.addError("'standardPayment.errorCode' length is more than max length of 20000"); }
      if (paymentChannelCode != null && paymentChannelCode.length() > 20000) { validationItemBuilder.addError("'standardPayment.paymentChannelCode' length is more than max length of 20000"); }
      if (paymentChannelCode != null && !paymentChannelCodeOptions.contains(paymentChannelCode)) { validationItemBuilder.addError("Property 'standardPayment.paymentChannelCode' should be one of " + paymentChannelCodeOptions); }

      return validationItemBuilder.hasErrors() ? List.of(validationItemBuilder.build()) : List.of();
    }

    @Override
    public StandardPaymentData correct(DeploymentConfig config, ValidationErrorResolver resolver) {
      StandardPaymentDataBuilder builder = this.toBuilder();
      Map<String, java.lang.reflect.RecordComponent> fields = Arrays.stream(this.getClass().getRecordComponents()).collect(java.util.stream.Collectors.toMap(java.lang.reflect.RecordComponent::getName, c -> c));
      resolver.correct(this, fields.get("errorCode"), builder::errorCode, new MaxLength(20000));
      resolver.correct(this, fields.get("paymentChannelCode"), builder::paymentChannelCode, new MaxLength(20000), new Options<>(paymentChannelCodeOptions));

      return builder.build();
    }

    @Override
    public StandardPaymentData applyAvailabilityRemovals(Instant referenceDate) {
      StandardPaymentDataBuilder builder = toBuilder();

      return builder.build();
    }

    public static StandardPaymentDataBuilder builder() {
      return new StandardPaymentDataBuilder();
    }
    public StandardPaymentDataBuilder toBuilder() {
      return new StandardPaymentDataBuilder()
      .errorCode(this.errorCode)
      .paidDate(this.paidDate)
      .paymentChannelCode(this.paymentChannelCode);
    }

    public static class StandardPaymentDataBuilder {
      private String errorCode;
      public StandardPaymentDataBuilder errorCode(String errorCode) { this.errorCode = errorCode; return this; }
      private LocalDate paidDate;
      public StandardPaymentDataBuilder paidDate(LocalDate paidDate) { this.paidDate = paidDate; return this; }
      private String paymentChannelCode;
      public StandardPaymentDataBuilder paymentChannelCode(String paymentChannelCode) { this.paymentChannelCode = paymentChannelCode; return this; }

      public StandardPaymentData build() {
        return new StandardPaymentData(errorCode, paidDate, paymentChannelCode);
      }
    }
  }

  public static boolean canAccessFields(DataMaskingLevel level, Map<String, Object> fields) {
    return true;
  }
  public static DataMaskingLevel fieldsMaximumLevel(Map<String, Object> fields) {
    DataMaskingLevel maxLevel = DataMaskingLevel.none;
    return maxLevel;
  }
  public static Map<String, Object> anonymizeFields(Map<String, Object> fields) {
    Map<String, Object> result = new HashMap<>();
    for (Map.Entry<String, Object> entry: fields.entrySet()) {
      String keyName = entry.getKey();
      Object fieldValue = entry.getValue();
      result.put(keyName, fieldValue);
    }
    return result;
  }
}
