/*
  Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.socotra.coremodel.*;

import java.time.*;
import java.util.*;
import java.math.*;
import java.util.function.Consumer;

import com.socotra.platform.tools.ULID;

public interface ZenCover extends Chargeable {
  Collection<? extends Item> items();
  ZenCoverData data();

  @Override
  default void consumeChargeableElements(Consumer<Chargeable> consumer) {
    items().forEach(consumer);
  }

  public interface ZenCoverData {
    OffsetDateTime contractTermEndDate();
    Integer coolingOffPeriod();
    BigDecimal discountAmount();
    String discountProfileCode();
    String discountTerm();
    String discountType();
    LocalDate expectedRenewalDate();
    Integer gracePeriod();
    String gracePeriodType();
    Integer newBusinessWaitPeriod();
    Integer settlementPeriod();
    Integer settlementPeriodOffsetInDays();
    String settlementPeriodType();
  }

  @Override
  default Collection<Charge> charges() {
    return Arrays.asList(Charge.values());
  }

  enum Charge implements com.socotra.coremodel.ChargeType {
    fee(ChargeType.fee),
    premium(ChargeType.premium),
    tax(ChargeType.tax),
    premiumExclDiscount(ChargeType.premiumExclDiscount),
    settlement(ChargeType.settlement);

    private final ChargeType chargeType;

    Charge(ChargeType chargeType) {
      this.chargeType = chargeType;
    }

    @Override
    public ChargeCategory category() {
      return chargeType.category();
    }

    @Override
    public ChargeInvoicing invoicing() {
      return chargeType.invoicing();
    }

    @Override
    public ChargeHandling handling() {
      return chargeType.handling();
    }
  }
}
