/*
Autogenerated - DO NOT EDIT!
*/
package com.socotra.deployment.customer;

import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.core.type.*;
import com.socotra.platform.tools.ULID;
import com.socotra.coremodel.*;
import com.socotra.coremodel.constraints.*;
import com.socotra.deployment.*;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.regex.*;
import java.util.stream.Collectors;

public record ZenCoverQuickQuoteStaticData() implements CustomerObject, Validatable, SensitiveObject {
  public static final String TYPE = "ZenCoverQuickQuoteStaticData";

  public String type() { return TYPE; }

  @Override
  public Collection<ValidationItem> validate(DeploymentConfig config, ValidatableContext context) {
    ValidationItem.ValidationItemBuilder validationItemBuilder = ValidationItem.builder().elementType(TYPE);

      return validationItemBuilder.hasErrors() ? List.of(validationItemBuilder.build()) : List.of();
  }

  @Override
  public ZenCoverQuickQuoteStaticData correct(DeploymentConfig config, ValidationErrorResolver resolver) {
    return this;
  }

  @Override
  public ZenCoverQuickQuoteStaticData applyAvailabilityRemovals(Instant referenceDate) {
    ZenCoverQuickQuoteStaticDataBuilder builder = toBuilder();

    return builder.build();
  }

  public ZenCoverQuickQuoteStaticData maskData(DataMaskingLevel level) {
    ZenCoverQuickQuoteStaticDataBuilder builder = toBuilder();
    if (level == DataMaskingLevel.level1) {
    }
    if (level == DataMaskingLevel.level2) {
    }
    if (level == DataMaskingLevel.none) {
    }
    return builder.build();
  }

  public ZenCoverQuickQuoteStaticData anonymizeData() {
    ZenCoverQuickQuoteStaticDataBuilder builder = toBuilder();
    return builder.build();
  }

  public static ZenCoverQuickQuoteStaticDataBuilder builder() {
    return new ZenCoverQuickQuoteStaticDataBuilder();
  }
  public ZenCoverQuickQuoteStaticDataBuilder toBuilder() {
    return new ZenCoverQuickQuoteStaticDataBuilder();
  }

  public static class ZenCoverQuickQuoteStaticDataBuilder {

    public ZenCoverQuickQuoteStaticData build() {
      return new ZenCoverQuickQuoteStaticData();
    }
  }

  public static boolean canAccessFields(DataMaskingLevel level, Map<String, Object> fields) {
    return true;
  }
  public static DataMaskingLevel fieldsMaximumLevel(Map<String, Object> fields) {
    DataMaskingLevel maxLevel = DataMaskingLevel.none;
    return maxLevel;
  }
  public static Map<String, Object> anonymizeFields(Map<String, Object> fields) {
    Map<String, Object> result = new HashMap<>();
    for (Map.Entry<String, Object> entry: fields.entrySet()) {
      String keyName = entry.getKey();
      Object fieldValue = entry.getValue();
      result.put(keyName, fieldValue);
    }
    return result;
  }
}